# -*- coding: utf-8 -*-
"""Canonical hymn identities for the Sehling hymn tables.

Each entry: (canonical_title, [match patterns], literal_english, common_english, alternates)
- literal_english : word-for-word rendering of the German/Latin incipit
- common_english  : the received English hymn title, where the hymn has one
                    (usually from the Lutheran Service Book / The Lutheran Hymnal
                     tradition); None where no standard English title exists
- alternates      : rival common English titles, when more than one is in use.
                    These are the rows that want an external adjudication.
"""

L = [
 # ---- Advent ----
 ('Nun komm, der Heiden Heiland', [r'n[uo]n? k[uo]m+,? der he[iy]den'],
  'Now come, Savior of the heathen', 'Savior of the Nations, Come',
  ['Come, Thou Saviour of the Gentiles', 'Savior of the Nations, Come']),
 ('Gott, heiliger Schöpfer aller Stern', [r'godt hilige schepper aller stern', r'gott.*schepper aller stern'],
  'God, holy creator of all the stars', 'Creator of the Stars of Night', None),
 ('Nun freut euch, lieben Christen gmein', [r'n[uo][un]? fr[oö]u?we?t? [ejiu]u?w?,? leven christen',
   r'nun freut euch,? lieben christen', r'nu fr[oö]uwet juw,? leven christen',
   r'gi leven christen fr[oö]uwet juw', r'nun freudt euch,? lieben'],
  'Now rejoice, dear Christians together', 'Dear Christians, One and All, Rejoice', None),
 ('Gott hat das Evangelium', [r'godt hefft dat evangelium', r'gott hat das evangelium'],
  'God has given the gospel', None, None),
 ('Es wird schier der letzte Tag herkommen', [r'idt wert schir de leste dach', r'es wird schier der letzte'],
  'The last day will soon be coming', None, None),
 ('Christus, seine Zukunft ist vorhanden', [r'christus tokumpst is vorhanden'],
  "Christ's coming is at hand", None, None),
 ('Herr Christ, der einig Gotts Sohn', [r'herr christ,? d[ue].*einige? ga?de?s s[oö]n',
   r'her christ der einig gottes sohn', r'herr christ,? der einig'],
  'Lord Christ, the only Son of God', 'The Only Son from Heaven', None),
 ('Herr Jesu Christ, wahr Mensch und Gott', [r'herr jesu christ war mensch und gott'],
  'Lord Jesus Christ, true man and God', 'Lord Jesus Christ, True Man and God', None),

 # ---- Christmas / Epiphany ----
 ('Gelobet seist du, Jesu Christ', [r'gelo?a?ve?[bt]e?t? s[ei]i?s?tu,? jesu?s? christ'],
  'Praised be thou, Jesus Christ', 'All Praise to Thee, Eternal Lord',
  ['O Jesus Christ, All Praise to Thee', 'All Praise to Thee, Eternal Lord']),
 ('Ein Kindelein so löbelich', [r'ein kindelein so l[oöa]a?ve?belick', r'ein kindelein so l[oö]belich'],
  'A little child so praiseworthy', None, None),
 ('Der Tag, der ist so freudenreich', [r'de[rn]? [dt]ach?,? de[ri]? is[t]? so fr[oöe]u?we?de?n?reich',
   r'der tag,? der ist so fre[uy]de?n?\s?reich'],
  'The day that is so full of joy', 'Hail This Joyous Day',
  ['Hail This Joyous Day', 'O Day Full of Grace', 'This Day So Rich in Joy']),
 ('Vom Himmel hoch da komm ich her', [r'va?o[nm] h[ei]m+el hoch'],
  'From heaven high I come here', 'From Heaven Above to Earth I Come', None),
 ('Vom Himmel kam der Engel Schar', [r'va?o[nm] h[ei]m+el (kam|quam) der engel'],
  'From heaven came the host of angels', 'To Shepherds as They Watched by Night',
  ['From Heaven Came the Angel Host', 'To Shepherds as They Watched by Night']),
 ('Christum wir sollen loben schon', [r'christum wi.? sch?[oö]?l+e?n? l[oa]ve?b?e?n? schon',
   r'christum wir sollen'],
  'Christ we should indeed praise', 'Now Praise We Christ, the Holy One', None),
 ('In dulci jubilo', [r'in dulci [ij]ubilo'],
  'In sweet rejoicing', 'Good Christian Men, Rejoice',
  ['Good Christian Men, Rejoice', 'In Dulci Jubilo']),
 ('Ein Kind geborn zu Bethlehem', [r'ein kind gebor[nt]? zue? b?e?[tl]'],
  'A child born in Bethlehem', 'A Child Is Born in Bethlehem', None),
 ('Die Hirten auf dem Felde waren', [r'de herden up dem felde weren'],
  'The shepherds were in the field', None, None),
 ('Was fürchtst du, Feind Herodes, sehr', [r'wat fr[uü]chtestu viend herodes'],
  'Why dost thou fear so, foe Herod', 'Why, Herod, Unrelenting Foe', None),
 ('Danksagen wir alle Gott', [r'dan[ck]+h? sagen wir( alle)?', r'dank sagen wir alle'],
  'Let us all give thanks to God', 'We All Give Thanks to God', None),

 # ---- Purification / Simeon ----
 ('Mit Fried und Freud ich fahr dahin', [r'mit f[ri]+e?de?n?t? unn?de? fr[oöeu]u?w?de', r'mit frid[t]? und freud'],
  'With peace and joy I depart', 'In Peace and Joy I Now Depart', None),
 ('Herr, nun lässest du deinen Diener', [r'herre? nu l[eä]s+e?s?tu d[ie]ne?[nr]', r'herr,? nun lessestu deinen'],
  'Lord, now lettest thou thy servant', 'Lord, Now Lettest Thou Thy Servant Depart', None),
 ('Mein Seel erhebt den Herren', [r'm[ei]i?ne? se+le? erhe[vb]e?t den herren', r'mein seel erhebt'],
  'My soul magnifies the Lord', 'My Soul Now Magnifies the Lord', None),
 ('Gelobet sei der Herr, der Gott Israel', [r'gelavet si de herre,? de godt israel', r'gebenedeit sey gott der'],
  'Blessed be the Lord, the God of Israel', 'Blessed Be the Lord, the God of Israel', None),

 # ---- Catechism ----
 ('Dies sind die heilgen zehn Gebot', [r'd[ei][sßt]+ s[ei][ni]+d? die hei?l+i?ge?n? zehen?',
   r'dit sint de hiligen tein gebot'],
  'These are the holy ten commandments', 'These Are the Holy Ten Commands', None),
 ('Mensch, willst du leben seliglich', [r'mi?ne?sche?,? wi?l+e?n?tu? leve?n? sel[ie]ch?lick',
   r'mensch,? wiltu leben selig'],
  'Man, wouldst thou live blessedly', 'Man, Wouldst Thou Live All Blissfully', None),
 ('Wir glauben all an einen Gott', [r'w[ir]+ gel[oö]ve?n? alle?', r'wir glauben all?e?( an einen gott)?'],
  'We all believe in one God', 'We All Believe in One True God', None),
 ('Ich glaub an Gott', [r'ich glaub (an|in) gott'],
  'I believe in God', 'I Believe in God (Credo)', None),
 ('Vater unser im Himmelreich', [r'va[dt]e?r unse?r? im h[ei]m+e?l?reich', r'vater unser im himel'],
  'Our Father in the kingdom of heaven', 'Our Father, Thou in Heaven Above', None),
 ('Christ, unser Herr, zum Jordan kam', [r'christ,? unse?e?r? herre?e? (zum|tom) [ij]ordan'],
  'Christ our Lord came to the Jordan', 'To Jordan Came the Christ, Our Lord', None),
 ('Gott sei gelobet und gebenedeiet', [r'gott se[iy] gelobet', r'godt si gelovet'],
  'God be praised and blessed', 'O Lord, We Praise Thee', None),

 # ---- Psalm hymns ----
 ('Es ist das Heil uns kommen her', [r'[ei][sd]t? i[st]+ dat? he[ai]l uns [ck][oa]m+e?n'],
  'Salvation has come to us', 'Salvation unto Us Has Come', None),
 ('Durch Adams Fall ist ganz verderbt', [r'd[ou][rc]+h adams [vf]all? is[t]? ganz'],
  "Through Adam's fall all is wholly corrupted", 'All Mankind Fell in Adam’s Fall', None),
 ('Aus tiefer Not schrei ich zu dir', [r'au[sß] t?d?ie?e?[fp]e?r no[th]+', r'ut deper not'],
  'Out of deep distress I cry to thee', 'From Depths of Woe I Cry to Thee',
  ['From Depths of Woe I Cry to Thee', 'Out of the Depths I Cry to Thee']),
 ('Erbarm dich mein, o Herre Gott', [r'erbarm[e]? d[ic]+h?[i]? m[ei]i?ne?r?,? o herre? go[dt]+'],
  'Have mercy on me, O Lord God', 'Have Mercy on Me, O Lord God', None),
 ('O Herre Gott, begnade mich', [r'o herre? go[dt]+,? begnade m[ic]+h?'],
  'O Lord God, show me grace', None, None),
 ('Ach Gott, vom Himmel sieh darein', [r'ach go[dt]+,? va?o[mn] h[ei]m+el se+h?e? da'],
  'O God, look down from heaven', 'O Lord, Look Down from Heaven, Behold', None),
 ('Es spricht der Unweisen Mund wohl', [r'[ei][sd]t? spr[ie]ckt? der unw[ei]i?se?n? mund'],
  'The mouth of the unwise says indeed', 'The Mouth of Fools Doth God Confess', None),
 ('Es wolle Gott uns gnädig sein', [r'[ei][sd]t? wol+[dte]+ uns go[dt]+ gne?[ad]ich?g? s[ei]i?n'],
  'May God be gracious to us', 'May God Bestow on Us His Grace', None),
 ('An Wasserflüssen Babylon', [r'an wa[st]+er\s?fl[uü][st]+e?n? bab[iy]lo[nm]', r'am waterflete babylon'],
  'By the waters of Babylon', 'By the Waters of Babylon', None),
 ('Nun lob, mein Seel, den Herren', [r'nu[n]? l[oa]v?be?e? m[ei]i?ne? se+le?n? de[nr]? herren',
   r'nun lob mein seel den herren'],
  'Now praise the Lord, my soul', 'My Soul, Now Praise Thy Maker', None),
 ('Wohl dem, der in Gottes Furcht steht', [r'wo[ll]+ de[mn],? de[r]? i[nm] ga?o[dt]+e?s f[uü]r?chte?n?'],
  'Blessed is he who stands in the fear of God', 'Blessed Are They Who Fear the Lord', None),
 ('Es sind doch selig alle, die', [r'[ei][sd]t? s[ei][ni]+d? doch se+l[ie]ch?g? alle'],
  'Blessed indeed are all those who', 'Blessed Are They Who Walk in the Way', None),
 ('Wo Gott der Herr nicht bei uns hält', [r'wo go[dt]+ de[rn]? herre? nicht b[ei]i? uns h[oöa]l[dt]+',
   r'wo gott,? der herr,? nit bey uns helt', r'wo godt de herre bi uns h[oö]lt'],
  'If God the Lord does not stand by us', 'If God Had Not Been on Our Side',
  ['If God Had Not Been on Our Side', 'If God Were Not Upon Our Side']),
 ('Wär Gott nicht mit uns diese Zeit', [r'we?[aä]?re? go[dt]+ nicht mit uns d[ie]se?', r'wer gott nicht mit uns'],
  'Were God not with us at this time', 'Were God Not with Us at This Time', None),
 ('Wo Gott zum Haus nicht gibt sein Gunst', [r'wo go[dt]+ z?t?u[mn] hau?[sß]e? nicht'],
  'If God does not give his favour to the house', 'Unless the Lord Builds Up the House', None),
 ('Vergebens ist all Müh und Kost', [r'vorgeves is alle m[oö][ie]e?'],
  'In vain is all toil and cost', None, None),
 ('Der Herr ist mein getreuer Hirt', [r'de[rn]? herre? ist mein getreuer h[ie]?r?[dt]+'],
  'The Lord is my faithful shepherd', 'The Lord’s My Shepherd, Faithful, True', None),
 ('Herr, wie lang willst du vergessen mein', [r'herr,? wie lan+g wilt vergessen', r'herr wie lang wilt vergessen'],
  'Lord, how long wilt thou forget me', None, None),
 ('Ach Gott, wie lang vergissest mein', [r'ach gott,? wie lan+g'],
  'O God, how long wilt thou forget me', None, None),
 ('Hilf Gott, wie geht das immer zu', [r'he?[il]+[pf]e? go[dt]+,? wo geit dat', r'hilf gott,? wie geht das'],
  'Help God, how does this ever go on', None, None),
 ('Hilf Gott, wie ist der Menschen Not', [r'he?[il]+[pf]e? go[dt]+,? wo is der minschen not'],
  "Help God, how great is mankind's distress", None, None),
 ('Nun welche hie ihr Hoffnung gar', [r'nu[n]? welche hie i?[hr]+ hoffnung'],
  'Now those who here their hope', None, None),
 ('Allein zu dir, Herr Jesu Christ', [r'all?e[ei]?ne? [zt][uo] d[ir]+,? herre?e? jesu'],
  'In thee alone, Lord Jesus Christ', 'In Thee Alone, O Christ, My Lord', None),
 ('Ich ruf zu dir, Herr Jesu Christ', [r'ic?k?h? r[ou][fp]e? [zt][uo] d[ir]+,? herre?e?,? jesu'],
  'I call to thee, Lord Jesus Christ', 'I Call to Thee, Lord Jesus Christ', None),
 ('Herr, wer wird wohnen in deiner Hütte', [r'herre?,? wo?e?[lr]+ we?[ir]+t? wa?o[hn]+e?n', r'o herr,? wer wird'],
  'Lord, who shall dwell in thy tent', None, None),
 ('O Herre Gott, dein göttlich Wort', [r'o herre? go[dt]+,? d[ie]n? g[oö][dt]+l'],
  'O Lord God, thy divine word', 'O Lord God, Thy Divine Word', None),

 # ---- Lent / Passion ----
 ('Christe, der du bist Tag und Licht', [r'christe?,? de?[ru]? du bist [dt]a[cg]+'],
  'Christ, thou who art day and light', 'O Christ, Who Art the Light and Day', None),
 ('O Mensch, bewein dein Sünde groß', [r'o? ?m[ei]i?n?sche?,? be?we[ie]?n+e? d[ie]ne? s[uü]nde'],
  'O man, bewail thy great sin', 'O Man, Bewail Thy Grievous Sin', None),
 ('Da Jesus an dem Kreuze stund', [r'd[oa] jesus an dem cr[uü]ze'],
  'When Jesus on the cross stood', 'When Jesus on the Cross Was Bound', None),
 ('O wir armen Sünder', [r'och wi armen s[uü]nders'],
  'O we poor sinners', None, None),
 ('Hilf Gott, dass mir gelinge', [r'help godt,? mi mach gelingen'],
  'Help, God, that I may succeed', None, None),
 ('O Lamm Gottes, unschuldig', [r'o? ?lamb? go[dt]+e?s,? unsch'],
  'O Lamb of God, innocent', 'Lamb of God, Pure and Holy', None),
 ('Wir danken dir, Herr Jesu Christ', [r'wir danken dir,? l?i?eb?e?r?e? herr'],
  'We thank thee, Lord Jesus Christ', 'We Thank Thee, Jesus, Dearest Friend', None),
 ('Gott dem Vater sei Lob', [r'godt dem vader si loff'],
  'To God the Father be praise', None, None),

 # ---- Easter ----
 ('Christ lag in Todesbanden', [r'christ la[gc]h? in [dt]o[dt]+e?s'],
  "Christ lay in death's bonds", "Christ Jesus Lay in Death's Strong Bands", None),
 ('Christ ist erstanden', [r'christ is[t]? e?[ru]?[fp]?ge?e?stan+de?n'],
  'Christ is risen', 'Christ Is Arisen', None),
 ('Erstanden ist der heilige Christ', [r'erstanden is de hilige christ'],
  'The holy Christ is risen', None, None),
 ('Jesus Christus, unser Heiland', [r'jesus christus,? [uv]nse?e?r? he?i?la?nn?d', r'jesus christus unser heil'],
  'Jesus Christ, our Savior', 'Jesus Christ, Our Blessed Savior', None),
 ('Jesus Christus, wahrer Gottes Sohn', [r'jesus christus,? ware gades s[oö]n'],
  "Jesus Christ, true Son of God", None, None),
 ('Also heilig ist der Tag', [r'also hei?l+ig \[?ist\]? d[ie]se?r? [dt]ag'],
  'Thus holy is this day', None, None),
 ('Jesus ist ein süßer Nam', [r'jesus ist ein s[uü]e?[sß]er nam'],
  'Jesus is a sweet name', None, None),
 ('Was kann uns kommen an für Not', [r'wat kan uns kamen an vor not'],
  'What distress can come upon us', None, None),
 ('Kommt her zu mir, spricht Gottes Sohn', [r'kame?e?t her [zt][uo] mi,? spre?ckt ga?de?s s[oö]n'],
  "Come here to me, says God's Son", 'Come unto Me, Ye Weary', None),

 # ---- Ascension / Pentecost / Trinity ----
 ('Christ fuhr gen Himmel', [r'christu?s? (fur|vohr|fuhr) [zg]?t?e?[no]n? h[ei]m+el'],
  'Christ went up to heaven', 'Christ Went Up to Heaven', None),
 ('Auf diesen Tag so denken wir', [r'auf? d[ie]se?n? [dt]ag,? so den[ck]+h?e?n wir'],
  'Upon this day we call to mind', None, None),
 ('Komm, Heiliger Geist, Herre Gott', [r'k[ou]m+,? he?[iy]l+i?ge?r? geist(?!.*sch[oö]pfer)'],
  'Come, Holy Spirit, Lord God', 'Come, Holy Ghost, God and Lord', None),
 ('Nun bitten wir den Heiligen Geist', [r'nu[n]? b[ie]?[dt]+e?n wir?( den)?( he?[iy]l+i?ge?n? geist)?$',
   r'nu bidden wi den hiligen geist'],
  'Now we pray to the Holy Spirit', 'We Now Implore God the Holy Ghost', None),
 ('Komm, Gott Schöpfer, Heiliger Geist', [r'k[ou]m+,? go[dt]+,? sch[oö]pfer'],
  'Come, God Creator, Holy Spirit', 'Come, Holy Ghost, Creator Blest', None),
 ('Der Heilige Geist, der wohn uns bei', [r'de hilige geist,? de wane uns bi'],
  'The Holy Spirit, may he dwell with us', None, None),
 ('Gott der Vater wohn uns bei', [r'go[dt]+ de[rn]? va[dt]er,? ?(wo?[hn]+e?|wane) uns b[ei]i?'],
  'God the Father, dwell with us', 'God the Father, Be Our Stay', None),
 ('Der du bist drei in Einigkeit', [r'de[rn]? du bist dre[iy]? in e[ii]?n[ie]?[ck]+h?e?it'],
  'Thou who art three in unity', 'O Thou, Who Art Three in One', None),
 ('Das Athanasianische Symbolum, deutsch', [r'symbolum athanasii'],
  'The Athanasian Creed, in German', 'Athanasian Creed', None),
 ('Herr Gott, dich loben wir', [r'herr go[dt]+,? dich loben wir', r'd[uü]dische te deum'],
  'Lord God, we praise thee', 'We Praise Thee, O God (Te Deum)', None),
 ('Nun hört zu, ihr Christenleute', [r'nu h[oö]ret to,? gi christen l[uü]de'],
  'Now hear, ye Christian people', None, None),
 ('Nun ist die angenehme Zeit', [r'nu is de angeneme tidt'],
  'Now is the acceptable time', None, None),
 ('Jerusalem, des Glaubens Stadt', [r'h?[ij]erusalem,? des gelovens stadt'],
  'Jerusalem, city of faith', None, None),
 ('Jesaja, dem Propheten, das geschah', [r'jesaia,? dem propheten'],
  'To Isaiah the prophet it happened', 'Isaiah, Mighty Seer, in Days of Old', None),
 ('Ein feste Burg ist unser Gott', [r'ein[e]? [fv]e?a?ste?e? bu?o?r[gck]+h?'],
  'A firm fortress is our God', 'A Mighty Fortress Is Our God', None),
 ('Erhalt uns, Herr, bei deinem Wort', [r'erhalt un+s,? herr'],
  'Keep us, Lord, in thy word', 'Lord, Keep Us Steadfast in Thy Word', None),
 ('Verleih uns Frieden gnädiglich', [r'verle?i?e?ihe? uns fr[ie]+de?n'],
  'Grant us peace graciously', 'Grant Peace, We Pray, in Mercy, Lord', None),
 ('Gib Fried zu unser Zeit', [r'gib fr[ie]+d[t]? zu unn?ser zeit', r'da pacem domine'],
  'Give peace in our time', 'Give Peace in Our Time, O Lord', None),
 ('Im Frieden dein', [r'im fr[ie]+de?n dein'],
  'In thy peace', 'In Thy Peace, O Lord', None),
 ('Nun lasst uns den Leib begraben', [r'nu[n]? la[st]+ un[sß] den l[ei]i?[fb]+ begraben'],
  'Now let us bury the body', 'Now Lay We Calmly in the Grave', None),
 ('Wenn mein Stündlein vorhanden ist', [r'wenn mein stundlein vorhanden'],
  'When my hour is at hand', 'When My Last Hour Is Close at Hand', None),
 ('Capitan, Herre Gott Vater mein', [r'capitan herre godt vader'],
  'Captain, Lord God my Father', None, None),
 ('Gnade mir, Herr, ewiger Gott', [r'gnade mi herr+e? ewige godt'],
  'Show me grace, Lord, eternal God', None, None),
 ('Ich danke dem Herrn von ganzem Herzen', [r'ick danke dem herren van ganzem'],
  'I thank the Lord with all my heart', None, None),
 ('Ich danke dir, lieber Herre', [r'ick danke di,? leve herre'],
  'I thank thee, dear Lord', None, None),
 ('O Mensch, willst du gedenken', [r'o minsche wil gedenken'],
  'O man, wilt thou consider', None, None),
 ('Ich glaube an Gott (Credo)', [r'^ich glaub an gott$'],
  'I believe in God', 'I Believe in God', None),
 ('Die deutsche Litanei', [r'd[uü]dische letanie', r'^litania[m]?$'],
  'The German Litany', 'The Litany', None),
 ('Herr Gott, dein Treue', [r'herr gott,? dein treue'],
  'Lord God, thy faithfulness', None, None),
 ('Jetzund so bitten wir', [r'jetzund,? so bitten wir'],
  'Now therefore we pray', None, None),
 ('Christum, unsern Heiland', [r'christum,? unn?se?rn he[iy]la'],
  'Christ, our Savior', 'Jesus Christ, Our Blessed Savior', None),
 ('Gott durch deine Güte', [r'gott durch deine g[uü]te'],
  'God, through thy goodness', 'God, Through Thy Goodness', None),
 ('Sei gegrüßt, Jesu, du einiger Trost', [r'sei gegr[uü][sß]t jesu'],
  'Be greeted, Jesus, thou only comfort', None, None),
 ('Ehre sei dir, Christe, der du leidest Not', [r'ehre sei dir christe'],
  'Glory be to thee, Christ, who sufferest distress', None, None),
 ('Das Kyrie', [r'^das (erst|zweyt|dridt)e? kyrie$', r'kyrie paschale'],
  'The Kyrie', 'Kyrie eleison', None),
]

LATIN_EN = {
 'Veni redemptor gentium': ('Come, redeemer of the nations', 'Savior of the Nations, Come'),
 'Conditor alme siderum': ('Kindly creator of the stars', 'Creator of the Stars of Night'),
 'A solis ortus cardine': ('From the hinge of the rising sun', 'From East to West, From Shore to Shore'),
 'Hostis Herodes impie': ('Herod, thou impious foe', 'Why, Herod, Unrelenting Foe'),
 'Corde natus ex parentis': (" Born of the Father's heart", 'Of the Father’s Love Begotten'),
 'Christe qui lux es et dies': ('Christ, who art the light and the day', 'O Christ, Who Art the Light and Day'),
 'Dies absoluti praetereunt': ('The days of freedom pass away', None),
 'Audi benigne conditor': ('Hear, kindly creator', 'O Kind Creator, Bow Thine Ear'),
 'Vexilla regis prodeunt': ('The banners of the King go forth', 'The Royal Banners Forward Go'),
 'Rex Christe factor omnium': ('King Christ, maker of all things', 'O Christ, Our King, Creator, Lord'),
 'Crux fidelis': ('Faithful cross', 'Faithful Cross, Above All Other'),
 'Ad coenam agni providi': ("Provided for the Lamb's supper", 'At the Lamb’s High Feast We Sing'),
 'Vita sanctorum decus angelorum': ('Life of the saints, glory of the angels', None),
 'Festum nunc celebre': ('Now the famed festival', None),
 'Veni creator Spiritus': ('Come, creator Spirit', 'Come, Holy Ghost, Creator Blest'),
 'O lux beata Trinitas': ('O light, blessed Trinity', 'O Trinity, Most Blessed Light'),
 'Veni sancte Spiritus': ('Come, Holy Spirit', 'Come, Holy Ghost'),
 'Pange lingua gloriosi': ('Sing, my tongue, of the glorious', 'Sing, My Tongue, the Glorious Battle'),
 'Iam maesta quiesce querela': ('Now cease, sorrowful lament', None),
 'Te Deum laudamus': ('We praise thee, O God', 'We Praise Thee, O God'),
 'Gloria laus et honor': ('Glory, praise and honour', 'All Glory, Laud and Honor'),
 'Victimae paschali laudes': ('Praises to the paschal victim', 'Christians, to the Paschal Victim'),
 'Grates nunc omnes': ('Now let us all give thanks', 'We All Give Thanks to God'),
 'Vespertina oratio': ('Evening prayer', None),
 'Iesu nostra redemptio': ('Jesus, our redemption', 'O Jesus, Our Redemption'),
 'Aurea luce': ('With golden light', None),
 'Optatus votis omnium': ('Longed for by the prayers of all', None),
 'Summae Trinitati': ('To the highest Trinity', None),
 'Beata nobis gaudia': ('Blessed joys for us', 'Rejoice! The Year Upon Its Way'),
 'Chorus novae Ierusalem': ('Choir of the new Jerusalem', 'Ye Choirs of New Jerusalem'),
}

L += [
 ('Mitten wir im Leben sind', [r'mi[dt]+e?n wi[r]? im le[bv]e?n?de?n? s[ei]i?n[dt]?'],
  'In the midst of life we are', 'In the Very Midst of Life', None),
 ('Es war einmal ein reicher Mann', [r'i?e?dt? was ein\s?mal ein r[ie]ke?r? man'],
  'There was once a rich man', None, None),
 ('Mag ich Unglück nicht widerstahn', [r'mach ick ungl[uü]ck nicht wedderstan'],
  'If I cannot withstand misfortune', None, None),
 ('Da Israel aus Ägypten zog', [r'da israel au[sß]+ egipten'],
  'When Israel went out of Egypt', 'When Israel Out of Egypt Came', None),
 ('Der Törichte spricht', [r'der th?[oö]rricht spricht', r'^der thorricht'],
  'The foolish man says', 'The Mouth of Fools Doth God Confess', None),
 ('Herr Gott, der du erforschest mich', [r'herr gott,? der du erforschest'],
  'Lord God, thou who searchest me', None, None),
 ('All Ehr und Lob soll Gottes sein', [r'all e[hr]+,? und lob sol gottes'],
  'All honour and praise shall be God’s', 'All Glory Be to God on High', None),
 ('All unsre Schuld vergib uns, Herr', [r'all unse schuld vorgiff uns'],
  'Forgive us all our guilt, Lord', None, None),
 ('Von allen Menschen abgewandt', [r'van allen minschen affgewandt'],
  'Turned away from all men', None, None),
 ('Der Heiligen Leben', [r'der hiligen levendt'],
  'The life of the saints', None, None),
 ('Veni Sancte Spiritus, deutsch', [r'veni san[ct]+e,? d[uü]disch'],
  'Veni Sancte Spiritus, in German', 'Come, Holy Ghost', None),
 # rubrics: cross-references in the source rather than named incipits
 ('[Die Weihnachtsgesänge]', [r'de winachten gesenge'],
  'the Christmas hymns [as a group]', None, None),
 ('[Die Ostergesänge]', [r'hir to de paschen gesenge'],
  'the Easter hymns [as a group]', None, None),
 ('[Passionspsalmen]', [r'^passion psalme$'],
  'passion psalms [as a group]', None, None),
]

L += [
 ('Mit Fried und Freud ich fahr dahin', [r'mit fr[ie]+d[t]? unn?d[t]? fre[uy]d[t]?']
  , 'With peace and joy I depart', 'In Peace and Joy I Now Depart', None),
 ('Mensch, willst du leben seliglich', [r'm[ei]n?sche?,? wil+e?n?t?u? le[bv]e?n?( sel)?'],
  'Man, wouldst thou live blessedly', 'Man, Wouldst Thou Live All Blissfully', None),
 ('Herr, wer wird wohnen in deiner Hütte', [r'herre?,? wo?e?l+ we?[rd]+ wa[nh]e?n'],
  'Lord, who shall dwell in thy tent', None, None),
 ('Wär Gott nicht mit uns diese Zeit', [r'we?[aä]?re?r? go[dt]+ ni[ct]+h?t? mit uns'],
  'Were God not with us at this time', 'Were God Not with Us at This Time', None),
 ('Aus tiefer Not schrei ich zu dir', [r'au[sß]+ d?t?ife?r not'],
  'Out of deep distress I cry to thee', 'From Depths of Woe I Cry to Thee', None),
 ('Herr, nun lässest du deinen Diener', [r'herre?,? nun le[sß]+e?stu'],
  'Lord, now lettest thou thy servant', 'Lord, Now Lettest Thou Thy Servant Depart', None),
 ('Gelobet sei der Herr, der Gott Israel', [r'gelobet se[yi] der herr'],
  'Blessed be the Lord, the God of Israel', 'Blessed Be the Lord, the God of Israel', None),
 ('Das Kyrie', [r'kyrie pasch', r'kyrie$', r'unnd drit kyrie'],
  'The Kyrie', 'Kyrie eleison', None),
 ('Komm, Heiliger Geist, Herre Gott', [r'^ha?e?il+ige?r? ga?e?ist'],
  'Come, Holy Spirit, Lord God', 'Come, Holy Ghost, God and Lord', None),
 ('Wo Gott zum Haus nicht gibt sein Gunst', [r'wo das hau[sß]+ ni[ct]+h?t? baut'],
  'If the Lord does not build the house', 'Unless the Lord Builds Up the House', None),
]

LATIN_EN['Puer natus in Bethlehem'] = ('A boy is born in Bethlehem', 'A Child Is Born in Bethlehem')

L += [
 ('Nun freut euch, lieben Christen gmein', [r'gi leve?n christen fr[oö]u?w?t? [ji]uw'],
  'Now rejoice, dear Christians together', 'Dear Christians, One and All, Rejoice', None),
 ('Ach Gott, vom Himmel sieh darein', [r'ach gott,? v[oa]n himel'],
  'O God, look down from heaven', 'O Lord, Look Down from Heaven, Behold', None),
 ('O Lamm Gottes, unschuldig', [r'^0? ?lamb? gottes'],
  'O Lamb of God, innocent', 'Lamb of God, Pure and Holy', None),
 ('Gelobet seist du, Jesu Christ', [r'^gelobet se?i?stu$', r'^jesu christ$'],
  'Praised be thou, Jesus Christ', 'All Praise to Thee, Eternal Lord', None),
 ('Nun ihr Völker all (Ps. 47, Lobwasser)', [r'nun ihr v[oö]lker all'],
  'Now all ye peoples', None, None),
 ('Allein zu dir, Herr Jesu Christ', [r'^herr jesu crist$'],
  'In thee alone, Lord Jesus Christ', 'In Thee Alone, O Christ, My Lord', None),
]

# ---- Hymns of the hymnal and compilation sources (Liliencron, Ludecus, the Hymn of the Day
# table, Krusemark) that the Sehling orders do not name.  Without these entries their titles
# either stayed unresolved, so that the German and English citations of one hymn were counted
# as different hymns, or were fuzzy-matched to the wrong hymn (Eber's "Herr Gott, dich loben
# alle wir" to the German Te Deum).  common_english is a received English title where one
# exists; None otherwise.
L += [
 ('Herr Gott, dich loben alle wir', [r'dich loben alle wir'],
  'Lord God, we all praise thee', 'Lord God, We All to Thee Give Praise', None),
 ('Als Jesus Christus, Gottes Sohn', [r'^als jesus christus,? gottes so'],
  'When Jesus Christ, the Son of God', None, None),
 ('Mag ich dem Tod nicht widerstahn', [r'mag ich dem tod nicht'],
  'Though I cannot withstand death', None, None),
 ('Wie schön leuchtet der Morgenstern', [r'wie scho?e?n leuchtet'],
  'How beautifully shines the morning star', 'How Lovely Shines the Morning Star', None),
 ('Christus, der uns selig macht', [r'christus,? der [uv]ns selig'],
  'Christ, who makes us blessed', None, None),
 ('Warum betrübst du dich, mein Herz', [r'waru[m]?b? betr\w*bs\w*( du)? dich'],
  'Why art thou troubled, my heart', 'Why Art Thou Thus Cast Down, My Heart', None),
 ('Es ist gewisslich an der Zeit', [r'es ist gewi[fs]+lich'],
  'It is surely time', 'The Day Is Surely Drawing Near', None),
 ('Wenn wir in höchsten Nöten sein', [r'wenn wir in ho?e?c?h?sten no'],
  'When we are in the greatest distress', 'When in the Hour of Utmost Need', None),
 ('Christe, du bist der helle Tag', [r'christe,? du bist der helle'],
  'Christ, thou art the bright day', None, None),
 ('Von Adam her so lange Zeit', [r'von adam her'],
  "From Adam's time so long", None, None),
 ('Ach Gott, thu dich erbarmen', [r'ach gott,? th?u dich erbarm'],
  'Ah God, have mercy', None, None),
 ('Nun freut euch, Gottes Kinder, all', [r'nu[n]? fre[uw]+t euch,? gottes kinder'],
  'Now rejoice, all ye children of God', None, None),
 ('Weltlich Ehr und zeitlich Gut', [r'weltlich ehr'],
  'Worldly honour and temporal goods', None, None),
 ('Helft mir Gotts Güte preisen', [r'helft mir gott'],
  "Help me praise God's goodness", None, None),
 ('Allein Gott in der Höh sei Ehr', [r'allein gott in der ho'],
  'To God alone on high be glory', 'All Glory Be to God on High', None),
 ('Ihr lieben Christen, freut euch nun', [r'^[ij]h?r lieben christen,? fre'],
  'Ye dear Christians, rejoice now', None, None),
 ('Heut triumphieret Gottes Sohn', [r'heut triumph'],
  "Today God's Son triumphs", 'Today in Triumph Christ Arose', None),
 ('Ach, lieben Christen, seid getrost', [r'ach,? lieben,? christen,? seid'],
  'Ah, dear Christians, be comforted', None, None),
 ('Gottes Sohn ist kommen', [r'gottes so[hn]+ ist kom'],
  "God's Son has come", 'Once He Came in Blessing', None),
 ('Weil Maria schwanger ging', [r'weil maria schwanger'],
  'While Mary went with child', None, None),
 ('Das alte Jahr vergangen ist', [r'das alte jahr vergangen'],
  'The old year has passed', 'The Old Year Now Hath Passed Away', None),
 ('Lob sei dem allmächtigen Gott', [r'lob sei dem allm'],
  'Praise be to almighty God', None, None),
 ('Menschenkind, merk eben', [r'menschen ?kind,? mer[ck]+ eben'],
  'Child of man, mark well', None, None),
 ('Als Jesus geboren war', [r'als jesus geboren war'],
  'When Jesus was born', None, None),
 ('In dich hab ich gehoffet, Herr', [r'in dich hab ich gehoffet'],
  'In thee have I hoped, Lord', 'In Thee, Lord, Have I Put My Trust', None),
 ('Erschienen ist der herrlich Tag', [r'erschienen ist der herrlich'],
  'The glorious day has appeared', 'The Day Hath Dawned, the Day of Days', None),
 ('Von Gott will ich nicht lassen', [r'von gott will ich nicht'],
  'From God I will not part', 'From God Can Naught Move Me', None),
 ('Lobsinget Gott und schweiget nicht', [r'lobsinget gott'],
  'Sing praise to God and be not silent', None, None),
 ('Jesu, nun sei gepreiset', [r'jesu,? nun sei gepreiset'],
  'Jesus, now be praised', 'Now Greet the Swiftly Changing Year', None),
 ('Die Propheten habn geprophezeit', [r'die propheten hab'],
  'The prophets have prophesied', None, None),
 ('O Licht, heilige Dreifaltigkeit', [r'o li\S*ht,? heilige dre'],
  'O light, holy Trinity', None, None),
 ('Als Adam im Paradiese', [r'als adam i[mn] paradi'],
  'When Adam was in Paradise', None, None),
 ('Was mein Gott will, das gscheh allzeit', [r'was mein gott will'],
  'What my God wills, may that be done always', 'The Will of God Is Always Best', None),
 ('Auf meinen lieben Gott', [r'auf meinen lieben gott'],
  'In my dear God', 'In God, My Faithful God', None),
 ('Wie soll ich dich empfangen', [r'wie soll ich dich empfangen'],
  'How shall I receive thee', 'O Lord, How Shall I Meet You', None),
 ('Wir Christenleut habn jetzund Freud', [r'wir christenleut'],
  'We Christian people now have joy', 'We Christians May Rejoice Today', None),
 ('Lobt Gott, ihr Christen, allzugleich', [r'lobt gott,? ihr christen'],
  'Praise God, ye Christians, all together', 'Let All Together Praise Our God', None),
 ('Das neugeborne Kindelein', [r'das neu ?geborne?n? kindelein'],
  'The newborn little child', None, None),
 ('Fröhlich wolln wir Halleluja singen', [r'fro?h?lich wol+e?n? wir (hal|al)'],
  'Joyfully will we sing Hallelujah', None, None),
 ('Ich danke dem Herrn von ganzem Herzen', [r'ich dank dem herren'],
  'I thank the Lord with all my heart', None, None),
 ('Zweierlei bitt ich von dir', [r'zweierlei bitt'],
  'Two things I ask of thee', None, None),
 ('Ich hab mein Sach Gott heimgestellt', [r'ich hab mein sach gott'],
  'I have committed my cause to God', "I Leave All Things to God's Direction", None),
 ('O Gott, verleih mir deine Gnad', [r'o gott,? verleihe? mir deine'],
  'O God, grant me thy grace', None, None),
 ('Wohl dem Menschen, der wandelt nicht', [r'wo[h]?l dem menschen,? der wandelt'],
  'Blessed is the man who walks not', 'Blessed Is the Man Who Walketh Not', None),
 ('Herzlich lieb hab ich dich, o Herr', [r'herzlich lieb hab ich dich'],
  'Heartily I love thee, O Lord', 'Lord, Thee I Love with All My Heart', None),
 ('Ach Gott und Herr', [r'^ach gott und herr'],
  'Ah God and Lord', 'Alas, My God, My Sins Are Great', None),
 ('Herr Jesu Christ, du höchstes Gut', [r'herr jesu christ,? du h\S*chstes gut'],
  'Lord Jesus Christ, thou highest good', 'Lord Jesus Christ, Thou Highest Good', None),
 ('Herr Jesu Christ, ich schrei zu dir', [r'herr jesu christ,? ich schrei'],
  'Lord Jesus Christ, I cry to thee', None, None),
 ('Uns ist geborn ein Kindelein', [r'uns ist geborn ein kindelein'],
  'Unto us a little child is born', None, None),
 ('O Traurigkeit, o Herzeleid', [r'o traurigkeit'],
  'O sadness, O heartache', 'O Darkest Woe', None),
 ('So wahr ich leb, spricht Gott der Herr', [r'^so wah?r ich leb'],
  'As truly as I live, saith God the Lord', 'As Surely as I Live, God Said', None),
 ('Kehr um, kehr um, du junger Sohn', [r'^kehr (um|[uv]mb)'],
  'Turn back, turn back, thou young son', None, None),
 ('Sie ist mir lieb, die werte Magd', [r'sie ist mir lieb'],
  'She is dear to me, the worthy maid', "To Me She's Dear, the Worthy Maid", None),
 ('Gelobet sei der Herr, der Gott Israel', [r'deutsche benedictus'],
  'Blessed be the Lord, the God of Israel', 'Blessed Be the Lord, the God of Israel', None),
 ('Herr, wer wird wohnen in deiner Hütte', [r'^herr,? wer wird wohnen'],
  'Lord, who shall dwell in thy tent', None, None),
 ('Wir glauben all an einen Gott', [r'wir gl[ea]u?ben all an einen'],
  'We all believe in one God', 'We All Believe in One True God', None),
 ('Ach bleib bei uns, Herr Jesu Christ', [r'ach bleib bei uns'],
  'Abide with us, Lord Jesus Christ', 'Lord Jesus Christ, with Us Abide', None),
 # cited only by English title in the modern lists
 ('Such, wer da will, ein ander Ziel', [r'such,? wer da will'],
  'Seek, whoever will, another goal', 'Seek Where Ye May to Find a Way', None),
 ('Ein Lämmlein geht und trägt die Schuld', [r'ein la\S*mmlein geht'],
  'A little lamb goes and bears the guilt', 'A Lamb Goes Uncomplaining Forth', None),
 ('Wachet auf, ruft uns die Stimme', [r'wachet auf'],
  'Wake up, the voice calls us', 'Wake, Awake, for Night Is Flying', None),
 ('Jesu, meine Freude', [r'jesu,? meine freude'],
  'Jesus, my joy', 'Jesus, Priceless Treasure', None),
 ('Mir nach, spricht Christus, unser Held', [r'mir nach,? spricht christus'],
  'After me, says Christ, our hero', 'Come, Follow Me, the Savior Spake', None),
 ('Sei Lob und Ehr dem höchsten Gut', [r'sei lob und ehr dem ho'],
  'Praise and honour be to the highest good', 'All Praise to God, Who Reigns Above', None),
 ('Lasset uns mit Jesu ziehen', [r'lasset uns mit jesu'],
  'Let us go with Jesus', 'Let Us Ever Walk with Jesus', None),
 ('Was frag ich nach der Welt', [r'was frag ich nach der welt'],
  'What do I care for the world', 'What Is the World to Me', None),
 ('O Gott, du frommer Gott', [r'o gott,? du frommer gott'],
  'O God, thou faithful God', 'O God, Thou Faithful God', None),
 ('Valet will ich dir geben', [r'valet will ich'],
  'Farewell will I bid thee', 'Farewell I Gladly Bid Thee', None),
 ('Tröstet, tröstet meine Lieben', [r'tro\S*stet,? tro\S*stet'],
  'Comfort, comfort my beloved', 'Comfort, Comfort Ye My People', None),
 ('Fröhlich soll mein Herze springen', [r'fro\S*hlich soll mein herze'],
  'Joyfully shall my heart leap', 'All My Heart This Night Rejoices', None),
]
# Luther's Easter hymn must be tried before his Communion hymn of the same opening, whose
# pattern would otherwise take it.
L.insert(0, ('Jesus Christus, unser Heiland, der den Tod überwand',
             [r'jesus christus,? [uv]nse?r? heiland,? der den tod'],
             'Jesus Christ, our Saviour, who overcame death', None, None))

# ---- Matthew Carver's translations ----------------------------------------------------------
# For hymns with no received English title, the English title of Matthew Carver's translation:
# either in Walther's Hymnal (Concordia, 2012), which he translated ("WH n"), or on his blog
# Hymnoglypt, matthaeusglyptes.blogspot.com ("HG").  The titles are those Krusemark prints in
# Thompson's and the other columns of Hymns ABC (rows_krusemark_raw.json; his pp. 95-96 name
# Carver as the translator), matched to the German hymn by the Ludecus and Thompson entries
# for the same day.  canonical -> (English title, source)
CARVER = {
 'Ach, lieben Christen, seid getrost': ('Dear Christians, Put Away Your Fears', "Walther's Hymnal 353"),
 'Als Adam im Paradiese': ('When in Eden Adam Was', 'Hymnoglypt'),
 'Als Jesus Christus, Gottes Sohn': ('When Jesus Christ, the Son of God', 'Hymnoglypt'),
 'Also heilig ist der Tag': ('This Is Such a Holy Day', "Walther's Hymnal 96"),
 'Auf diesen Tag so denken wir': ('Today Our Lord Went Up on High', "Walther's Hymnal 118"),
 'Christe, du bist der helle Tag': ("Lord Christ, Thou Art the Heav'nly Light", "Walther's Hymnal 312"),
 'Christus, der uns selig macht': ('Christ, Who Saves Us by His Cross', 'Hymnoglypt'),
 'Das neugeborne Kindelein': ('The New-Born Child This Early Morn', "Walther's Hymnal 49"),
 'Die Propheten habn geprophezeit': ('The Prophets Prophesied of Old', 'Hymnoglypt'),
 'Ehre sei dir, Christe, der du leidest Not': ('Christ, to Thee Be Glory', 'Hymnoglypt'),
 'Es war einmal ein reicher Mann': ('There Was a Rich and Wealthy Man', 'Hymnoglypt'),
 'Es wird schier der letzte Tag herkommen': ('Lo, the Final Day Is Fast Approaching', 'Hymnoglypt'),
 'Fröhlich wolln wir Halleluja singen': ('"Alleluia" Sing We with Jubilation', 'Hymnoglypt'),
 'Gott hat das Evangelium': ('God Gave the Gospel That We May', "Walther's Hymnal 442"),
 'Helft mir Gotts Güte preisen': ('To God the Anthem Raising', "Walther's Hymnal 50"),
 'Herr Jesu Christ, ich schrei zu dir': ('Lord Jesus Christ, I Cry to Thee', 'Hymnoglypt'),
 'Hilf Gott, dass mir gelinge': ('Assist Me, Great Creator', 'Hymnoglypt'),
 'Hilf Gott, wie geht das immer zu': ('Oh, Help Us, God! Why Must It Be', 'Hymnoglypt'),
 'Hilf Gott, wie ist der Menschen Not': ("Oh, God, Man's Ruin Is So Broad and Grim", 'Hymnoglypt'),
 'Ich danke dir, lieber Herre': ('I Thank Thee, Lord, for Keeping', 'Hymnoglypt'),
 'Ihr lieben Christen, freut euch nun': ('Rejoice, Rejoice, Ye Christians Dear', 'Hymnoglypt'),
 'Jesus Christus, unser Heiland, der den Tod überwand':
     ('Jesus Christ, Our Savior and King', "Walther's Hymnal 110"),
 'Jesus Christus, wahrer Gottes Sohn': ('Christ, the Very Son of God', 'Hymnoglypt'),
 'Kehr um, kehr um, du junger Sohn': ('Return, Return, Thou Youthful Son', 'Hymnoglypt'),
 'Lob sei dem allmächtigen Gott': ('All Praise to God the Highest Be', 'Hymnoglypt'),
 'Lobsinget Gott und schweiget nicht': ('Sing Praise to God and Be Not Mute', 'Hymnoglypt'),
 'Mag ich Unglück nicht widerstahn': ('May I My Fate No More Withstand', 'Hymnoglypt'),
 'Menschenkind, merk eben': ('Mark, O Mortal, Duly', "Walther's Hymnal 32"),
 'Nun freut euch, Gottes Kinder, all': ('O Children of Your God, Rejoice', "Walther's Hymnal 122"),
 'Nun hört zu, ihr Christenleute': ('O Christian Men, Now Lend an Ear', 'Hymnoglypt'),
 'O Gott, verleih mir deine Gnad': ('O God, on Me Thy Grace Bestow', 'Hymnoglypt'),
 'O wir armen Sünder': ('Oh, What Wretched Sinners', 'Hymnoglypt'),
 'Vergebens ist all Müh und Kost': ('In Vain Is All Thy Toil and Pain', 'Hymnoglypt'),
 'Von Adam her so lange Zeit': ("Since Adam's Age, So Long Have We", "Walther's Hymnal 43"),
 'Von allen Menschen abgewandt': ('By All Mankind Cast Off, I Groan', 'Hymnoglypt'),
 'Was kann uns kommen an für Not': ('What Shall We Want Where Christ Our Head', 'Hymnoglypt'),
}
for _i, (_c, _p, _lit, _com, _alt) in enumerate(L):
    if _com is None and _c in CARVER:
        L[_i] = (_c, _p, _lit, CARVER[_c][0], _alt)
