"""Family A -- Brenz's bidding prayer (Schwäbisch Hall 1526) and its descendants.

Each petition is a bidding addressed to the people ("Lasset uns bitten für ...")
followed by a collect addressed to God.  Brenz's collects for the Church, for
the magistrates and for the afflicted are close renderings of the Good Friday
Orationes sollemnes (pro Ecclesia, pro imperatore, and bidding VI with its
collect "maestorum consolatio, laborantium fortitudo").
"""
from gp import P

# Luther's paraphrase of the Lord's Prayer (Deutsche Messe 1526), as used in
# Frankfurt 1553/1589 for the closing petition.
LP_PARA_EN = (
    "O Lord God, our Father in heaven, we thy wretched children upon earth beseech "
    "thee that thou wouldest look upon us mercifully and vouchsafe us grace, that thy "
    "holy name may be hallowed among us and in all the world, through the pure and "
    "right doctrine of thy word and through the fervent love of our life. Graciously "
    "turn away all false doctrine and evil life, wherein thy worthy name is blasphemed "
    "and put to shame. Thy kingdom come and be increased: bring all sinners, the "
    "blinded, and them that are taken captive of the devil into his kingdom, to the "
    "knowledge of the right faith in Jesus Christ thy Son, that the number of "
    "Christians may be great. Strengthen us, Lord, with thy Spirit, to do and to "
    "suffer thy will, both in life and in death, in good and in evil, that our will "
    "may at all times be broken, offered up, and slain. And give us our daily bread; "
    "keep us from covetousness and from the care of the belly, that we may look unto "
    "thee for all good things enough. Forgive us our debts, as we forgive our "
    "debtors, that our heart may have a sure and joyful conscience before thee, and "
    "may never fear nor be affrighted before any sin. Lead us not into temptation, "
    "but help us by thy Spirit to subdue the flesh, to despise the world with all "
    "its ways, and to overcome the devil with all his wiles. And at the last deliver "
    "us from all evil, both bodily and ghostly, temporal and eternal. Whosoever "
    "earnestly desire all this, let them say from the heart: Amen; believing without "
    "all doubt that it is Yea and heard in heaven, as Christ promiseth us: What "
    "things soever ye ask, believe that ye shall have them, and it shall be done. Amen.")

W = []

# ---------------------------------------------------------------------------
W.append(dict(
    key='schwaebisch_hall_1526', doc=754, year=1526,
    order='Schwäbisch Hall, Frühmessordnung (Johannes Brenz)',
    territory='Schwäbisch Hall (Imperial city)',
    citation='Sehling 17, I/1, pp. 37–40',
    family='A. Brenz bidding prayer', form='bidding + collect',
    tradition='Lutheran',
    position='After the Kyrie and Gloria, in place of the Latin Oremus/collect; read from a lectern before the altar in a cope. The sermon precedes the whole service.',
    heading='Gemein gebet fur die kirchen zu S[chwäbisch] Hal',
    heading_en='The common prayer for the Church at Schwäbisch Hall',
    notes='Base text A (StadtA Schwäbisch Hall 4/54); variants of MSS B and C in Sehling’s apparatus are not taken in. The Our Father, Creed and Decalogue are printed as part of the common prayer.',
    petitions=[
        P('exhortation',
          r='Vorrede', r_en='Preface',
          b='Auff das all glaubig zubeten gereitzt wurden, so hat unser Herr Cristus dem gebet ein ernstlich versicherung angehengkt, sprechendt: Bitten, so werden ir gewert, suchendt, so werden ir finden, klopffet an, so wirt euch auffgethon.',
          b_en='To the end that all the faithful might be stirred up to pray, our Lord Christ hath annexed unto prayer an earnest assurance, saying: Ask, and ye shall be granted; seek, and ye shall find; knock, and it shall be opened unto you.'),
        P('church', sub='ministers',
          r='Für die kirchen und kirchendinern', r_en='For the Church and the ministers of the Church',
          b='Hieruff lassent uns fleyssig bitten fur die gemein cristenlich kirch, fur der kirchen diener, das sie unser Herr Got wolle beschutzen wider all anleuff und versuchung des boßen feinds, darmit sie auff dem starcken felsen, unserm Herrn Cristo, bestendig pleyben. Bittend Also:',
          b_en='Hereupon let us diligently pray for the common Christian Church, and for the ministers of the Church, that the Lord our God would defend them against all the assaults and temptation of the wicked enemy, that they may abide steadfast upon the strong rock, our Lord Christ. Pray ye thus:',
          p='Almechtiger, ewiger Got, der du hast allen volckern dein gnad durch Jesum Cristum geoffenbaret, erhalt, Herr, das volck deiner barmhertzikait, das dein kirch sampt irn dienern, in der gantzen welt zerstrewt, dir mit bestendigem glauben diene und in bekantnus deins namens bestande.',
          p_en='Almighty, everlasting God, who hast revealed thy grace unto all peoples through Jesus Christ: preserve, O Lord, the people of thy mercy, that thy Church together with her ministers, scattered abroad in the whole world, may serve thee with steadfast faith and continue in the confession of thy name.'),
        P('civil-authority',
          r='Fur die Oberkait', r_en='For the magistracy',
          b='Lassendt uns auch bitten auß gebot und bevelh unsers Herrn Jesu Cristi und seiner Apposteln fur unsern allergnedigsten Herrn, den kaiser, fur alle konig und amptlewt des weltlichen Regiments, sonderlich fur ein erbare Oberkait diser stat, auff das wir ein geruwigs und stils leben in aller gotselikait furen mogen. Bittend Allso:',
          b_en='Let us also pray, by the commandment and bidding of our Lord Jesus Christ and of his apostles, for our most gracious Lord the Emperor, for all kings and officers of the temporal government, and especially for an honourable magistracy of this city, that we may lead a quiet and peaceable life in all godliness. Pray ye thus:',
          p='Barmhertziger, ewiger Got, in welchs handt aller menschen gewalt und Oberkait besten, von dir verordnet zur straff der ubeltetter und wolfart der biderlewt, in welchs handt auch steen all Recht und gesatz aller Reich, Wir bitten dich, sihe gnedigklich auff unsern Herrn, den kaiser, und all sein amptlewt, nemlich auff ein Oberkait diser Stat, darmit sie das weltlich schwerdt, inen von dir bevolhen, in glauben nach deinem wort und bevelh furen mogen.',
          p_en='Merciful, everlasting God, in whose hand standeth the power and authority of all men, ordained of thee for the punishment of evildoers and for the welfare of the upright, in whose hand also stand all the rights and laws of all kingdoms: we beseech thee, look graciously upon our Lord the Emperor and all his officers, and namely upon the magistracy of this city, that they may bear the temporal sword, committed unto them of thee, in faith, according to thy word and commandment.'),
        P('afflicted', sub='error;calamities',
          r='Fur Irthumb und anfechtung', r_en='For error and temptation',
          b='Lassendt uns auch bitten Got, unsern Herrn, das er die welt von Irthum erlosen wol, auch von kranckhaiten, Tewerung, gefengknus, sterben und aller widerwertikait, so durch den bosen feindt uns zur verderpnus zugefugt werden. Bittend also:',
          b_en='Let us also pray God our Lord, that he would deliver the world from error, and also from sicknesses, dearth, imprisonment, death, and all adversity which by the wicked enemy is brought upon us unto our destruction. Pray ye thus:',
          p='Almechtiger, ewiger Got, ein trost der trawrigen, ein sterck der schwachen, laß fur dein angesicht durch unsern Herrn Jesum Cristum komen die bit aller deren, so in bekumernus unnd anfechtung zu dir seufftzen, das menigklich dein hilff und beystand in der zeyt der nodt entpfinde.',
          p_en='Almighty, everlasting God, the comfort of the sorrowful, the strength of the weak: let the prayer of all them that sigh unto thee in trouble and temptation come before thy face, through our Lord Jesus Christ, that every man may feel thy help and succour in the time of need.'),
        P('peace',
          r='Umb Friden', r_en='For peace',
          b='Lassendt uns auch bitten umb ein gemeinen friden und besserung der gantzen Cristenhait, das uns got mit zeitlichem und ewigklichem friden gnedigklich begabe. Bittend also:',
          b_en='Let us also pray for a common peace and for the amendment of all Christendom, that God would graciously endue us with temporal and everlasting peace. Pray ye thus:',
          p='Barmhertziger, ewiger Got, ein konig der himel und erden, durch welchs gaist alle ding regirt, durch welchs fursehung alle ding geordnet werden, ein Got des Frids, wir bitten dich durch unsern Herrn Jesum Cristum, du wollest unsern sunden vergeben und uns mit dem gaist des frids salben, darmit wir in forcht und zittern dir dienen, zu lob und preys deines namens.',
          p_en='Merciful, everlasting God, King of heaven and earth, by whose Spirit all things are governed, by whose providence all things are ordered, the God of peace: we beseech thee through our Lord Jesus Christ, that thou wouldest forgive our sins and anoint us with the spirit of peace, that we may serve thee in fear and trembling, to the laud and praise of thy name.'),
        P('enemies',
          r='Fur unsere Feind', r_en='For our enemies',
          b='Lassendt uns auch bitten fur unsere feind, das Got sie fur in ir aigne erkantnus und sie von irem unrechten abfur. Bittend also:',
          b_en='Let us also pray for our enemies, that God would lead them into the knowledge of themselves and lead them away from their unrighteousness. Pray ye thus:',
          p='Almechtiger, ewiger Got, der du uns durch deinen liben Son, unsern Herrn Jesum Cristum, bevolhen hast, das wir unsere feindt sollen liben, fur unsere verfolger bitten, wir schreyhen hertzlich zu dir, das du wellest unsere feind gnedigklich heimsuchen und inen ein fruntlich, einhellig gemut unnd hertz mit uns und der gantzen Cristenhait geben, durch unsern Herrn Jesum Cristum.',
          p_en='Almighty, everlasting God, who by thy dear Son, our Lord Jesus Christ, hast commanded us to love our enemies and to pray for our persecutors: we cry heartily unto thee, that thou wouldest graciously visit our enemies, and give them a friendly and one-accorded mind and heart with us and with all Christendom; through our Lord Jesus Christ.'),
        P('childbirth',
          r='Fur all schwanger Frawen', r_en='For all women with child',
          b='Lassendt uns bitten fur all schwanger frawen, das got sie gnedigklich von kinds banden erlosen wol. Bittend also:',
          b_en='Let us pray for all women with child, that God would graciously deliver them from the bonds of childbirth. Pray ye thus:',
          p='Barmhertziger, ewiger Got, der du man und weyp reichlich gesegnet hast, sprechend: Seyent fruchtbar und meret Euch, und dem weyp iren kumer im gebern zu einem hailigen Creutz durch unsern Herrn Jesum Cristum gemacht, wir bitten dich, Herr Got, du wollest die frucht irs leips, dein aigen werck, erhalten und sie underm Creutz der schmertzlichen geburt nit verderben laßen, sonder gnedigklich entpinden.',
          p_en='Merciful, everlasting God, who hast richly blessed man and woman, saying: Be fruitful and multiply; and hast made the woman’s sorrow in bearing an holy cross through our Lord Jesus Christ: we beseech thee, Lord God, that thou wouldest preserve the fruit of her womb, thine own work, and suffer her not to perish under the cross of the painful birth, but graciously deliver her.',
          note='Bid printed “erlosen wo”; the final l is lost in the OCR (cf. “erlosen wol” in the bid For error and temptation).'),
        P('fruits-of-earth',
          r='Fur die Fruchten der erden', r_en='For the fruits of the earth',
          b='Lassendt uns auch bitten fur die frucht der erden, das sie Got wol gesegnen und uns wol geraten lassen. Bittend also:',
          b_en='Let us also pray for the fruits of the earth, that God would bless them and let them prosper well for us. Pray ye thus:',
          p='Almechtiger, barmhertziger, ewiger Got, der du durch dein wort alle ding erschafest und gesegnest, wir bitten dich, das du den somen deins worts unsern Herrn Jesum Cristum, uns wollest mittailn und in unser Hertz sewen, dardurch an uns gesegnet werd mit fruchtbarer wachsung und gotlichem gebrauch alles, was uns zur leblichen noturft dienet.',
          p_en='Almighty, merciful, everlasting God, who through thy word createst and blessest all things: we beseech thee that thou wouldest impart unto us the seed of thy word, our Lord Jesus Christ, and sow him in our heart, whereby there may be blessed unto us, with fruitful increase and godly use, all that serveth us for our bodily need.'),
        P('lords-prayer', sub='conclusion',
          r='Gemein Gebet', r_en='Common prayer',
          b='Lassendt uns auch bitten sonst fur alles, so Got, unser Herr, gebetten sein wil, sprechend ein Vater unser.',
          b_en='Let us also pray besides for all things for which God our Lord will be prayed unto, saying an Our Father.'),
        P('lords-prayer',
          r='Des Herrn Gebet', r_en='The Lord’s Prayer',
          p='Vater unser in dem himel, etc.', p_en='Our Father, which art in heaven, etc.'),
        P('creed',
          r='Die bekantnus des Glaubens', r_en='The confession of the faith',
          p='Ich glaub in Got vater, almechtigen.', p_en='I believe in God the Father Almighty.'),
        P('decalogue',
          r='Die zehen gebot', r_en='The Ten Commandments',
          p='Disse wort hat der Herr alle geredt: Ich bin der Herr, etc.', p_en='The Lord spake all these words: I am the Lord, etc.'),
        P('special-supplications',
          r='Das wer nu fur das gemein gebet. Man mocht alwegen gebet hintzusetzen nach zufallenden sachen mit kriegen, pestilentz oder sonderlichen kranckhaiten, etc.',
          r_en='This, then, were for the common prayer. Prayers might always be added thereto according to matters as they befall, with wars, pestilence, or special sicknesses, etc.'),
    ]))

# ---------------------------------------------------------------------------
W.append(dict(
    key='schwaebisch_hall_1543', doc=762, year=1543,
    order='Schwäbisch Hall, Kirchenordnung 1543',
    territory='Schwäbisch Hall (Imperial city)',
    citation='Sehling 17, I/10, pp. 142–145',
    family='A. Brenz bidding prayer', form='bidding + collect',
    tradition='Lutheran', position='After the sermon, from the pulpit (per the 1614/15 revision); the 1543 text places it as the “form of the common prayer” of the Sunday service.',
    heading='So folget nun ein form des gemeinen Gebeets, wie sie inn der Kirchen fürgesprochen werden sol',
    heading_en='There followeth now a form of the common prayer, as it shall be said before the people in the church',
    notes='Base text 1543. Sehling’s apparatus prints the thoroughly rewritten continuous prayer of the 1614 draft / KO 1615 as variants; that later form is not reconstructed here.',
    petitions=[
        P('exhortation', r='Vorrede', r_en='Preface',
          b='Unser HERR Christus hat uns nicht allein bevolhen unnd gebotten zu beeten, sonder auch warhafftiglich versprochen, das Gebeet, so es im rechten vertrawen Götlicher zusagung geschicht, sol gewißlich von Gott erhöret werden, und sagt: Bittet, so wirt euch gegeben, suchet, so werdt ir finden, klopfft an, so wirt euch auffgethan. Denn wer da bittet, der nimpt, wer da sucht, der findt und wer do anklopfft, dem wirt auffgethon.',
          b_en='Our LORD Christ hath not only commanded and enjoined us to pray, but hath also truly promised that prayer, if it be made in right trust in the divine promise, shall surely be heard of God; and he saith: Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you. For he that asketh receiveth, he that seeketh findeth, and to him that knocketh it shall be opened.'),
        P('church', sub='ministers',
          b='Hierauff lassent uns bitten für die gmein Christlich Kirch und für ire diener, das sie unser Herr Gott beschütze wider alle anleuff und versuchung des bösen feinds und erhalte sie bestendiglich auff dem rechten felsen, unserm HERRN Jesu Christo. Bettent also:',
          b_en='Hereupon let us pray for the common Christian Church and for her ministers, that the Lord our God would defend them against all the assaults and temptation of the wicked enemy, and keep them steadfastly upon the right rock, our LORD Jesus Christ. Pray ye thus:',
          p='Allmechtiger, ewiger Gott, der du hast allen Völckern dein genad durch Jesum Christum und sein Evangelion offenbaret, erhalt, HERR, das volck deiner barmhertzigkeit, das dein Kirch sampt iren dienern, inn der gantzen welt zerstrewet, dir mit rechtem glauben diene und inn bekantnus deines namens bestande.',
          p_en='Almighty, everlasting God, who hast revealed thy grace unto all peoples through Jesus Christ and his Gospel: preserve, O LORD, the people of thy mercy, that thy Church together with her ministers, scattered abroad in the whole world, may serve thee with right faith and continue in the confession of thy name.'),
        P('civil-authority',
          b='Lassent uns bitten für die weltlich Oberkeit, für unsere Herrn, die Römischen Keyser und König, für alle Christliche herschafft, sonderlich für ein Erbarn Rath diser Stadt, das wir ein gerüwigs und stils leben in allem Göttlichem gehorsam füren mögen. Bittent also:',
          b_en='Let us pray for the temporal magistracy, for our lords the Roman Emperor and King, for all Christian lordship, and especially for an honourable Council of this city, that we may lead a quiet and peaceable life in all godly obedience. Pray ye thus:',
          p='Barmhertziger, Himelischer Vater, in welches hand bestehet aller menschen gwalt und Oberkeit, von dir gesetzt zur straff der bösen und wolfart der frummen, inn welches hand auch stehn alle Recht und Gesetz aller Reich auff Erden, Wir bitten dich, sihe gnediglich auff unsere Herrn, die Römischen Keyser unnd König als unsere öbriste weltliche häupter und andere ordenliche Christliche Oberkeit, sonderlich auff unsere herschafft, ein Erbarn Rath der Stadt Schwebischen Hall, das sie das weltlich Schwerdt, inen von dir bevolhen, nach deinem bevelch füren mögen.',
          p_en='Merciful, heavenly Father, in whose hand standeth the power and authority of all men, set of thee for the punishment of the wicked and the welfare of the godly, in whose hand also stand all the rights and laws of all kingdoms upon earth: we beseech thee, look graciously upon our lords the Roman Emperor and King, as our highest temporal heads, and upon all other ordained Christian magistracy, especially upon our lordship, an honourable Council of the city of Schwäbisch Hall, that they may bear the temporal sword, committed unto them of thee, according to thy commandment.',
          note='“öbriste” printed “Sbriste” (OCR).'),
        P('afflicted', sub='error;calamities',
          b='Lassent uns bitten, das Gott uns gnediglich erlöse von allem irthumb, kranckheit, tewrung, gfengnus, pestilentz und von aller widerwertigkeit, so der böß feind uns zur verderbnus zu füget. Bittent also:',
          b_en='Let us pray that God would graciously deliver us from all error, sickness, dearth, imprisonment, pestilence, and from all adversity which the wicked enemy bringeth upon us unto our destruction. Pray ye thus:',
          p='Allmechtiger, ewiger Gott, ein trost der traurigen, ein stercke der schwachen, las für dein angesicht kommen die bitt aller derer, die in bekümmernus und anfechtung zu dir seufftzen, das sie dein gnedig hilff inn aller irer not entpfinden, durch unsern HERRN Jesum Christ, AMEN.',
          p_en='Almighty, everlasting God, the comfort of the sorrowful, the strength of the weak: let the prayer of all them that sigh unto thee in trouble and temptation come before thy face, that they may feel thy gracious help in all their need; through our LORD Jesus Christ. AMEN.'),
        P('peace',
          b='Lassent uns auch bitten umb ein gemeinen friden, das wir Gottis wort mögen lernen und inn einem erbarlichen Christlichen leben wandeln. Bittent also:',
          b_en='Let us also pray for a common peace, that we may learn God’s word and walk in an honest Christian life. Pray ye thus:',
          p='Allmechtiger, ewiger Got, ein Herr Himels und der Erden, durch welches Geist alle ding regirt, durch welches fürsehung alle ding geordnet werden, der du bist ein Gott des friedens, Wir bitten dich, du wollest uns mit deinem Gotlichen friden und einigkeit begnaden, das wir dir in rechter forcht zu lob und preiß deines namens dienen.',
          p_en='Almighty, everlasting God, Lord of heaven and earth, by whose Spirit all things are governed, by whose providence all things are ordered, who art the God of peace: we beseech thee, vouchsafe us thy godly peace and concord, that we may serve thee in right fear, to the laud and praise of thy name.'),
        P('enemies',
          b='Lassent uns auch bitten für unsere feinde, das Gott sie mit gnaden bedencke und inen, was zu irem heil nutzlich und notdürfftig ist, gnediglich verleyhe. Bittent also:',
          b_en='Let us also pray for our enemies, that God would remember them with grace, and graciously grant them what is profitable and needful to their salvation. Pray ye thus:',
          p='Allmechtiger, ewiger Gott, der du uns bevolhen hast, das wir unser feind lieb haben sollen, denen, die uns beleidigen, guts thun und für unsere verfolger bitten, Wir schreien ernstlich zu dir, das du alle unsere feind wöllest gnediglich heimsuchen, inen ware rew irer sünden verleihen, auch mit uns und der gantzen Christenheit ein freundtliches, Gotsförchtigs, einhelligs gemüt und hertz geben, durch unsern Herrn Jesum Christ, AMEN.',
          p_en='Almighty, everlasting God, who hast commanded us to love our enemies, to do good to them that despitefully use us, and to pray for our persecutors: we cry earnestly unto thee, that thou wouldest graciously visit all our enemies, grant them true repentance for their sins, and give them a friendly, God-fearing, one-accorded mind and heart with us and with all Christendom; through our Lord Jesus Christ. AMEN.'),
        P('childbirth',
          b='Lassent uns auch bitten für alle schwangere Weiber, das Gott sie gnediglich von Kindsbanden erlösen wöl. Bittent also:',
          b_en='Let us also pray for all women with child, that God would graciously deliver them from the bonds of childbirth. Pray ye thus:',
          p='Allmechtiger, ewiger Gott und Vater, ein schöpffer aller ding, der du Man und Weib gnediglich gesegnet und dem weib iren kummer im geberen zu einem heiligen Creutz durch unsern Herrn Jesum Christum geweyhet hast, Wir bitten dich, Herre Gott, du wöllest die frucht ires leibs, dein eigen geschöpff, erhalten und bewaren und unter dem Creutz inn der bekümmerlichen geburt nicht verderben lassen, sonder gnediglich und mit freuden entpinden, AMEN.',
          p_en='Almighty, everlasting God and Father, Creator of all things, who hast graciously blessed man and woman, and hast hallowed the woman’s sorrow in bearing into an holy cross through our Lord Jesus Christ: we beseech thee, Lord God, that thou wouldest preserve and keep the fruit of her womb, thine own creature, and suffer her not to perish under the cross in the grievous birth, but graciously and with joy deliver her. AMEN.'),
        P('fruits-of-earth',
          b='Lassent uns auch bitten für die frücht der Erden, das sie Gott wöl gesegnen und, uns die selben inn seinem gehorsam zugniessen, gnediglich verleihen. Bittent also:',
          b_en='Let us also pray for the fruits of the earth, that God would bless them and graciously grant us to enjoy the same in his obedience. Pray ye thus:',
          p='Allmechtiger, ewiger Gott, der du durch dein wort alle ding erschaffest und gesegnest, Wir bitten dich, das du dein Wort, unsern Herrn Jesum Christ, inn unser hertz pflantzest, dardurch an uns gesegnet werde mit fruchtbarer wachsung und Götlichem gebrauch alles, was uns zur leiblichen notdurfft dienet.',
          p_en='Almighty, everlasting God, who through thy word createst and blessest all things: we beseech thee that thou wouldest plant thy Word, our Lord Jesus Christ, in our heart, whereby there may be blessed unto us, with fruitful increase and godly use, all that serveth us for our bodily need.'),
        P('lords-prayer', sub='conclusion',
          b='Lassent uns auch sonst bitten für alles, so unser Herr gebeeten sein wil, sprechent: Vater unser, etc.',
          b_en='Let us also pray besides for all things for which our Lord will be prayed unto, saying: Our Father, etc.'),
    ]))

# ---------------------------------------------------------------------------
_frankfurt_common = dict(
    territory='Frankfurt am Main (Imperial city)',
    family='A. Brenz bidding prayer', form='bidding + collect',
    tradition='Lutheran',
    position='Within the Communion office: after the exhortation to the communicants, before the Words of Institution.')

W.append(dict(
    key='frankfurt_1553', doc=2332, year=1553,
    order='Frankfurt am Main, Agende 1553 („Einfeltige form, das Nachtmal des Herren zuhalten“)',
    citation='Sehling 9, VI/Frankfurt Nr. 10, pp. 524–526',
    heading=None, heading_en=None,
    notes='Base text KO 1553; variants of KO 1564, 1565 and 1579/80 in Sehling’s apparatus not taken in. Collects adapted from Brandenburg-Nürnberg 1533 and Veit Dietrich 1545 (Sehling’s notes). The last petition is Luther’s paraphrase of the Lord’s Prayer from the Deutsche Messe.',
    petitions=[
        P('exhortation',
          b='Damit aber die unbußfertigen durch Gottes gnad erleuchtet, auch gemeine Christenheit gebessert und erbawet werden möge, so lasset uns Gott, den Vatter aller barmhertzigkeit, auff seinen befelh und verheissung durch Jesum Christum von hertzen anrüffen und lasset uns bitten:',
          b_en='But to the end that the impenitent may be enlightened by the grace of God, and the common Christendom amended and edified, let us call from the heart upon God, the Father of all mercies, at his commandment and promise, through Jesus Christ; and let us pray:'),
        P('church', sub='ministers',
          b='I. Für die gemeine Christliche Kirch, ire Diener und Lehrer Götlichs Worts, und betet also:',
          b_en='I. For the common Christian Church, her ministers and the teachers of God’s Word; and pray ye thus:',
          p='Almechtiger, Ewiger Gott, der du hast allen Völckern deine genad durch Jesum Christum und sein Evangelion offenbaret, Erhalte, Herr, das Volck deiner barmhertzigkeit, das dein Kirche sampt iren Dienern, in der gantzen Welt zerstrewet, dir mit rechtem glauben diene und wider allen anlauff und versuchung des bösen feinds in bekantniß deines Namens und auff dem rechten felsen, unserm Herren Jesu Christo, festiglich bestehe.',
          p_en='Almighty, everlasting God, who hast revealed thy grace unto all peoples through Jesus Christ and his Gospel: preserve, O Lord, the people of thy mercy, that thy Church together with her ministers, scattered abroad in the whole world, may serve thee with right faith, and against every assault and temptation of the wicked enemy may stand fast in the confession of thy name and upon the right rock, our Lord Jesus Christ.'),
        P('civil-authority',
          b='II. Lasset uns auch bitten für Keiserliche Mayestat und alle Oberkeit, sonderlich für ein Erbarn Rath und Burgermeister dieser Stadt, und betet also:',
          b_en='II. Let us also pray for his Imperial Majesty and all magistracy, especially for an honourable Council and Burgomaster of this city; and pray ye thus:',
          p='Barmhertziger, Himlischer Vatter, in welches Handt besteht aller Menschen gwalt und Oberkeit, von dir gesetzt zur straffe der bösen und wolfart der frommen, in welchs Handt auch stehn alle Rechte und gesetze aller Reich auff Erden. Sihe gnediglich auff Kei. May. und aller Oberkeit, sonderlich uff einen Erbarn Rath und Burgermeister dieser Stadt, das sie das Weltlich schwerdt, inen von dir befohlen, nach deinem befelh gebrauchen, auff das wir ein rüwigs und stilles leben in allem Göttlichen gehorsam füren mögen.',
          p_en='Merciful, heavenly Father, in whose hand standeth the power and authority of all men, set of thee for the punishment of the wicked and the welfare of the godly, in whose hand also stand all the rights and laws of all kingdoms upon earth: look graciously upon his Imperial Majesty and all magistracy, and especially upon an honourable Council and Burgomaster of this city, that they may use the temporal sword, committed unto them of thee, according to thy commandment, that we may lead a quiet and peaceable life in all godly obedience.'),
        P('afflicted', sub='turks;calamities',
          b='III. Lasset uns auch bitten, das Gott alle irthumb, kranckheit, tewrung, gefengniß, sterben, sönderlich aber den grausamen erbfeind Christlichs bluts und Namens, den Türcken, sampt aller widerwertigkeit von uns gnediglich abwenden wölle und betet also:',
          b_en='III. Let us also pray that God would graciously turn away from us all error, sickness, dearth, imprisonment, death, and especially the cruel hereditary enemy of the Christian blood and name, the Turk, together with all adversity; and pray ye thus:',
          p='Almechtiger, Ewiger Gott, ein trost der trawrigen, ein stercke der schwachen, lasse für dein angesicht kommen die bitte aller deren, so in bekümmernuß und anfechtungen zu dir seufftzen, das sie deine gnedige hülffe in aller not empfinden. Du wöllest deinen zorn von allen bußfertigen abwenden, sie in allerley straffe und plage, vorab von allen Tyrannen und feinden Christliches namens, sampt aller widerwertigkeit gnediglich erretten.',
          p_en='Almighty, everlasting God, the comfort of the sorrowful, the strength of the weak: let the prayer of all them that sigh unto thee in trouble and temptations come before thy face, that they may feel thy gracious help in all need. Turn away thy wrath from all the penitent, and graciously rescue them in every kind of punishment and plague, above all from all tyrants and enemies of the Christian name, together with all adversity.'),
        P('peace',
          b='IIII. Lasset uns auch bitten umb einen gemeinen frieden, und betet also:',
          b_en='IV. Let us also pray for a common peace; and pray ye thus:',
          p='Almechtiger, Ewiger Gott, ein Herr Himels und der Erden, durch welches Geist alle ding geordnet werden, der du bist ein Gott des friedens, wir bitten dich, du wöllest uns mit deinem Göttlichen frieden und einigkeit begnaden, das wir dein Göttlichs Wort mögen lernen, in einem erbarlichen, Christlichen leben wandeln und dir in rechter forcht zu lob und preise deines Namens dienen.',
          p_en='Almighty, everlasting God, Lord of heaven and earth, by whose Spirit all things are ordered, who art the God of peace: we beseech thee, vouchsafe us thy godly peace and concord, that we may learn thy divine Word, walk in an honest Christian life, and serve thee in right fear, to the laud and praise of thy name.'),
        P('childbirth',
          b='V. Lasset uns auch bitten für alle schwangere Frawen, und betet also:',
          b_en='V. Let us also pray for all women with child; and pray ye thus:',
          p='Almechtiger, Ewiger Got und Vatter, ein Schöpffer aller ding, der du Mann und Weib gnediglich gesegnet und dem Weib iren kummer im geberen zu einem Heiligen creutz durch unsern Herren Jesum Christum geweihet hast, wir bitten dich, Herre Gott, du wöllest die frucht ires Leibs, dein eigen geschöpff, erhalten und bewaren und unter dem creutz in der bekümmerlichen geburt nicht verderben lassen, sondern genediglich und mit freuden entbinden durch unsern Herren Jesum Christum, Amen.',
          p_en='Almighty, everlasting God and Father, Creator of all things, who hast graciously blessed man and woman, and hast hallowed the woman’s sorrow in bearing into an holy cross through our Lord Jesus Christ: we beseech thee, Lord God, that thou wouldest preserve and keep the fruit of her womb, thine own creature, and suffer her not to perish under the cross in the grievous birth, but graciously and with joy deliver her; through our Lord Jesus Christ. Amen.'),
        P('lords-prayer', sub='conclusion',
          b='VI. Lasset uns auch sonst bitten für alles, so unser Herre Gott gebetten sein will, und betet also:',
          b_en='VI. Let us also pray besides for all things for which the Lord our God will be prayed unto; and pray ye thus:',
          p='O Herre Gott, unser Vatter im Himel, wir, deine elende Kinder auff Erden, bitten dich, das du uns barmhertziglich ansehen und gnad verleihen wöllest, Das dein Heiliger Name unter uns und in aller Welt geheiliget werde durch reine, rechtschaffene Lehr deines Worts und durch brünstige liebe unsers lebens. Wende ab genediglich alle falsche lehr und böses leben, darinnen dein werder nam gelestert und geschendet wird. Dein Reich komme und werde gemehret, Alle sünder, verblendte und vom Teuffel in sein reich gefangenen bring zum erkantniß des rechten glaubens an Jesum Christ, deinen Son, auff das die zal der Christen groß werde. Stercke uns, Herr, mit deinem Geist, deinen willen zuthun und zu leiden beide, im leben und sterben, im guten und bösen, auff das alle zeit unser will gebrochen, geopffert und getödtet werde. Und gib uns unser teglichs brot, für geitz und sorge des Bauchs behüte, damit wir uns alles guten gnug zu dir mögen versehen. Vergib uns unser schuld, wie wir unsern schuldigern vergeben, das unser hertz ein sicher, frölich gewissen für dir habe und für keiner sünde uns nimmer fürchten noch erschrecken. Nicht füre uns in anfechtunge, sondern hilff uns, durch deinen Geist das fleisch zwingen, die Welt mit irem wesen verachten und den Teuffel mit allen seinen tücken uberwinden. Und zuletzt erlöse uns von allem ubel beide, leiblich und geistlich, zeitlich und ewiglich. Welche das alles mit ernst begeren, die sprechen von hertzen: Amen; On allen zweiffel glaubet, es sey „ja“ und erhöret im Himel, wie uns Christus zusagt: Was ir bittet, glaubet, das irs haben werdet, so soll es geschehen, Amen.',
          p_en=LP_PARA_EN,
          note='Luther’s paraphrase of the Lord’s Prayer from the Deutsche Messe (1526), used as the concluding prayer.'),
    ], **_frankfurt_common))

W.append(dict(
    key='frankfurt_1589', doc=2332, year=1589,
    order='Frankfurt am Main, Agende 1589',
    citation='Sehling 9, VI/Frankfurt Nr. 13, pp. 552–553',
    heading=None, heading_en=None,
    notes='Same series as the Agende 1553 with minor wording changes, and a new closing prayer for the Holy Spirit upon the communicants.',
    petitions=[
        P('exhortation', tr_from=('frankfurt_1553', 1),
          b='Damit aber die Unbußfertigen durch Gottes Gnade erleuchtet, auch Gemeine Christenheit gebessert und erbauwet werden möge, so lasset uns Gott, den Vatter aller Barmhertzigkeit, auff seinen Befehl und Verheissung durch Jesum Christum von Hertzen anruffen und lasset uns betten:'),
        P('church', sub='ministers',
          b='Für die Gemeine Christliche Kirche, ihre Diener und Lehrer Göttlichs Worts, und betet also:',
          b_en='For the common Christian Church, her ministers and the teachers of God’s Word; and pray ye thus:',
          p='Allmechtiger, ewiger Gott, der du hast allen Völckern deine Genade durch Jesum Christum und sein Evangelion offenbaret, Erhalte, Herr, das Volck deiner Barmhertzigkeit, daß deine Kirche sampt iren Dienern, in der gantzen Welt zerstreuwet, dir mit rechtem Glauben diene und wider allen Anlauff und Versuchung deß bösen Feindes in Bekanntnuß deines Namens und auff dem rechten Felsen, unserm Herren Jesu Christo, festiglich bestehe.',
          tr_from=('frankfurt_1553', 2)),
        P('civil-authority',
          b='Lasset uns auch bitten für Käyserliche Majestät und alle Oberkeit, sonderlich fur ein Erbaren Rath und Bürgermeister dieser Statt, und bettet also:',
          b_en='Let us also pray for his Imperial Majesty and all magistracy, especially for an honourable Council and Burgomaster of this city; and pray ye thus:',
          p='Barmhertziger, Himmlischer Vatter, in welches Hand bestehet aller Menschen Gewalt und Oberkeit, von dir gesetzt zur straff der Bösen und Wolfart der Frommen, in welches Hand auch stehen alle Rechte und Gesetze aller Reich auff Erden. Sihe genediglich auff Käyserliche Majestet unnd aller Oberkeit, sonderlich aber auff ein Ehrbaren Rath unnd Bürgermeister dieser Statt, daß sie das Weltliche Schwert, ihnen von dir befohlen, nach deinem Befehl gebrauchen, auff daß wir ein rühiges unnd stilles Leben in allem Göttlichen Gehorsam führen mögen.',
          tr_from=('frankfurt_1553', 3)),
        P('afflicted', sub='turks;calamities',
          b='Lasset uns auch bitten, daß Gott alle Irrthumb, Kranckheit, Thewrung, Gefengnuß, Sterben, sonderlich aber den grauwsamen Erbfeind Christliches Bluts und Namens, den Türcken, sampt aller Widerwertigkeit von uns genediglich abwenden wölle, und bettet also:',
          b_en='Let us also pray that God would graciously turn away from us all error, sickness, dearth, imprisonment, death, and especially the cruel hereditary enemy of the Christian blood and name, the Turk, together with all adversity; and pray ye thus:',
          p='Allmechtiger, ewiger Gott, ein Trost der trauwrigen, ein stärcke der schwachen, lasse für dein Angesicht kommen die Bitte aller deren, so in Bekümmernuß und Anfechtungen zu dir Seufftzen, daß sie deine genedige Hülff in aller Noth entpfinden, Du wöllest deinen Zorn von allen Bußfertigen Sündern genediglich abwenden, sie in allerley Straffe und Plage, vorab von allen Tyrannen und Feinden Christliches Namens und von aller Widerwerdigkeit genediglich erretten.',
          p_en='Almighty, everlasting God, the comfort of the sorrowful, the strength of the weak: let the prayer of all them that sigh unto thee in trouble and temptations come before thy face, that they may feel thy gracious help in all need. Graciously turn away thy wrath from all penitent sinners, and graciously rescue them in every kind of punishment and plague, above all from all tyrants and enemies of the Christian name, and from all adversity.'),
        P('peace',
          b='Lasset uns auch bitten umb einen gemeinen Frieden, und bettet also:',
          b_en='Let us also pray for a common peace; and pray ye thus:',
          p='Allmechtiger, ewiger Gott, ein Herr Himmels und der Erden, durch welches Geist alle ding geordnet werden, der du bist ein Gott deß Friedens, Wir bitten dich, du wöllest uns mit deinem Göttlichen Frieden unnd Einigkeit begnaden, daß wir dein Göttliches Wort mögen lernen, in einem Ehrbarlichen, Christlichen Leben wandeln und dir in rechter Forcht zu Lob und Preiß deines Namens dienen.',
          tr_from=('frankfurt_1553', 5)),
        P('childbirth',
          b='Lasset uns auch bitten für alle Schwangere Frauwen, und bettet also:',
          b_en='Let us also pray for all women with child; and pray ye thus:',
          p='Allmechtiger, ewiger Gott und Vatter, ein Schöpffer aller ding, der du Mann und Weib genediglich gesegnet und dem Weib ihren Kummer und Geberen zu einem Heiligen Creutz durch unsern Herren Jesum Christum geweyhet hast, Wir bitten dich, Herr Gott, du wöllest die Frucht ires Leibes, dein eigen Geschöpff, erhalten und bewaren unnd unter dem Creutz in der bekümmerlichen Geburt nicht verderben lassen, sondern genediglich und mit frewden entbinden, Durch unsern Herren Jesum Christum, Amen.',
          tr_from=('frankfurt_1553', 6)),
        P('lords-prayer', sub='conclusion',
          b='Lasset uns auch sonst bitten für alles, so unser Herr Gott gebetten seyn wil, und bettet also:',
          b_en='Let us also pray besides for all things for which the Lord our God will be prayed unto; and pray ye thus:',
          p='O Herre Gott, unser Vatter im Himmel, wir, deine elende Kinder auff Erden, bitten dich, daß du uns barmhertziglich ansehen und Genad verleihen wöllest, daß dein Heiliger Nam unter uns unnd in aller Welt geheiliget werde durch reine, rechtschaffene Lehr deines Worts und durch brünstige Liebe unsers Lebens. Wende ab genediglich alle falsche Lehr und böses Leben, darinnen dein werther Nam gelestert und geschendet wird. Dein Reich komme unnd werde gemehret, alle Sünder, verblendte unnd vom Teuffel in sein Reich gefangene bring zum Erkanntnuß deß rechten Glaubens an Jesum Christum, deinen Sohn, auff daß die Zahl deiner Christen groß werde. Stärcke uns, Herr, mit deinem Geist, deinen Willen zu thun und zu leyden beyde, im Leben und Sterben, im guten und bösen, auff daß allezeit unser Will gebrochen, geopffert und getödtet werde. Und gib uns unser täglichs Brot, für Geitz und Sorge deß Bauchs behüte, damit wir uns allen genug zu dir mögen versehen. Vergib uns unser Schuldt, wie wir unsern Schuldigern vergeben, daß unser Hertz ein sicher, frölich Gewissen für dir habe und vor keiner Sünde uns nimmermehr förchten noch erschrecken. Nicht führe uns in Anfechtung, sondern hilff uns durch deinen Geist das Fleisch zwingen, die Welt mit irem Wesen verachten unnd den Teuffel mit allen seinen Tücken uberwinden. Und zuletzt Erlöse uns von allem Ubel beyde, Leiblich und Geistlich, zeitlich und ewiglich. Welche das alles mit ernst begeren, die sprechen von Herzten: Amen; Ohn allen zweiffel glaubet, es sey „ja“ und erhöret im Himmel, wie uns Christus zusagt: Was ihr bittet, glaubet, daß ihrs haben werdet, so soll es geschehen, Amen.',
          tr_from=('frankfurt_1553', 7),
          tr_sub=[('that the number of Christians may be great', 'that the number of thy Christians may be great'),
                  ('that we may look unto thee for all good things enough', 'that we may look unto thee for enough of all things')],
          note='Luther’s paraphrase of the Lord’s Prayer (Deutsche Messe 1526).'),
        P('communicants',
          p='Uber das alles bitten wir, O Herr Jesu Christe, dich, der du dieses Sacraments stiffter und erhalter bist, daß du uns, die wir solches zu entpfahen hie erscheinen, deinen Heiligen Geist laut deiner vielfältigen Verheissung reichlich mittheilen wöllest, der unsere Hertzen stärcke und erhalte in ungezweiffeltem Glauben deiner Wort, in warer Erkanntnuß, Reuw und Leyd unserer Sünde und in festem vertrawen auff dein allein genugthuhung für dieselbigen, damit wir nicht unwirdiglich, sonder wirdiglich der thewren Pfande deines heiligen Leibs und Bluts theilhafftig werden umb deines heiligen Leidens und Sterbens unnd dieses deines Heiligen Testaments Ehre willen, Amen.',
          p_en='Over and above all this we beseech thee, O Lord Jesu Christ, who art the founder and upholder of this Sacrament, that thou wouldest richly impart unto us, who appear here to receive the same, thy Holy Spirit according to thy manifold promise, who may strengthen and keep our hearts in undoubting faith in thy words, in true knowledge, repentance and sorrow for our sins, and in firm trust in thy sole satisfaction for the same, that we may be partakers, not unworthily but worthily, of the precious pledges of thy holy Body and Blood; for the honour of thy holy sufferings and death and of this thy holy Testament. Amen.'),
    ], **_frankfurt_common))

# ---------------------------------------------------------------------------
W.append(dict(
    key='neckarbischofsheim_1560', doc=742, year=1560,
    order='Neckarbischofsheim, Kirchenordnung (Herren von Helmstatt)',
    territory='Lordship of Neckarbischofsheim (Kraichgau)',
    citation='Sehling 16, V, pp. 670–672',
    family='A. Brenz bidding prayer', form='bidding + collect',
    tradition='Lutheran',
    position='After the sermon, the general confession and absolution and the Creed hymn, said by the pastor before the altar; followed by the Our Father, a word of assurance (Mt 21:22) with blessing, “Danck sagen wir alle” and the benediction.',
    heading='thut das gemein gebet volgender gestalt',
    heading_en='maketh the common prayer after this manner',
    notes='Brenz’s bidding for the Church and his collect (Schwäbisch Hall 1526), then biddings in his manner with collects freely after Brandenburg-Nürnberg 1533; Latin headings; each collect closes “sprecht von Hertzen: Amen”.',
    petitions=[
        P('exhortation',
          b='Andechtige, geliebte gottes in Christo, dem herren. Dieweil wir, jetz alhie versamlet, gehert haben das wirdige, edel und crefftige wort gottes, welches ist ein wort der warhait, des hails und lebens, dardurch alle ausserwelte kinder gottes im glauben und liebe geiebt und gefüret werden zu einem Christlichen, gottseligen leben und weßen, darumb so last uns in der liebe unserm Nechsten dienen und neben der teglichen hilff und handtraichung, so wir in sonderhait den armen, unsern Brüdern und mitglidern, aus gottes bevelch zu thun schuldig, nach seinem wort und trostlicher zusagung auch getrewlich biten für alle anligende notturfft der gantzen Christlichen gemain und anfenckhlich:',
          b_en='Devout and beloved of God in Christ the Lord: forasmuch as we, here now assembled, have heard the worthy, noble and mighty word of God, which is a word of truth, of salvation and of life, whereby all the elect children of God are exercised in faith and love and led to a Christian, godly life and conversation: therefore let us in love serve our neighbour, and besides the daily help and ministering which we owe by God’s commandment especially to the poor, our brethren and fellow members, let us also, according to his word and comfortable promise, faithfully pray for all the pressing necessity of the whole Christian congregation, and first:'),
        P('church', sub='ministers',
          r='Pro Ministris Ecclesiae.', r_en='For the ministers of the Church.',
          b='Für die gemaine Christliche kirchen und alle derselben diener in dem wort gottes, uf das sy gott durch seinen heiligen gaist sterckhen welle wider allen anlauff und versuchung des besen feindes, darmit sy uf dem starckhen felßen, unsern herren Jesu Christo, bestendig bleiben. Bettend mit mir also:',
          b_en='For the common Christian Church and all the ministers thereof in the word of God, that God would strengthen them by his Holy Spirit against all the assaults and temptation of the wicked enemy, that they may abide steadfast upon the strong rock, our Lord Jesus Christ. Pray ye with me thus:',
          p='Allmechtiger, ewiger gott, der du hast allen velckhern deine gnad durch unsern herren Jesum Christum geoffenbaret, erhalt, herr, das volckh deiner Barmhertzigkait, das deine Kirche sampt deinen dienern in deinem wort, durch die gantze welt zerstrewet, dir mit bestendigem glauben dienen und in bekantnus deines heiligen Namens bestendig bleiben, sprecht von Hertzen: Amen.',
          p_en='Almighty, everlasting God, who hast revealed thy grace unto all peoples through our Lord Jesus Christ: preserve, O Lord, the people of thy mercy, that thy Church together with thy ministers in thy word, scattered throughout the whole world, may serve thee with steadfast faith and abide steadfast in the confession of thy holy name. Say ye from the heart: Amen.'),
        P('civil-authority',
          r='Pro Magistratu.', r_en='For the magistrates.',
          b='Lasset uns auch aus gottes bevelch bitten für die weltliche Obrigkait, unsern allergnedigsten herren, den Römischen Kayser, alle Christliche König, Chur- und Fürsten, der selbigen Reth und diener, auch für ein gnedige herrschafft dises fleckhens, der amptleut und bevelchshaber, das wir under inen ein geruwiges und stilles leben füren megen in aller gottseligkait, dan soliches gut darzu angenem ist vor gott, dem herren, welcher will, das alle menschen genesen und zue erkantnus der warhait kommen. Bettend mit mir also:',
          b_en='Let us also by God’s commandment pray for the temporal magistrates, our most gracious lord the Roman Emperor, all Christian kings, Electors and princes, their counsellors and servants, and also for a gracious lordship of this township, its officers and governors, that we may lead under them a quiet and still life in all godliness; for this is good and acceptable before God the Lord, who will have all men to be saved and to come unto the knowledge of the truth. Pray ye with me thus:',
          p='Allmechtiger, ewiger gott, in welches hannd aller menschen gewalt und Obrigkait bestehn, von dir gesetzt zur straff der übelthetter und wolfart der frommen menschen, in welches hand auch sten alle rechte und gesatz aller Reich, wir biten dich, sihe gnedigklich uf unsern allergnedigsten herren, den Römischen Kaiser, uf alle Churfürsten, Fürsten und herren der Christenhait, auch uf ein gnedige herrschafft dises fleckhens, deren ampt und bevelchsleüten. Erleuchte sy mit erkantnus deiner güette und des heiligen Evangeliums, uf das si dich für iren rechten oberherren erkenen, nach deinem getlichen wolgefallen regieren und das weltliche schwert, inen von dir bevolchen, Christlich nach deinem wort und befelch füren megen, sprecht von Hertzen: Amen.',
          p_en='Almighty, everlasting God, in whose hand standeth all power and authority of men, set of thee for the punishment of evildoers and the welfare of godly men, in whose hand also stand all the rights and laws of all realms: we beseech thee, look graciously upon our most gracious lord the Roman Emperor, upon all Electors, princes and lords of Christendom, and also upon a gracious lordship of this township, its officers and governors. Enlighten them with the knowledge of thy goodness and of the holy Gospel, that they may acknowledge thee for their rightful overlord, rule according to thy divine good pleasure, and bear the temporal sword, committed unto them of thee, in Christian wise according to thy word and commandment. Say ye from the heart: Amen.'),
        P('afflicted', sub='calamities; errant',
          r='Für Kranckhait.', r_en='For sickness.',
          b='Lasset uns auch unsern herren gott anruffen, das er die welt von irthum, Kranckhait, Tewerung, gefenckhnus, sterben und aller widerwertigkait, so uns durch den besen gaist zu verderbung werden zue gefügt, gnedigklich wolle erlesen. Bettet mit mir also:',
          b_en='Let us also call upon the Lord our God, that he would graciously deliver the world from error, sickness, dearth, imprisonment, death, and all adversity which are laid upon us by the evil spirit to our destruction. Pray ye with me thus:',
          p='Allmechtiger, ewiger gott, ein könig himmels und der Erden, ein trost aller betriebten und trawrigen hertzen, ein sterckhe der Schwachen, laß für dein angesicht durch unsern herren Jesum Christum komen die bit aller menschen, die in bekümmernus und anfechtung zu dir seufftzen und schreyen, uf das menigklich merckh deine hilff und beistand in zeit der Noth umb deines heiligen Namens und deiner grossen Barmhertzigkait willen. Amen.',
          p_en='Almighty, everlasting God, a King of heaven and of earth, a comfort of all troubled and sorrowful hearts, a strength of the weak: let come before thy face, through our Lord Jesus Christ, the prayer of all men that sigh and cry unto thee in trouble and temptation, that every man may mark thy help and succour in time of need, for thy holy name’s sake and thy great mercy’s sake. Amen.'),
        P('peace',
          r='Pro Pace.', r_en='For peace.',
          b='Lassend uns bitten umb Christlichen friden unsers hertzens und gewissens, uff das wir vor unserem herren gott frölich wider die Sünde, todt, Teuffel und hell bestehn megen. Beten mit mir also:',
          b_en='Let us pray for Christian peace of our heart and conscience, that we may stand joyfully before the Lord our God against sin, death, devil and hell. Pray ye with me thus:',
          p='Allmechtiger, ewiger gott, ein könig himels und der Erden, durch welches gaist alle ding regiert, durch welches fürsehung alle ding geordnet werden, ein gott des fridens, wir biten dich durch unsern herren Jesum Christum, du wollest uns unser Sünd verzeihen und uns mit dem gaist des fridens salben, auf das wir in forcht und zütern dir allein dienen zu lob und preis deines heiligen Namens. Amen.',
          p_en='Almighty, everlasting God, a King of heaven and of earth, by whose Spirit all things are governed, by whose providence all things are ordered, a God of peace: we beseech thee through our Lord Jesus Christ that thou wouldest pardon us our sins and anoint us with the spirit of peace, that we may serve thee alone in fear and trembling, to the praise and glory of thy holy name. Amen.'),
        P('enemies',
          r='Pro Inimicis nostris.', r_en='For our enemies.',
          b='Lassent uns auch bitten für unsere feind, das sy gott zu irer selbs aignen Erkantnus füren und von irem unrechten und verbiterten hertzen und gemüt gnedigklich abweisen wolle. Betet mit mir also:',
          b_en='Let us also pray for our enemies, that God would lead them to the knowledge of themselves and graciously turn them from their unrighteous and embittered heart and mind. Pray ye with me thus:',
          p='Allmechtiger, ewiger gott, der du uns bevolchen hast, das wir unsere feind lieben, denen, die uns belaidigen, guts thon und für unsere verfolger biten sollen, wir ruffen ernstlich zu dir, du wollest unsere feind gnedigklich haim suchen und inen ein fridsam, rain, hailig hertz und gemüett verleihen, das sy einheligklich mit der gantzen Christenhait glauben und leben, durch unsern herren Jesum Christum. Amen.',
          p_en='Almighty, everlasting God, who hast commanded us that we should love our enemies, do good to them that hurt us, and pray for our persecutors: we call earnestly upon thee that thou wouldest graciously visit our enemies and vouchsafe them a peaceable, pure and holy heart and mind, that they may believe and live with one accord with the whole of Christendom; through our Lord Jesus Christ. Amen.'),
        P('childbirth',
          r='Pro Praegnantibus.', r_en='For women with child.',
          b='Lasset uns auch biten für alle Schwangere frawen, das inen gott welle geben sterckhe und Krafft, uf das sy gnedigklich von kinds banden erlest und mit frölichem anblickh begabet werden. Beten mit mir also:',
          b_en='Let us also pray for all women with child, that God would give them strength and power, that they may be graciously delivered from the bonds of childbirth and be gifted with a joyful sight. Pray ye with me thus:',
          p='Allmechtiger, ewiger gott und vatter, der du man und weib genedigklich gesegnet hast, also sprechende: Seit fruchtbar und mehret euch, und dem weib iren kumer im geberen zu einem heiligen Creutz durch unsern herrn Jesum Christum gemacht hast, wir biten dich, herre got, du wollest die frucht irer leib, deine eigne werckh, erhalten und sy under dem Creutz der geburt nit verderben lassen, sonder gnedigklich und mit freud entbinden, sprecht von Hertzen: Amen.',
          p_en='Almighty, everlasting God and Father, who hast graciously blessed man and woman, saying: Be fruitful and multiply; and hast made unto the woman her sorrow in bearing an holy cross through our Lord Jesus Christ: we beseech thee, Lord God, that thou wouldest keep the fruit of their womb, thine own work, and not let them perish under the cross of birth, but graciously and with joy deliver them. Say ye from the heart: Amen.'),
        P('fruits-of-earth',
          r='Pro Frugibus terrae.', r_en='For the fruits of the earth.',
          b='Endtlich lasset uns auch biten für die samen uf dem feld und liebe Frucht der Erden, das sy der allmechtig gott gnedig segnen, vor ungewitter behüetten und wolgeratten lasse. Beten mit mir also:',
          b_en='Finally, let us also pray for the seed upon the field and the dear fruit of the earth, that almighty God would graciously bless it, keep it from tempest, and make it to prosper well. Pray ye with me thus:',
          p='O Herr, allmechtiger gott, der du durch dein wort alle ding erschaffen und gesegnet hast, wir biten dich, du wollest den himmlischen samen, dein ewiges wort, unsern herren Jesum Christum offenbaren und in unsere hertzen pflantzen, dardurch an uns gesegnet werde mit fruchtbarer wachsung und göttlichem gebrauch alles, was uns zur leiblichen notturfft dint, sprecht von hertzen: Amen.',
          p_en='O Lord, almighty God, who by thy word hast created and blessed all things: we beseech thee that thou wouldest reveal the heavenly seed, thine eternal Word, our Lord Jesus Christ, and plant him in our hearts, whereby all that serveth us for our bodily need may be blessed unto us with fruitful increase and godly use. Say ye from the heart: Amen.'),
        P('lords-prayer',
          r='Nach gesprochnem gebeten thuend pfarrherr volgende wort hinzu:',
          r_en='After the prayers are said, the pastor addeth the following words:',
          b='Fasset dise bit zu hertzen im glauben und beschliest mit dem herrlichen, schen gebet Jesu Christi: Unser vatter, der du bist.',
          b_en='Take these petitions to heart in faith, and conclude with the glorious, fair prayer of Jesus Christ: Our Father, who art.'),
        P('blessing', sub='conclusion',
          r='Appendix.', r_en='Appendix.',
          p='Glaubt, so seyt ir erhert im himmel, wie uns der Herr zugesagt hat: Was ir bitet in ewerm gebet, glaubt nur, das irs Empfangen werdet, so wirts euch werden. Hierbey gesegne und behüte euch der herr, er erzaige euch sein angesicht und erbarme sich über euch und gebe euch seinen ewigen friden. Amen.',
          p_en='Believe, and ye are heard in heaven, as the Lord hath promised us: Whatsoever ye ask in your prayer, only believe that ye shall receive it, and it shall be done unto you. Herewith the Lord bless you and keep you; he show you his face and have mercy upon you, and give you his everlasting peace. Amen.'),
    ]))
