"""Other Lutheran general prayers: biddings addressed to the people (the
"Vermahnung zum Gebet" type, closing with the Our Father) and continuous
prayers that do not descend from the Brenz or Württemberg forms."""
from gp import P

W = []

# ---------------------------------------------------------------------------
W.append(dict(
    key='hanau_lichtenberg_1573', doc=1364, year=1573,
    order='Hanau-Lichtenberg, Kirchenordnung (Graf Philipp IV.)',
    territory='County of Hanau-Lichtenberg (Alsace)',
    citation='Sehling 20/2, Hanau-Lichtenberg Nr. 6, pp. 52–53',
    family='C. Bidding exhortation (Strasbourg type)', form='bidding exhortation + Lord’s Prayer',
    tradition='Lutheran',
    position='After the sermon; then a psalm is sung by school and congregation, followed by a collect and the blessing. The pastor is to refer to the sermon just preached and to present needs (war, plague, dearth) in the common prayer.',
    heading='Nach der Predig geschehe das gemein Gebet auff folgende weiß',
    heading_en='After the sermon let the common prayer be made on this wise',
    notes='The Württemberg 1553 collects printed later in the order (XII. Collecten oder Gebet, pp. 72–78, without their biddings) are a collect bank and are not entered here.',
    petitions=[
        P('exhortation',
          r='Nach der Predig geschehe das gemein Gebet auff folgende weiß:',
          r_en='After the sermon let the common prayer be made on this wise:',
          b='Lieben freund, Dieweil wir beyeinander versamlet sein und Gottes wort gehöret haben, so wöllen wir alle not der gantzen Christenheit unserm Herrgott fürtragen, ihne bitten, er wöll uns gnedig und barmhertzig sein, alles geben, was uns nutz und not ist, zur leibes notturfft und zur seelen seligkeit:',
          b_en='Dear friends, forasmuch as we are gathered together and have heard God’s word, we will lay all the need of the whole of Christendom before our Lord God, and pray him that he would be gracious and merciful unto us, and give all that is profitable and needful for us, for the necessity of the body and for the salvation of the soul:'),
        P('word', sub='persecuted; errant; church',
          b='Am ersten so bittet für das Geistlich, das unser lieber Herrgott uns sein heiligs wort wölle lassen predigen und gnad verleihen, das wir solches gerne hören, mit dem hertzen glauben und unser leben darnach richten, auch alle die jenigen, so von solchs Worts wegen in jamer, elend und widerwertigkeit stecken, trösten, stercken und auß allem jamer und elend erretten. Er wölle auch alle, so noch in finsternuß, irrthumb und abgötterey stecken, gnediglich durch sein Wort und Heiligen Geist erleuchten und zu erkantnuß der warheit bringen, auff daß sie mit uns und wir mit ihnen mögen selig werden.',
          b_en='First, pray ye for the spiritual estate: that our dear Lord God would let his holy word be preached unto us, and vouchsafe grace that we may gladly hear the same, believe it with the heart, and order our life thereafter; and that he would comfort, strengthen, and deliver out of all misery and woe all those that for the sake of this Word are in misery, woe and adversity. That he would also graciously enlighten by his Word and Holy Spirit all that are yet in darkness, error and idolatry, and bring them to the knowledge of the truth, that they with us and we with them may be saved.'),
        P('civil-authority', sub='peace',
          b='Zum andern bittet für das Weltlich Regiment: Erstlich für das Haupt, die Römische Kayserliche Majestat, unsern aller gnedigsten Herren, Darnach für die Glieder, alß Churfürsten, Fürsten und Herren der gantzen Christenheit, In sonderheit aber für unsere gnedige Herren, Frawe und Frewlein von Hanaw, für irer Gnaden Räthe, Amptleut, Diener und die gantze Herrschafft, für ein ersam Gericht und Gemeine alhie, auch die umbligende Nachpaurschafft. Der Allmechtige Gott verleihe der Oberkeit seinen Heiligen Geist und weißheit, das sie Christlich und wol regieren, die Unterthanen in gemeinem friden erhalten und bewaren.',
          b_en='Secondly, pray ye for the temporal government: first for the head, his Roman Imperial Majesty, our most gracious lord; then for the members, as the Electors, princes and lords of all Christendom; but especially for our gracious lords, lady and damsels of Hanau, for their Graces’ counsellors, officers, servants and the whole lordship, for a worshipful court and commune here, and also the neighbourhood round about. Almighty God vouchsafe unto the magistrates his Holy Spirit and wisdom, that they may rule in Christian wise and well, and keep and preserve the subjects in common peace.'),
        P('estates', sub='marriage',
          b='Letzlich bittet auch für den Ehelichen stand, der Allmechtige Gott verleihe allen Eheleuten seinen Heiligen Geist, das sie Christlich, fridlich und eintrechtiglich beieinander leben, ihre Kinder und Gesind zu Gottes forcht, auch ehr und tugent mögen aufferziehen.',
          b_en='Lastly, pray ye also for the estate of matrimony: Almighty God vouchsafe unto all married folk his Holy Spirit, that they may live together in Christian wise, peaceably and in concord, and may bring up their children and household in the fear of God, and also in honour and virtue.'),
        P('fruits-of-earth',
          b='Bittet für die frucht des Feldes, umb ein seliges Wetter und umb alles, so uns von nöten ist.',
          b_en='Pray ye for the fruit of the field, for seasonable weather, and for all that is needful unto us.'),
        P('afflicted', sub='childbirth',
          b='Kinder und Krancken wölle unser Herrgott pflegen und warten, Schwangern und Seugerin fröliche frucht und gedeien geben, die gefangnen loß und ledig machen.',
          b_en='May our Lord God tend and keep children and the sick, give unto women with child and them that give suck joyful fruit and increase, and loose and set free the captives.'),
        P('special',
          b='Und ein jeglicher bedenck sein eigene not und kom mit ir für Gott, den himlischen Vater, und zweiffel nicht, er werde uns gnediglich durch Christum erhören. Und sprecht von gantzem hertzen also:',
          b_en='And let every man consider his own need and come with it before God, the heavenly Father, and doubt not that he will graciously hear us through Christ. And say with your whole heart thus:'),
        P('lords-prayer',
          p='Unser Vater, der du bist im Himel, Geheiliget werde dein Nam. Zukom dein Reich. Dein will geschehe auff Erden wie im Himel. Unser täglich Brot gib uns heut. Und vergib uns unser Schuld, alß wir vergeben unseren Schuldigern. Füre uns nit in versuchung, Sondern erlöse uns von dem bösen. Dann dein ist das Reich und die Krafft und die Herrligkeit von ewigkeit zu ewigkeit, Amen.',
          p_en='Our Father, which art in heaven, Hallowed be thy name. Thy kingdom come. Thy will be done in earth, as it is in heaven. Give us this day our daily bread. And forgive us our debts, as we forgive our debtors. And lead us not into temptation, but deliver us from evil: For thine is the kingdom, and the power, and the glory, from everlasting to everlasting. Amen.',
          note='With the doxology (Strasbourg use).'),
    ]))

# ---------------------------------------------------------------------------
# Family D: the Nürnberg-type "Vermahnung zum Gebet für alle Stände" -- a
# bidding exhortation in which the preacher names the intentions one after
# another ("So last uns nu erstlich bedenken die not der ganzen christenheit
# ... Darnach last uns auch bitten fur das zeitliche leben ..."), closing with
# the Our Father.  Veit Dietrich's Agendbüchlein (Nürnberg 1545) prescribes a
# "vermanung zum gebet für alle stend sambt dem Vater unser" in this place.
W.append(dict(
    key='henneberg_1582', doc=1247, year=1582,
    order='Henneberg, Kirchenordnung (Graf Georg Ernst)',
    territory='County of Henneberg',
    citation='Sehling 2, Henneberg Nr. 3, p. 308',
    family='D. Nürnberg-type Vermahnung zum Gebet', form='bidding exhortation + Lord’s Prayer',
    tradition='Lutheran',
    position='Sunday morning, after the sermon from the pulpit (“das volk zum gebet, fur alle stende und not der christlichen kirchen … abermals ermanen”); then the Our Father and the apostolic blessing; the Supper follows.',
    heading='Forma des gemeinen gebets',
    heading_en='Form of the common prayer',
    notes='Sehling prints this order under Henneberg 1555, but the text is Georg Ernst’s Kirchenordnung of 1582 (running heads). The afternoon service has a shorter form after the Württemberg short prayer (“Geliebten in Christo, weil wir alle glieder eines leibs sind … Erstlich … Zum sechsten”), and weekday morning prayer a thanksgiving form; neither is entered here.',
    petitions=[
        P('exhortation',
          r='Nach der predigt sol der kirchendiener das volk zum gebet, fur alle stende und not der christlichen kirchen vermittelst nachfolgender form mit vleis abermals ermanen. ¶ Forma des gemeinen gebets.',
          r_en='After the sermon the minister shall again diligently exhort the people to prayer for all estates and the need of the Christian Church by means of the following form. ¶ Form of the common prayer.',
          b='Geliebten im herrn Christo, weil wir im namen unsers herren Christi jetzt alhie versamlet sind, göttlichen befehl und gebot haben, wir sollen beten, darzu verheissung, was wir im namen Jesu Christi bitten, das es unser gnediger vater im himel uns gern geben wolle.',
          b_en='Beloved in the Lord Christ, forasmuch as we are now here gathered together in the name of our Lord Christ, and have God’s commandment and bidding that we should pray, and moreover the promise that whatsoever we ask in the name of Jesus Christ, our gracious Father in heaven will gladly give it us:'),
        P('church', sub='word; errant',
          b='So last uns nu erstlich bedenken die not der ganzen christenheit und bitten, das uns gott sein wort rein und lauter erhalten wolle wider alle rotten und ketzereien und seine arme christenheit gnediglich behüten widers furnemen des teufels und der tyrannen.',
          b_en='Let us now first consider the need of all Christendom, and pray that God would keep his word pure and clear unto us against all sects and heresies, and graciously guard his poor Christendom against the devices of the devil and of the tyrants.'),
        P('peace', sub='fruits-of-earth; calamities; turks; enemies',
          b='Darnach last uns auch bitten fur das zeitliche leben, das uns gott mit gnedigem fried und seligem wetter begnaden, fur theurung und pestilenz behüten und sonderlich dem Türken und allen feinden seines worts und kirchen wehren wolle, umb seines heiligen namens willen.',
          b_en='Thereafter let us also pray for this temporal life, that God would bless us with gracious peace and seasonable weather, keep us from dearth and pestilence, and especially withstand the Turk and all the enemies of his word and Church, for his holy name’s sake.'),
        P('civil-authority',
          b='Bittet auch fur die obrigkeit der ganzen christenheit, das gott ire herzen durch sein wort und geist erleuchten wolle, auf das gottes wort und ehre durch sie gefördert und nicht gehindert, und wir desto mehr frieds bei irem regiment haben mögen. In sonderheit aber bittet fur unsern landsfürsten zu Henneberg, unter welches schutz und schirm uns der liebe gott gesetzt hat, und seiner f. g. gemahl, auch ihrer bederseits f. g. blutsverwandten und sonsten angehörige, das sie gott semptlich in seiner furcht, bei langwiriger guter gesundheit erhalten und an leib und seel begnaden, auch alle seiner f. g. räte und amptleute regieren wolle, auf das gottes ehre und alle erbarkeit gefördert, allem ergernus gewehret, und die gemeine gottes wol und friedlich regieret werde.',
          b_en='Pray ye also for the magistrates of all Christendom, that God would enlighten their hearts by his word and Spirit, that God’s word and honour may be furthered and not hindered by them, and that we may have the more peace under their government. But especially pray ye for our prince of the land at Henneberg, under whose protection and defence the dear God hath set us, and for his princely Grace’s consort, and the kinsfolk by blood and others belonging to their princely Graces on both sides, that God would keep them all together in his fear in long and good health and bless them in body and soul, and also govern all his princely Grace’s counsellors and officers, that God’s honour and all honesty may be furthered, all offence prevented, and the congregation of God well and peaceably governed.'),
        P('estates', sub='errant; enemies',
          b='Darnach bittet fur alle fürsten und stende, so bishero gottes wort bekennet haben, das sie gott in solchem erkentnis gnedig erhalten und andere mehr herzu bringen wolle, widerumb aber die es mutwillig verfolgt haben und noch nicht ablassen, in ihrem bösen furnemen hindern und seine kirche gnediglich wider sie schützen wolle.',
          b_en='Thereafter pray ye for all princes and estates which hitherto have confessed God’s word, that God would graciously keep them in such knowledge and bring yet more thereto; and again, that he would hinder in their evil purpose them that have wilfully persecuted it and yet cease not, and graciously defend his Church against them.',
          note='The “Stände” here are the Protestant estates of the Empire.'),
        P('persecuted',
          b='Sonderlich auch, weil hin und wider in andern landen viel armer christen umb des worts willen verfolgt, verjagt, gefenglich eingezogen, elendiglich gemartert und erwürgt werden, sind wir schuldig fur sie zu bitten, das gott durch seinen heiligen geist ire herzen trösten und sterken, in bekentnis rechter lehr und glaubens sie fest erhalten, und inen an leib und seel seliglich helfen wolle.',
          b_en='Especially also, forasmuch as here and there in other lands many poor Christians are for the word’s sake persecuted, driven out, cast into prison, miserably tormented and slain, we are bound to pray for them, that God would comfort and strengthen their hearts by his Holy Spirit, keep them steadfast in the confession of right doctrine and faith, and help them blessedly in body and soul.'),
        P('afflicted', sub='childbirth',
          b='Bittet auch fur alle betrübte, angefochtene, kranke, dürftige und notleidende christen, unsere arme brüder und schwestern, hie und in der ganzen welt, fur alle schwangere, sechswöchnerin und seugende, das sie gott mit gnaden erledigen, entbinden und erhalten wolle.',
          b_en='Pray ye also for all sorrowful, tempted, sick, needy and distressed Christians, our poor brethren and sisters, here and in the whole world; for all women with child, women in childbed, and them that give suck, that God would graciously deliver them, bring them safely to bed, and preserve them.'),
        P('errant',
          b='Letztlich bittet auch fur die arme leute, so noch unter dem babstumb in irrtumb und bösem gewissen ligen und die selige erkentnis des worts nicht haben, wie wir, das sie gott zu solchem licht seiner gnaden auch füren und sie mit uns durch rechten glauben an Christum wolle ewig selig machen.',
          b_en='Lastly pray ye also for the poor people that yet lie under the papacy in error and an evil conscience, and have not the blessed knowledge of the word as we have, that God would lead them also to such light of his grace and make them with us eternally blessed through right faith in Christ.'),
        P('special',
          b='In sonderheit wird ein gemeine vorbitte von euch begeret, fur N.',
          b_en='In particular a common intercession is desired of you for N.'),
        P('lords-prayer',
          b='Solch alles zu erwerben, betet mit andacht das heilige vater unser.',
          b_en='To obtain all this, pray ye with devotion the holy Our Father.'),
        P('blessing',
          r='Nach solcher vermanung und dem gesprochenen vater unser, sol der prediger nachfolgenden segen uber das volk sprechen:',
          r_en='After such exhortation and the Our Father said, the preacher shall speak the following blessing over the people:',
          p='Die gnade unsers herren Jesu Christi, die liebe gottes und die gemeinschaft des heiligen geistes sei mit euch allen, amen.',
          p_en='The grace of our Lord Jesus Christ, the love of God, and the communion of the Holy Ghost be with you all. Amen.'),
    ]))

W.append(dict(
    key='erbach_1560', doc=2316, year=1560,
    order='Erbach, Kirchenordnung (Graf Georg)',
    territory='County of Erbach',
    citation='Sehling 9, IV/Erbach Nr. 6 (2. Erbacher Kirchenordnung 1560), pp. 428–429',
    family='D. Nürnberg-type Vermahnung zum Gebet', form='bidding exhortation + Lord’s Prayer',
    tradition='Lutheran',
    position='After the sermon, following the open confession and absolution; special prayers may be added in time of war, plague or dearth, and a prayer for the sick follows.',
    heading='Das gemein gebet',
    heading_en='The common prayer',
    notes='Base text 1560 (Sehling’s edition; the corpus document is labelled 1587). The 1558 draft (apparatus) is closer to Henneberg: “wider alle rotten und ketzereyen … und der tyrannen”, and closes with the apostolic blessing.',
    petitions=[
        P('church', sub='exhortation; word; errant',
          r='Das gemein gebet:', r_en='The common prayer:',
          b='Dieweil wir im nahmen unsers Herrn Christi jetzundt versamlet sein unnd befehl haben, wir söllen Bitten, auch verheissung, was wir im namen Jhesu Christi bitten werden, daß es unser gnediger Vatter im Himel gern geben wölle, So last uns erstlich bedencken die noth der gantzen Christenheit und bitten, daß Gott uns sein wort rein und lauter erhalten, auch die jenigen, so noch nit zu rechter erkentniß kommen, herzu führen und seine arme Christenheit gnediglich behüten wölle wider alles fürnehmen des Teuffels.',
          b_en='Forasmuch as we are now gathered together in the name of our Lord Christ, and have commandment that we should pray, and also the promise that whatsoever we shall ask in the name of Jesus Christ, our gracious Father in heaven will gladly give it: let us first consider the need of all Christendom, and pray that God would keep his word pure and clear unto us, and also bring thereto them that are not yet come to the right knowledge, and graciously guard his poor Christendom against all the devices of the devil.'),
        P('peace', sub='fruits-of-earth; calamities',
          b='Darnach last uns auch bitten für dieses zeitlich leben, daß uns Gott mit gnedigem fride und seligem Wetter begnaden, vor Theurung, Kriege unnd Pestilentz behüten wölle.',
          b_en='Thereafter let us also pray for this temporal life, that God would bless us with gracious peace and seasonable weather, and keep us from dearth, war and pestilence.'),
        P('civil-authority',
          b='Bittet auch für alle Oberkeit, Keyser, König, Fürsten und Herrn, In sonderheit für unsere gnedige Herrschafft allhier, daß Gott ire hertzen durch seinen Geist und wort erleuchten wölle, Auff das Gottes wort und ehre durch sie gefordert unnd nicht verhindert werde, auch wir dester mehr fridens bey ihrem Regiment haben mögen.',
          b_en='Pray ye also for all magistrates, Emperor, kings, princes and lords, especially for our gracious lordship here, that God would enlighten their hearts by his Spirit and word, that God’s word and honour may be furthered and not hindered by them, and that we also may have the more peace under their government.'),
        P('persecuted',
          b='Dieweil auch hin und wider inn allen landen viel armer Christen umb deß wort Gottes und der gerechtigkeit willen verfolgt, verjagt, gefencklich eingezogen, elendiglichen gemartert und erwürgt werden, sind wir schuldig, für sie Gott zubitten, das er durch seinen heiligen Geist ire hertzen trösten und stercken, im bekentniß sie fest erhalten und seliglichen ihnen helffen wölle an leib und sehle.',
          b_en='Forasmuch also as here and there in all lands many poor Christians are for the word of God and for righteousness’ sake persecuted, driven out, cast into prison, miserably tormented and slain, we are bound to pray God for them, that he would comfort and strengthen their hearts by his Holy Spirit, keep them steadfast in the confession, and help them blessedly in body and soul.'),
        P('afflicted',
          b='Darnach last uns auch bitten für unsere arme Brüder und schwestern, hie unnd inn der gantzen Welt, da entweder schwere kranckheit odder grosse anfechtung sind, das sie Gott mit gnaden erledigen wölle.',
          b_en='Thereafter let us also pray for our poor brethren and sisters, here and in the whole world, where there is either grievous sickness or great temptation, that God would graciously deliver them.'),
        P('childbirth', sub='enemies; errant',
          b='Bittet auch für alle schwangere frawen, das sie von kinds banden gnediglich erlöst werden, für diese unnd alle andere nodturfft der gantzen Christenheit, auch für unsere feinde, das sie möchten bekert unnd zu rechter erkäntniß unsers Herrn Jhesu Christi gebracht werden.',
          b_en='Pray ye also for all women with child, that they may be graciously delivered from the bonds of childbirth; for these and all other necessities of the whole of Christendom; and also for our enemies, that they may be converted and brought to the right knowledge of our Lord Jesus Christ.'),
        P('estates',
          b='Der Allmechtige Gott wölle seine gaben in allen stenden, warzu ein jeglicher beruffen ist, zu seinem preis und unserer seeligkeit segnen und fertigen durch Jhesum Christum, unsern Herrn, Amen.',
          b_en='Almighty God bless and prosper his gifts in all estates, whereunto every one is called, to his praise and our salvation; through Jesus Christ our Lord. Amen.'),
        P('lords-prayer',
          b='Lasset uns mit andacht sprechen das Gebet unsers Herrn Jhesu Christi: Unser Vatter, der du bist im Himmel etc.',
          b_en='Let us say with devotion the prayer of our Lord Jesus Christ: Our Father, which art in heaven, etc.'),
        P('special',
          r='So mögen auch jeder zeit aus zufallender not, als in kriegen, sterben unnd thewrung, sonderliche gebet, so darzu dienlich, dieselbige zeit hinzu gethan unnd gebraucht werden.',
          r_en='So also at any time, by reason of need befalling, as in wars, pestilence and dearth, special prayers serving thereto may for that time be added and used.'),
    ]))

W.append(dict(
    key='solms_laubach_1576', doc=2311, year=1576,
    order='Solms-Laubach, Kirchenordnung [1576–1580]',
    territory='County of Solms-Laubach',
    citation='Sehling 9, III/Solms Nr. 10, pp. 360–361',
    family='D. Nürnberg-type Vermahnung zum Gebet', form='bidding exhortation + Lord’s Prayer',
    tradition='Lutheran',
    position='At the end of the sermon, after a recapitulation and the publishing of banns; then (if no communicants) a psalm, a collect and the Aaronic blessing.',
    heading='Dancksagung und gemein gebett',
    heading_en='Thanksgiving and common prayer',
    notes='Undated manuscript order, 1576–1580 (the corpus document is labelled 1603). Built on the Erbach text, with a thanksgiving for creation, redemption and sanctification, a fuller petition for the ministry of the Word, and the household estate from Hanau-Lichtenberg.',
    petitions=[
        P('thanksgiving', sub='exhortation; estates',
          r='Zu ende der predigt sollen die verhandlete stuck kurtzlich repetirt und alßdan, wo personen, so sich miteinander ehelich versprochen, angeben, proclamirt werden, daruf dancksagung und gebett volgen, also: ¶ Dancksagung und gemein gebett',
          r_en='At the end of the sermon the matters handled shall be briefly repeated, and then, if there be persons that have given in their names as betrothed one to another, they shall be proclaimed; whereupon thanksgiving and prayer shall follow, thus: ¶ Thanksgiving and common prayer',
          b='Dieweil wir nun Gottes wortt haben angehort und schuldig seint, Gott dem allmechtigen fur alle seine wollthatt, so er uns täglich erzeigt, zudancken, so wollen wir ime dancksagen vor das werck der erschöpfung, erlösung und heiligung, das er auch noch fur und fur biß an den jungsten tag in seiner erkantnus uns erhelt, zum geistlichen, weltlichen und haußstandt seine gnad verleyhet und uns segenet, seint auch schuldig, umb erhaltung derselben stende und was darzu gehörig, zubitten, haben göttliche verheissung und gewisse zusage, was wir im nhamen Jhesu Christi bitten werden, das unß dasselbige der vatter im hiemel geben wölle.',
          b_en='Forasmuch now as we have heard God’s word, and are bound to give thanks unto God Almighty for all his benefits which he daily showeth us, we will give him thanks for the work of creation, redemption and sanctification; that he still keepeth us evermore in his knowledge until the last day, and vouchsafeth his grace to the spiritual, temporal and household estate, and blesseth us. We are bound also to pray for the preservation of the same estates and what pertaineth thereto; and we have God’s promise and sure assurance that whatsoever we shall ask in the name of Jesus Christ, the Father in heaven will give it us.'),
        P('church', sub='ministers; word; errant',
          b='So lasset uns erstlich bedencken die noth der gantzen christenheit und bitten, das Gott uns sein wortt rein und lauter erhalten, diejenige, so noch nit zu rechter erkantnus kommen, herzufhüren und seine arme christenheit gnediglich behüten wölle wider alles fürnemen des teuffels, wolle uns derwegen getrewe lehrer und prediger seines heiligen heilsamen worts iderzeit zuschicken, dieselben in seiner warheit und christenlichem leben erhalten, auch gnediglich verleihen, das wir Gottes wortt mit rechter andacht mögen hören, dasselbige liebhaben, bewegen, behalten und unser leben darnach anstellen, alles zu lob und preiß seines gottlichen nhamens und unser seelen seligkheit, wolle auch stewern und wehren allen denjenigen, so uns solches liechts der warheit zuberauben understehen.',
          b_en='Let us therefore first consider the need of all Christendom, and pray that God would keep his word pure and clear unto us, bring thereto them that are not yet come to the right knowledge, and graciously guard his poor Christendom against all the devices of the devil; that he would therefore at all times send us faithful teachers and preachers of his holy, wholesome word, keep them in his truth and in Christian life, and also graciously grant that we may hear God’s word with right devotion, love it, ponder it, keep it, and order our life thereafter, all to the praise and glory of his divine name and the salvation of our souls; and that he would also restrain and withstand all those that undertake to rob us of such light of the truth.'),
        P('peace', sub='fruits-of-earth; calamities',
          b='Zum andern lasset uns auch bitten fur dieses zeitliche leben, das uns Gott mit gnedigem fried und seligem wetter begnaden, vor thewrung, krieg und pestilentz behüten wolle.',
          b_en='Secondly, let us also pray for this temporal life, that God would bless us with gracious peace and seasonable weather, and keep us from dearth, war and pestilence.'),
        P('civil-authority',
          b='Bittet auch fur alle obrigkeit, keiser, könige, fursten und herrn, insonderheit fur unsere gnedige landthern, under welcher schutz und schirm uns Gott der herr gesetzt hat, und fur beide heuser, der graven von Isenburg und Solms, fur irer gnaden ambtleute, räthe und diener, auch eine erbare gemein alhier, das Gott ir hertzen durch seinen heiligen geist und wortt erleuchten und regiren wölle, domit ire gnaden und sie bei der erkanten warheit bestendig mögen pleiben, uf das Gottes wortt und ehre durch sie gefördert und nicht verhindert werde, domit wir under irem regiment ein stilles und fridliches leben mögen fhüren in aller gottseligkeit und erbarkheit.',
          b_en='Pray ye also for all magistrates, Emperor, kings, princes and lords, especially for our gracious lords of the land, under whose protection and defence God the Lord hath set us, and for both houses, of the Counts of Isenburg and of Solms, for their Graces’ officers, counsellors and servants, and also an honourable commune here, that God would enlighten and govern their hearts by his Holy Spirit and word, that their Graces and they may abide steadfast in the truth acknowledged, that God’s word and honour may be furthered and not hindered by them, and that we under their government may lead a quiet and peaceable life in all godliness and honesty.'),
        P('estates', sub='marriage; persecuted',
          b='Zum dritten bittet auch vor das haußregiment und ehelichen standt, das der allmechtig gütig Gott verleihen wölle allen eheleuten seinen heiligen geist, das sie christlich, fridlich und einträchtig beieinander leben, ire kinder und gesinde zu gottesforcht, auch ehre und tugent, mögen uferziehen. Dieweil auch hin und wider in allen landen viel arme christen umb des worts Gottes und der gerechtigkeit willen verfolgt, verjagt, gefengklich ingezogen, elendiglich gemartert und erwürget werden, seint wir schuldig, Gott vor sie zubitten, das er durch seinen heiligen geist ire hertzen trösten und stercken, im bekantnus sie fest erhalten und seliglichen inen helffen wölle an leib und seele.',
          b_en='Thirdly, pray ye also for the government of the household and the estate of matrimony, that the almighty, gracious God would vouchsafe unto all married folk his Holy Spirit, that they may live together in Christian wise, peaceably and in concord, and may bring up their children and household in the fear of God, and also in honour and virtue. Forasmuch also as here and there in all lands many poor Christians are for the word of God and for righteousness’ sake persecuted, driven out, cast into prison, miserably tormented and slain, we are bound to pray God for them, that he would comfort and strengthen their hearts by his Holy Spirit, keep them steadfast in the confession, and help them blessedly in body and soul.'),
        P('afflicted', sub='childbirth; enemies',
          b='Darnach lasset uns auch bitten fur unsere arme brüder und schwestern und in der gantzen weldt, da entweder schwere kranckheiten oder grosse anfechtungen seint, das sie Gott mit gnaden erledigen wölle. Bittet auch für alle schwangere weiber und seugerin, Gott wolle inen fröliche frucht und gedeien geben, das auch unser lieber herr Gott alle unsere feinde wolle bekheren und inen, was sie gegen uns gesündiget, gnediglich vergeben.',
          b_en='Thereafter let us also pray for our poor brethren and sisters, and in the whole world, where there are either grievous sicknesses or great temptations, that God would graciously deliver them. Pray ye also for all women with child and them that give suck, that God would give them joyful fruit and increase; and that our dear Lord God would also convert all our enemies and graciously forgive them what they have sinned against us.'),
        P('special', sub='lords-prayer',
          b='Ein iglicher schliesse seine eigene noth, welche ime am besten bewust, mit in und spreche mit mir also:',
          b_en='Let every one include therein his own need, which is best known unto him, and say with me thus:'),
        P('lords-prayer',
          p='Unser vatter, der du bist in dem hiemel, geheiliget werde dein nhame, zukom dein reich, dein wille geschehe wie in dem hiemel also auch auf erden. Unser taglich brodt gib uns heut und vergib uns unsere schuldt, als wir vergeben unsern schuldigern. Und fhüre uns nicht in versuchung, sondern erlöse uns von dem bösen, dan dein ist das reich und die kraft und die herligkeit von ewigkeit zu ewigkeit, amen.',
          p_en='Our Father, which art in heaven, hallowed be thy name, thy kingdom come, thy will be done, as in heaven, so also upon earth. Give us this day our daily bread, and forgive us our debt, as we forgive our debtors. And lead us not into temptation, but deliver us from evil: for thine is the kingdom, and the power, and the glory, from everlasting to everlasting. Amen.'),
    ]))
