"""Reformed general prayers (Heidelberg/Kurpfalz 1563 and its descendants;
Calvin/Poullain/à Lasco/Micron types).  The Kurpfalz 1563 Sunday prayer
("Almechtiger Gott, schöpfer himmels und der erden, wir dancken dir") is a
thanksgiving-and-intercession prayer after Genevan models; its alternative
("Oder also") is a paraphrase of the Lord's Prayer drawn from Geneva 1563
and Heidelberg Catechism qq. 122-127."""
from gp import P

W = []

W.append(dict(
    key='kurpfalz_1563', doc=504, year=1563,
    order='Kurpfalz, Kirchenordnung (Friedrich III.)',
    territory='Electoral Palatinate',
    citation='Sehling 14, Regierungszeit Friedrichs III. Nr. 60 (KO 1563), pp. 389–390',
    family='R1. Heidelberg 1563 prayer', form='confession + absolution + continuous prayer + Lord’s Prayer',
    tradition='Reformed',
    position='Sunday morning after the sermon: exhortation to confession, confession, absolution (with retention), then the prayer and the Our Father; a psalm and the Aaronic blessing follow. The prayer before the sermon is a separate confession of sins.',
    heading='Gebet am Sontag nach der predigt',
    heading_en='Prayer on Sunday after the sermon',
    notes='The corpus document carries the 1585 edition in the apparatus (Johann Casimir as administrator). The afternoon service has a short prayer after Zürich 1535 (“Herr, allmechtiger Gott, laß deine heilige ehr …”) or, “oder also”, the Württemberg short form; these are not entered here.',
    petitions=[
        P('confession',
          r='Am Sontag nach der morgenpredig soll der kirchendiener sprechen:', r_en='On Sunday after the morning sermon the minister shall say:',
          b='Ir geliebten in dem herrn, Dieweil wir in den geboten Gottes gleich als in einem spiegel sehen, wie groß und vielfältig unser sünden sind, durch welche wir zeitliche und ewige straf verdienen, so laßt uns diesselbige von hertzen unserm getreuen vater bekennen, sprecht derhalben mit mir also:',
          b_en='Dearly beloved in the Lord, forasmuch as we see in the commandments of God as in a glass how great and manifold our sins are, whereby we deserve temporal and eternal punishment, let us confess the same from the heart unto our faithful Father; say therefore with me thus:',
          p='Ich armer sünder bekenn für dir, meinem Gott und schöpfer, daß ich leider schwerlich und mannigfältig wider dich gesündiget hab, nit allein mit eusserlichen groben sünden, sonder vilmehr mit innerlicher angeborner blindheyt, unglauben, zweifelung, kleinmütigkeyt, ungedult, hoffart, bösem geitz, heimlichen neid, haß und mißvergunst, auch andern bösen dücken, wie du, mein herr und Gott, an mir erkennest und ich leider nit gnugsam erkennen kan, die reuen mich und sind mir leid und beger von hertzen gnad, durch deinen lieben son Jesum Christum.',
          p_en='I, poor sinner, confess before thee, my God and Creator, that I, alas, have sinned grievously and manifoldly against thee, not only with outward gross sins, but much more with inward, inborn blindness, unbelief, doubting, faintheartedness, impatience, pride, evil covetousness, secret envy, hatred and grudging, and other evil wiles, as thou, my Lord and God, knowest in me, and I, alas, cannot sufficiently know; they repent me and grieve me, and I desire grace from my heart, through thy dear Son Jesus Christ.'),
        P('confession', sub='absolution',
          r='Darauf soll er den gläubigen die vergebung der sünden und den unbußfertigen das urtheil Gottes verkündigen und also sprechen:',
          r_en='Thereupon he shall declare unto the faithful the forgiveness of sins, and unto the impenitent the judgement of God, and say thus:',
          p='Nun höret an den gewissen trost der gnaden Gottes, welche er allen gläubigen in seinem evangelio verheisset. Also spricht der herr Christus Johan. am 3.: Also hat Gott die welt geliebt, daß er seinen eingebornen son gab, auf daß alle, die an in glauben, nicht verlorn werden, sonder das ewig leben haben. Sovil nun euer sein, die an ihnen selbst und an iren sünden ein mißfallen haben und vertrauen, daß sie inen durch den verdienst Jesu Christi allein gantz und gar vergeben sind, und den fürsatz haben, je lenger je mehr von sünden abzustehen und dem herrn in warer heiligkeyt und gerechtigkeyt zu dienen, denselbigen (dieweil sie glauben in den son des lebendigen Gottes) verkündige ich aus dem befelch Gottes, daß sie von allen iren sünden (wie er in seinem heiligen evangelio verheißt) in dem himmel entbunden seind durch die volkommene genugthuung des allerheiligisten leidens und sterbens unsers herrn Jesu Christi, Amen. Soviel aber under euch seind, die noch einen gefallen haben an iren sünden und schanden oder in sünden wider ir gewissen beharren, denselbigen verkündige ich auß befelch Gottes, daß der zorn und das urtheil Gottes uber inen bleibt und daß alle ire sünden im himmel gehalten seind und sie von der ewigen verdamnuß nit entbunden mögen werden, biß daß sie sich bekehren.',
          p_en='Hear now the sure comfort of the grace of God, which he promiseth in his Gospel to all believers. Thus saith the Lord Christ in John the third: God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life. As many of you therefore as are displeased with yourselves and your sins, and trust that they are wholly and altogether forgiven them through the merit of Jesus Christ alone, and have the purpose more and more to cease from sins and to serve the Lord in true holiness and righteousness, unto them (forasmuch as they believe in the Son of the living God) I declare by the commandment of God that they are loosed in heaven from all their sins (as he promiseth in his holy Gospel) through the perfect satisfaction of the most holy suffering and death of our Lord Jesus Christ. Amen. But as many among you as yet have pleasure in their sins and shame, or continue in sins against their conscience, unto them I declare by the commandment of God that the wrath and judgement of God abideth upon them, and that all their sins are retained in heaven, and that they cannot be loosed from eternal damnation until they be converted.'),
        P('thanksgiving', sub='exhortation',
          b='Nachdem wir nun nicht zweifelen, wir und unser gebet seien durch das leiden Jesu Christi geheiliget und Gott angenem, so laßt uns in von hertzen anrüfen und also sprechen:',
          b_en='Forasmuch now as we doubt not that we and our prayer are sanctified through the suffering of Jesus Christ and acceptable unto God, let us call upon him from the heart and say thus:',
          r='Gebet am Sontag nach der predigt.', r_en='Prayer on Sunday after the sermon.',
          p='Almechtiger Gott, schöpfer himmels und der erden, wir dancken dir auß grund unsers hertzens, daß du uns erschaffen, biß auf disen tag uns und unsere kinder erhalten, gespeiset und erneret hast und noch hinfort erhalten und regieren wilst. Insonderheyt aber dancken wir dir, daß du deinen son Jesum Christum, den du im paradeiß verheissen hast, uns hast zu erkennen geben und unsere sünden durch sein bitter leiden und sterben uns verzihen.',
          p_en='Almighty God, Creator of heaven and of earth, we give thee thanks from the ground of our heart that thou hast created us, and unto this day hast preserved, fed and nourished us and our children, and wilt yet henceforth preserve and govern us. But especially we give thee thanks that thou hast given us to know thy Son Jesus Christ, whom thou didst promise in Paradise, and hast forgiven us our sins through his bitter suffering and death.'),
        P('word', sub='congregation',
          p='Und bitten dich, daß du uns zum ebenbildt deines sohns Jesu Christi durch die predig deines worts und kraft deines heiligen geistes erneuern wöllest, auf daß wir mit leib und seel ewig mit dir leben und dich preisen, darzu wir anfenglich erschaffen seind, und wöllest dem satan weren, daß er uns dein heiliges wort nicht auß unsern hertzen reisse, wie er unsern ersten eltern Adam und Even gethon hat.',
          p_en='And we beseech thee that thou wouldest renew us unto the image of thy Son Jesus Christ through the preaching of thy word and the power of thy Holy Spirit, that we may live with thee eternally in body and soul and praise thee, whereunto we were created in the beginning; and that thou wouldest withstand Satan, that he snatch not thy holy word out of our hearts, as he did to our first parents Adam and Eve.'),
        P('civil-authority',
          p='Dieweil du uns auch in diesem leben durch die handt unser oberkeyt, deiner diener, wilst regieren, so bitten wir dich, der du ihre hertzen in deiner hand hast, wöllest ihnen allen, der keyserlichen und königlichen majestat, allen fürsten und herrn, insonderheyt unserm gnedigisten chur- und landsfürsten, hertzog Friderichen, pfaltzgraven, sampt irer churfürstlichen gnaden ehegemahel, jungen herrschaft, rähten und amptleuten (auch einen erbern rath dieser statt) [einer erbaren gemein dieses orts.] gnad und einigkeyt verleihen, daß sie ire gantze regierung dahin richten, daß unser herr Jesus Christus, dem du allen gewalt im himmel und auf erden gegeben hast, uber sie und ire underthonen hersche, auf daß das arme volck, die da sind creaturn deiner hend und schaf deiner wayde, für die auch der herr Jesus sein blut vergossen hat, regiert werden in aller heiligkeyt und gerechtigkeyt, daß auch wir umb deinetwillen inen alle gebürliche ehr und treu erzeigen und under inen ein ehrbar, fridsams und christlichs leben füren mögen.',
          p_en='And forasmuch as thou wilt govern us in this life also by the hand of our magistrates, thy ministers, we beseech thee, who hast their hearts in thy hand, that thou wouldest vouchsafe unto them all, the Imperial and royal Majesty, all princes and lords, especially our most gracious Elector and prince of this land, Duke Frederick, Count Palatine, together with his Electoral Grace’s consort, the young lordship, counsellors and officers (and also an honourable council of this city) [an honourable commune of this place], grace and unity, that they may direct their whole government to this end, that our Lord Jesus Christ, unto whom thou hast given all power in heaven and in earth, may reign over them and their subjects; that the poor people, which are the creatures of thy hands and the sheep of thy pasture, for whom also the Lord Jesus hath shed his blood, may be governed in all holiness and righteousness; and that we also for thy sake may show them all due honour and faithfulness, and lead under them an honest, peaceable and Christian life.'),
        P('fruits-of-earth',
          p='Gib auch deinen segen und benedeiung zu der frucht der erden, auf daß wir dich dardurch als einen vater und ursprung aller barmhertzigkeyt und güter erkennen.',
          p_en='Give also thy blessing and benediction to the fruit of the earth, that we may thereby acknowledge thee as a Father and fountain of all mercy and good things.'),
        P('all-men',
          p='Wir bitten dich auch nicht allein für uns, sonder auch für alle menschen der gantzen welt, wöllest dich uber sie allesampt gnediglich erbarmen,',
          p_en='We pray thee also not for ourselves only, but also for all men of the whole world, that thou wouldest have mercy upon them all graciously;'),
        P('persecuted', sub='turks; errant',
          p='insonderheyt aber, die unser mitglieder seind an dem leib Jesu Christi und umb deiner warheyt willen vom Türcken und bapst verfolgen leiden. Wöllest, o vater aller gnaden, solches wüten deiner feind, die deinen son Jesum in seinen gliedern verfolgen, zurückhalten und die verfolgten mit unüberwindtlicher standhaftigkeyt und kraft deines heiligen geists stercken, auf daß sie solche verfolgung von deiner hand mit dancksagung annemen und in ihrem trübsal solche freund empfinden, welche ubertrifft allen verstand.',
          p_en='but especially upon them that are our fellow members in the body of Jesus Christ and for thy truth’s sake suffer persecution from the Turk and the Pope. Restrain, O Father of all grace, such raging of thine enemies, which persecute thy Son Jesus in his members, and strengthen the persecuted with invincible steadfastness and the power of thy Holy Spirit, that they may receive such persecution from thy hand with thanksgiving, and in their tribulation feel such joy as passeth all understanding.',
          note='“freund” (sic) for “freud”.'),
        P('afflicted', sub='childbirth',
          p='Tröste und stercke alle armen, gefangen, krancken, witwen und weysen, schwangere weiber und bekümmerte und angefochtene hertzen und gib ihnen deinen frieden,',
          p_en='Comfort and strengthen all the poor, the captives, the sick, widows and orphans, women with child, and troubled and tempted hearts, and give them thy peace;'),
        P('lords-prayer', sub='conclusion',
          p='durch unsern lieben herrn Jesum Christum, welcher uns diese gwisse verheissung gethan hat: Fürwar, fürwar, sage ich euch, was ihr den vater bitten werdet in meinem namen, das wirdt er euch geben, und uns darauf hat befohlen, also zu beten: Unser vater etc.',
          p_en='through our dear Lord Jesus Christ, who hath made us this sure promise: Verily, verily, I say unto you, Whatsoever ye shall ask the Father in my name, he will give it you; and hath commanded us thereupon to pray thus: Our Father, etc.'),
    ]))

W.append(dict(
    key='kurpfalz_1563_lp', doc=504, year=1563,
    order='Kurpfalz, Kirchenordnung (Friedrich III.)',
    territory='Electoral Palatinate',
    citation='Sehling 14, Regierungszeit Friedrichs III. Nr. 60 (KO 1563), pp. 390–391',
    family='R2. Heidelberg Lord’s-Prayer paraphrase', form='Lord’s Prayer paraphrase',
    tradition='Reformed',
    position='Alternative (“Oder also”) to the Sunday prayer after the sermon (after confession and absolution); followed by the Our Father, a psalm and the blessing.',
    heading='Oder also',
    heading_en='Or thus',
    notes='Petitions follow the order of the Lord’s Prayer, the clause of which Sehling’s edition prints in square brackets before each paragraph; text from Geneva 1563 and Heidelberg Catechism qq. 122–127.',
    petitions=[
        P('exhortation', sub='lords-prayer',
          r='Oder also:', r_en='Or thus:',
          p='Almechtiger Gott, himlischer vater, der du hast uns verheissen, was wir dich in dem namen deines geliebten sohns Jesu Christi werden bitten, das wöllest du uns gewißlich geben.',
          p_en='Almighty God, heavenly Father, who hast promised us that whatsoever we shall ask thee in the name of thy beloved Son Jesus Christ, thou wilt surely give it us:'),
        P('word', sub='congregation',
          r='[Geheiliget werde dein nam.]', r_en='[Hallowed be thy name.]',
          p='Wir bitten dich, daß du durch deinen heiligen geist in uns wöllest würcken, daß wir dich recht erkennen und dich in allen deinen wercken, in welchen leuchtet dein allmechtigkeyt, weißheyt, güte, gerechtigkeyt, barmhertzigkeyt und warheyt, heiligen, rühmen und preisen und daß auch wir unser gantzes leben, gedancken, wort und werck dahin richten, daß dein nam umb unsertwillen nicht gelestert, sonder geehret und gepriesen werde.',
          p_en='We beseech thee that thou wouldest work in us by thy Holy Spirit, that we may rightly know thee, and hallow, extol and praise thee in all thy works, wherein shineth thine almightiness, wisdom, goodness, righteousness, mercy and truth; and that we also may so direct our whole life, thoughts, words and works, that thy name be not blasphemed for our sakes, but honoured and praised.',
          note='Rubric in square brackets is Sehling’s.'),
        P('church', sub='enemies; errant',
          r='[Dein reich kom.]', r_en='[Thy kingdom come.]',
          p='Auch regier uns also durch das scepter deines worts und kraft deines heiligen geistes, daß wir und alle menschen uns deiner majestet von tag zu tag mehr underwerfen und ergeben, erhalt und mehre deine kirch und zerstör alle werck des teufels und alle falsche und böse rahtschläg, die wider dein heiliges wort erdacht werden. Mach zuschanden deine feind durch die macht deiner warheyt und gerechtigkeyt, daß also aller gewalt, der sich wider deine ehr erhebet, von tag zu tag mehr zerstöret und vertilget werde, biß die vollkommenheyt deines reichs herzukomme, wenn du am jüngsten gericht deine herrligkeyt in uns offenbaren und in ewigkeyt alles in allen sein wirst.',
          p_en='Rule us also so by the sceptre of thy word and the power of thy Holy Spirit, that we and all men may from day to day submit and yield ourselves more unto thy Majesty; preserve and increase thy Church, and destroy all the works of the devil and all false and wicked counsels devised against thy holy word. Confound thine enemies by the might of thy truth and righteousness, that so all power which exalteth itself against thine honour may from day to day be more destroyed and brought to nought, until the perfection of thy kingdom come, when thou shalt reveal thy glory in us at the last judgement and be all in all for ever.'),
        P('estates',
          r='[Dein will geschehe etc.]', r_en='[Thy will be done, etc.]',
          p='Verleihe auch, daß wir und alle menschen unserem eignen willen und allen lüsten unsers fleischs absagen und deinem allein guten willen one alles widersprechen gehorchen, daß also jederman sein ampt und beruf so willig und treulich verrichte wie die engel im himmel.',
          p_en='Grant also that we and all men may renounce our own will and all the lusts of our flesh, and obey thy will, which alone is good, without any gainsaying; that so every man may perform his office and calling as willingly and faithfully as the angels in heaven.'),
        P('fruits-of-earth', sub='peace; civil-authority',
          r='[Gib uns heut unser teglich brodt.]', r_en='[Give us this day our daily bread.]',
          p='Wöllest uns auch mit aller leiblichen notturft versorgen, uns fried und gut regiment verleihen, auf daß wir dardurch erkennen, daß du der einige ursprung alles guten bist und ein getreuer vater, der da sorget für seine kinder, daß auch on deinen segen weder unser sorgen und arbeit noch deine gaben uns gedeien mögen und wir derhalben unser vertrauen von allen creaturen abziehen und allein auf dich setzen.',
          p_en='Provide us also with all bodily necessaries, and vouchsafe us peace and good government, that we may thereby acknowledge that thou art the only fountain of all good and a faithful Father who careth for his children, and that without thy blessing neither our care and labour nor thy gifts can prosper us; and that we may therefore withdraw our trust from all creatures and set it upon thee alone.'),
        P('repentance',
          r='[Vergib uns unser schuldt etc.]', r_en='[Forgive us our debts, etc.]',
          p='Wollest auch uns armen sünderen alle unsere missethat und schulden, auch das böß, so uns noch immerdar anhanget, umb des blutvergiessens Jesu Christi willen nicht zurechnen, wie auch wir diß zeugnuß deiner gnaden in unsern hertzen befinden, daß wir unserm nechsten von hertzen verzeihen und sein nutz begeren zu befürdern.',
          p_en='Impute not unto us poor sinners all our misdeeds and debts, nor the evil that yet always cleaveth unto us, for the sake of the shedding of the blood of Jesus Christ; even as we also find this witness of thy grace in our hearts, that we forgive our neighbour from the heart and desire to further his good.'),
        P('congregation',
          r='[Füre unß nit in versuchung etc.]', r_en='[Lead us not into temptation, etc.]',
          p='Und dieweil wir ja auß uns selbst so schwach sein, daß wir nicht einen augenblick bestehen können und darzu unsere abgesagte feind, der teufel, die welt und unser eigen fleisch, nit aufhören, uns anzufechten, so wöllest uns erhalten und stercken durch die kraft deines heiligen geistes, auf daß wir inen mögen festen widerstandt thuen und in diesem geistlichen streit nit underligen, sonder bestendig bleiben, biß daß wir endtlich den sieg vollkomlich erhalten und in deinem reich mit deinem son, unserm herrn und beschirmer Jesu Christo, ewig regieren.',
          p_en='And forasmuch as we of ourselves are so weak that we cannot stand one moment, and moreover our sworn enemies, the devil, the world and our own flesh, cease not to assail us: uphold and strengthen us by the power of thy Holy Spirit, that we may make firm resistance against them and not be overcome in this spiritual warfare, but abide steadfast, until at the last we obtain the victory perfectly and reign for ever in thy kingdom with thy Son, our Lord and protector Jesus Christ.'),
        P('conclusion', sub='lords-prayer',
          p='Welches alles wir von dir bitten, daß dadurch nit wir, sonder du ewig gepriesen werdest, und daß du solches thun kanst als ein almechtiger Gott und thun wilst wie ein getreuer vater, so gwiß als wir dises von hertzen an dich begeren, durch unsern herrn Jesum Christum, Amen. Unser vater etc.',
          p_en='All which we ask of thee, that thereby not we but thou mayest be praised for ever; and that thou canst do this as an almighty God, and wilt do it as a faithful Father, as surely as we desire this of thee from the heart; through our Lord Jesus Christ. Amen. Our Father, etc.'),
    ]))

W.append(dict(
    key='bentheim_tecklenburg_1588', doc=1507, year=1588,
    order='Bentheim-Tecklenburg, Kirchenordnung 1588/1619',
    territory='Counties of Bentheim, Tecklenburg and Steinfurt',
    citation='Sehling 22, IV/3, pp. 256–257',
    family='R1. Heidelberg 1563 prayer', form='continuous prayer + Lord’s Prayer',
    tradition='Reformed',
    position='After the sermon, the confession and absolution (after Kurpfalz 1563); then the prayer and the Our Father; then baptism, the Supper or marriage, and psalms. Ministers may add to or alter the prayer in time of need or to suit the sermon.',
    heading='Das gemeine Gebett für allerley Noth der Christlichen Gemeine',
    heading_en='The common prayer for all manner of need of the Christian congregation',
    notes='Kurpfalz 1563, adapted for Count Arnold; the print of 1619 (under Emperor Matthias) is the base. The petition for all men adds the conversion of those who err “auß einfalt unnd unwissenheit”, and the persecuted petition adds “die Feinde dieses orts”.',
    petitions=[
        P('thanksgiving', tr_from=('kurpfalz_1563', 3),
          r='Nach diesem allen sol der Diener das gemeine Gebett für allerley Noth der Christlichen Gemeine also anfahen:',
          r_en='After all this the minister shall begin the common prayer for all manner of need of the Christian congregation thus:',
          p='Almächtiger Gott, Schöpffer Himmels unnd der Erden, Wir dancken dir auß grunde unsers Hertzen, daß du uns erschaffen, biß auff diesen Tag uns und die unsere erhalten, gespeiset und ernehret hast. Insonderheit aber dancken wir dir, daß du deinen Sohn Jesum Christum, den du im Paradeiß verheissen, uns hast zuerkennen geben und unsere Sünden durch sein bitter leiden und sterben uns verziehen,',
          tr_sub=[('preserved, fed and nourished us and our children, and wilt yet henceforth preserve and govern us.', 'preserved, fed and nourished us and ours.')]),
        P('word', sub='congregation', tr_from=('kurpfalz_1563', 4),
          p='Und bitten dich, daß du uns zum ebenbildt deines Sons Jesu Christi durch die Predigt seines Worts und krafft deines H. Geists ernewern wollest, auff daß wir mit Leib und Seel ewig mit dir leben unnd dich preisen, darzu wir anfenglich geschaffen seindt, unnd wollest dem Sathan wehren, daß er uns dein heilig Wort nicht auß unserm Hertzen reisse, wie er unsern ersten Eltern, Adam und Even, gethan hat.',
          tr_sub=[('through the preaching of thy word', 'through the preaching of his word'), ('out of our hearts', 'out of our heart')]),
        P('civil-authority', tr_from=('kurpfalz_1563', 5),
          p='Dieweil du uns auch in diesem leben durch die Handt unser Obrigkeit, deiner Diener, wilt regieren, So bitten wir dich, die du ihre Hertzen in deiner Handt hast, wollest inen allen, der Keyserlichen Mayestät, Allen Königen, Chur- und Fürsten und Herrn, Insonderheit aber unseren Gnädigen Landtherrn, Graffen Arnoldten, unnd ihrer G. Ehegemahl jungen Herrn und Fräwlein, auch ihr G. Rähten und Amptleuten und einer erbarn Gemein dieses orts gnad unnd einigkeit verlehnen, daß sie ire gantze regierung dahin richten, daß unser Herr Jesus Christus, dem du allen gewalt im Himmel und auff Erden gegeben hast, uber sie und ihre Underthanen herrsche, auff daß das arme Volck, die da seindt Creaturen deiner Handt und Schaaffe deiner Weide, für die auch der Herr Christus sein Blut vergossen hat, regiert werden in aller heiligkeit und gerechtigkeit, Daß auch wir umb deinent willen ihnen alle gebürliche ehr unnd treuw erzeigen unnd under ihnen ein ehrbar, friedtsam und Christlich leben führen mögen.',
          tr_sub=[('the Imperial and royal Majesty, all princes and lords, especially our most gracious Elector and prince of this land, Duke Frederick, Count Palatine, together with his Electoral Grace’s consort, the young lordship, counsellors and officers (and also an honourable council of this city) [an honourable commune of this place],',
                   'the Imperial Majesty, all kings, Electors and princes and lords, but especially our gracious lord of the land, Count Arnold, and his Grace’s consort, the young lords and damsels, and also his Grace’s counsellors and officers and an honourable commune of this place,'),
                  ('for whom also the Lord Jesus hath shed', 'for whom also the Lord Christ hath shed')]),
        P('fruits-of-earth', tr_from=('kurpfalz_1563', 6),
          p='Gib auch deinen Segen unnd benedeyung zu der Frucht der Erden, Auff daß wir dich dadurch als einen Vatter unnd ursprunck aller Barmhertzigkeit und Güter erkennen.'),
        P('all-men', sub='errant', tr_from=('kurpfalz_1563', 7),
          p='Wir bitten dich auch nicht allein für uns, sondern auch für alle Menschen der gantzen Welt, daß du dieselbige, so sie auß einfalt unnd unwissenheit irren, durch die Predigt deines göttlichen Worts gnediglich bekehren und zu deiner und ihrer selbst erkandtnuß bringen wollest.',
          tr_sub=[('that thou wouldest have mercy upon them all graciously;', 'that if they err out of simplicity and ignorance, thou wouldest graciously convert them through the preaching of thy divine word and bring them to the knowledge of thee and of themselves.')]),
        P('persecuted', sub='turks; errant; enemies', tr_from=('kurpfalz_1563', 8),
          p='Insonderheit aber bitten wir dich für die, so unsere Mitglieder seindt an dem Leib Jesu Christi und umb deiner warheit willen vom Türcken und Bapst verfolgung leiden, Wollest, O Herr aller gnaden, solchs wüten deiner Feinde, die deinen Sohn Jesum Christum in deinen Gliedern verfolgen und die Feinde dieses orts, in welchem dein heiliger Nahm angeruffen wirt, zurück halten unnd die verfolgete mit unuberwindtlicher standthafftigkeit und krafft deines heiligen Geistes stärcken, auff daß sie solche verfolgungen von deiner Handt mit dancksagung annemmen und in ihrem trübsal solche freuwde empfinden, welche ubertrifft allen Verstandt.',
          tr_sub=[('but especially upon them that are our fellow members', 'But especially we pray thee for them that are our fellow members'),
                  ('Restrain, O Father of all grace, such raging of thine enemies, which persecute thy Son Jesus in his members,',
                   'Restrain, O Lord of all grace, such raging of thine enemies, which persecute thy Son Jesus Christ in thy members, and the enemies of this place wherein thy holy name is called upon,')]),
        P('afflicted', sub='childbirth', tr_from=('kurpfalz_1563', 9),
          p='Tröste und stärcke auch alle arme, gefangene, krancken, Wittwen und Waisen, schwangere Weiber, bekümmerte und angefochtene Hertzen und gib inen deinen friede,',
          tr_sub=[('Comfort and strengthen all the poor', 'Comfort and strengthen also all the poor')]),
        P('lords-prayer', sub='conclusion', tr_from=('kurpfalz_1563', 10),
          p='durch unsern Herrn Jesum Christum, welcher uns diese gewisse verheissung gethan hat: Fürwar, fürwar, sag ich euch, was ir den Vatter bitten werdet in meinem Nahmen, das wirdt er euch geben, und uns hat befohlen, darauff also zu betten: Unser Vatter, der du bist, etc.',
          tr_sub=[('through our dear Lord Jesus Christ', 'through our Lord Jesus Christ'), ('Our Father, etc.', 'Our Father, who art, etc.')]),
    ]))

W.append(dict(
    key='bentheim_tecklenburg_1588_lp', doc=1507, year=1588,
    order='Bentheim-Tecklenburg, Kirchenordnung 1588/1619',
    territory='Counties of Bentheim, Tecklenburg and Steinfurt',
    citation='Sehling 22, IV/3, pp. 256–258',
    family='R2. Heidelberg Lord’s-Prayer paraphrase', form='Lord’s Prayer paraphrase + Creed',
    tradition='Reformed',
    position='Alternative (“Oder also”) to the common prayer after the sermon; closes with the Our Father and the Apostles’ Creed.',
    heading='Oder also',
    heading_en='Or thus',
    notes='Kurpfalz 1563 alternative without Sehling’s bracketed petition-headings; adds, after the Our Father, the petition for steadfastness in faith and the Creed (from the Kurpfalz afternoon prayer).',
    petitions=[
        P('exhortation', sub='lords-prayer', tr_from=('kurpfalz_1563_lp', 1),
          r='Oder also:',
          p='Herr, Gott, himlischer Vatter, der du uns verheissen hast, was wir dich in dem Namen deines geliebten Sohns Jesu Christi werden bitten, das wollest du uns gewißlich geben,',
          tr_sub=[('Almighty God, heavenly Father,', 'Lord God, heavenly Father,')]),
        P('word', sub='congregation', tr_from=('kurpfalz_1563_lp', 2), r_en=None,
          p='Wir bitten dich, daß du durch deinen H. Geist in uns wollest wircken, daß wir dich recht erkennen unnd dich in allen deinen Wercken, in welchen leuchte die Almechtigkeit, Weißheit, Güte, Gerechtigkeit, Barmhertzigkeit und warheit, heiligen, rühmen und preisen, und daß auch wir unser gantzes leben, Gedancken, Wort unnd Wercken dahin richten, daß dein Nahme umb unsert willen nicht gelästert, sondern geehret und gepriesen werde,'),
        P('church', sub='enemies; errant', tr_from=('kurpfalz_1563_lp', 3),
          p='Auch regiere uns also durch das Scepter deines Wortes und krafft deines heiligen Geistes, daß wir und alle Menschen uns deiner Majestat von tage zu tage underwerffen und ergeben. Erhalte und mehre deine Kirche unnd zerstöre alle wercke deß Teuffels und alle falsche unnd böse Rathschläge, die wider dein heiliges Wort erdacht werden. Mache zu schanden deine Feinde durch deine warheit unnd gerechtigkeit, und also alle gewalt, die sich wider deine ehr erhebt, von tag zu tag mehr zerstöret und vertilget werde, biß die vollenkommenheit deines Reichs herzu komme, Wann du am jüngsten Gerichte deine herrlichkeit in uns offenbahren und in ewigkeit alles in allem seyn werdest.',
          tr_sub=[('from day to day submit and yield ourselves more', 'from day to day submit and yield ourselves'), ('by the might of thy truth', 'by thy truth')]),
        P('estates', tr_from=('kurpfalz_1563_lp', 4),
          p='Verleihe auch, daß wir und alle Menschen unserm einigen willen und allen lüsten unsers fleisches absagen und deinem allein guten willen ohn alles widersprechen gehorchen, daß also jederman sein ampt und beruff so willig und trewlich verrichte wie die Engelen im Himmel.',
          note='“einigen” (sic) for “eignen”.'),
        P('fruits-of-earth', sub='peace; civil-authority', tr_from=('kurpfalz_1563_lp', 5),
          p='Wollest uns auch mit aller leiblicher notturfft versorgen, uns friedt und gut Regiment verlehnen, auff daß wir dardurch erkennen, daß du der einig ursprung alles guten bist und ein getrewer Vatter, der da versorget seine Kinder, Daß auch one deinen segen weder unser sorg noch arbeit noch deine Gaben uns gedeien mögen Und wir derhalben unser vertrawen von allen Creaturen abziehen und allein auff dich setzeen.',
          tr_sub=[('who careth for his children', 'who provideth for his children')]),
        P('repentance', tr_from=('kurpfalz_1563_lp', 6),
          p='Wollest auch uns armen Sündern alle unsere Missethat unnd Schulden, auch das böse, so uns noch immerdar anhangt, umb deß blutvergiessens Jesu Christi willen nit zurechnen, wie auch wir zeugnuß deiner gnaden in unsern Hertzen befinden, daß wir unsern Negsten von Hertzen verzeihen und seinen nutz begeren zu fürdern.'),
        P('congregation', tr_from=('kurpfalz_1563_lp', 7),
          p='Und weil wir je auß uns selbst so verderbt sein, daß wir nicht ein augenblick bestehen können, Und darzu unser abgesagter Feind, der Teuffel, die Welt unnd unser eigen fleisch nicht auffhören, uns anzufechten, So wöllest uns erhalten und stärcken durch die krafft deines H. Geistes, auff daß wir inen mögen festen widerstandt thun und in diesem geistlichen streit nit underligen, sondern bestendig bleiben, biß daß wir endtlich den Sieg vollenkomlich erhalten und in deinem Reich mit deinem Sohn, unserm Herrn und beschirmer Jesu Christo, ewig regieren,',
          tr_sub=[('we of ourselves are so weak', 'we of ourselves are so corrupt'), ('our sworn enemies', 'our sworn enemy')]),
        P('conclusion', sub='lords-prayer', tr_from=('kurpfalz_1563_lp', 8),
          p='Welches alles wir von dir bitten, daß dadurch nicht wir, sonder Du ewig gepreiset werdest, Und daß du solches thun kanst als ein Almächtiger Gott unnd wöllest thun wie ein getrewer Vatter, so gewiß als wir dieses von Hertzen von dir begeren, durch unsern Herrn Jesum Christum, der uns auch also zu betten gelehret hat: Unser Vatter, der du bist, etc.',
          tr_sub=[('through our Lord Jesus Christ. Amen. Our Father, etc.', 'through our Lord Jesus Christ, who hath also taught us so to pray: Our Father, who art, etc.')]),
        P('creed',
          p='Wollest uns auch geben standthafftigkeit und täglichs zunemen in dem alten, waren und ungezweiffelten Christlichen Glauben, auff daß wir uns durch denselben je lenger, je mehr Christi Jesu und aller seiner Güter theilhafftig machen, von welchem Glauben wir bekantnuß thun, mit Munde und Hertzen sprechende: Ich glaub in Gott Vatter, Almächtigen, etc.',
          p_en='Give us also steadfastness and daily increase in the old, true and undoubted Christian faith, that thereby we may make ourselves more and more partakers of Christ Jesus and all his benefits; of which faith we make confession with mouth and heart, saying: I believe in God the Father Almighty, etc.'),
    ]))
