#!/usr/bin/env python3
"""Build the Index of persons of the master guide.

The index lists the historical persons whom the guide names: the reformers,
princes, prelates, pastors, schoolmasters and musicians of the period, named
in the orders, in Sehling's titles of them or in the guide's own text, and
the Fathers and other persons of earlier centuries. Biblical persons, saints
named for their feast days, and later editors and scholars are not indexed. Each person
is filed under the sections that name them, and each section is a link. The
list is written between the index markers; the note above them is ordinary
text.

PERSONS gives each person's heading and the forms under which the guide
names them. A form is a regular expression, and a genitive s may follow it:
"Luther", "Lutheri", "Doctor Martinus" and "D. Mart." are all Luther. Where
a name is shared, as "Philip", "Duke George" and "Johann" are, the form
carries the context that tells the persons apart. Where forms match at the
same place, the longest match is taken. A person whose forms match nothing
is reported.

Usage:
    python3 tools/master_persons.py           rebuild the index in place
    python3 tools/master_persons.py --check   only report whether it is current
    python3 tools/master_persons.py --list    print every name found
"""
import re
import sys
import unicodedata

from master_scripture import blocks, label, links, normalize, roman

MASTER = 'LITURGICAL_AND_ECCLESIASTICAL_LIFE.md'
START = '<!-- Index of persons start: generated by tools/master_persons.py; do not edit by hand -->'
END = '<!-- Index of persons end -->'

# Heading, forms. Rulers are as a rule entered under their first names, with title and
# territory, and others under their surnames. The groups only make the table easier to read:
# the index is sorted by heading.
PERSONS = [
    # Reformers, pastors and others of the period
    ('Luther, Martin', [r'Luther', r'Lutheri', r'Luthero', r'Lutherum', r'Lutherus',
        r'Doctor Martin(?:us)?', r'Dr\.? Martin(?:us)?', r'D\. Martin(?:us)?', r'D\. Mart\.',
        r'doctor Mart\.', r'Master Dr Martin']),
    ('Bugenhagen, Johannes', [r'Bugenhagen', r'Bugenhagius', r'Pomeranus', r'Pomerani',
        r'Joannem Bugenhagen Pomeren']),
    ('Melanchthon, Philip', [r'Dr Philip', r"Philip(?='s Loci)", r'(?<=Tomes of Luther and of )Philip',
        r'Melanchthon', r'Melanthon', r'Master Philip(?: Melanchthon)?', r'Philippi(?=, Brencii)',
        r"Philip(?='s, Brenz)"]),
    ('Müntzer, Thomas', [r'Müntzer', r'Münzer', r'Thomas Müntzer']),
    ('Bucer, Martin', [r'Bucer', r'Butzer']),
    ('Brenz, Johannes', [r'Brenz', r'Brentius', r'Brencii', r'Johannes Brenz']),
    ('Osiander, Andreas', [r'Osiander', r'Andreas Osiander']),
    ('Jonas, Justus', [r'(?<=Kreuziger, )Jonas', r'Justus Jonas', r'Jonas(?= für Zerbst)',
        r'(?<=Luther und )Jonas', r'Doctor Justus', r'(?<=Regensburg \()Jonas(?=\), 1553)',
        r'(?<=Regensburg, )Jonas(?=, 1553)']),
    ('Spangenberg, Johann', [r'Johann Spangenberg', r'Johan Spangenberge',
        r'Master Johann(?: Spangenberg)?', r'Spangenbergii', r'Spangenbergio', r'Spangenberg']),
    ('Spangenberg, Cyriacus', [r'Cyriacus Spangenberg']),
    ('Dietrich, Veit', [r'V\. Dietrich', r'Dietrich', r'Veit Dietrich', r'Vitum Dietrich',
        r"Dietrich(?=\'s Agendbüchlein| Agendbüchlein)"]),
    ('Döber, Andreas', [r'Döber', r'Andreas Döber']),
    ('Kantz, Kaspar', [r'Kantz', r'Caspar Kantz', r'Kaspar Kantz']),
    ('Volprecht, Wolfgang', [r'Volprecht']),
    ('Micron, Marten', [r'Micron', r'Marten Micron', r'Martin Micron']),
    ('Lasco, John a', [r'John a Lasco', r'Johannes a Lasco', r'a Lasco', r'Lasco']),
    ('Calvin, John', [r'Calvin(?!ist|ism)']),
    ('Zwingli, Huldrych', [r'Zwingli(?!an)']),
    ('Knox, John', [r'John Knox', r'Knox']),
    ('Hus, John', [r'John Hus', r'Hus', r'Huß', r'Huss', r'Hussen', r'Hussens', r'Johann Hussen?',
        r'Johan Hussen']),
    ('Lossius, Lucas', [r'Lucas Lossius', r'Lossius']),
    ('Corvinus, Antonius', [r'Antonius Corvinus', r'Corvinus', r'Corvinum', r'D\. Anto\. Corvinum']),
    ('Rhegius, Urbanus', [r'Urban(?:us)? ?Rhegius', r'Rhegius', r'D\. Urbanum Regium', r'Urbanum Regium']),
    ('Andreae, Jakob', [r'D\. Jacob \[Andreä\]', r'Jakob Andreae', r'Jakob Andreäs',
        r'Dr Jacob \[?Andreae\]?', r'(?<!S\. )(?<!tag )(?<!\[)Andreae(?!, Thomae| Apostoli| Thomae)']),
    ('Chemnitz, Martin', [r'Martin Chemnitz', r'M\. Chemnitz',
        r"Chemnitz(?=/Andreae| and Mörlin|\'s Corpus)"]),
    ('Mörlin, Joachim', [r'Mörlin', r'Joach\. Morlini']),
    ('Selnecker, Nikolaus', [r'Selnecker']),
    ('Pfeffinger, Johann', [r'Johann Pfeffinger', r'Pfeffinger']),
    ('Bonnus, Hermann', [r'Hermanni Bonni', r'Bonni', r'Hermann Bonnus', r'Bonnus']),
    ('Lobwasser, Ambrosius', [r'Lobwasser', r'Lobwaßer', r'Lobwaßers']),
    ('Hausmann, Nicolaus', [r'Nicolaus Hausmann', r'Hausmann']),
    ('Marbach, Johann', [r'Johann(?:es)? Marbach', r'Doctor Johann Marbach', r'Marbach(?!er)']),
    ('Zuleger, Wenzel', [r'Wenzel Zuleger', r'Zuleger']),
    ('Linck, Wenzel', [r'Wenzel Linck', r'Linck']),
    ('Schwarz, Diebold', [r'Diebold Schwarz', r'Theobald (?:\(Diebold\) )?Schwarz', r'Schwarz']),
    ('Rothmann, Bernhard', [r'Bernhard Rothmann', r'Rothmann']),
    ('Hardenberg, Albert', [r'Albert Hardenberg', r'Hardenberg']),
    ('Karlstadt, Andreas', [r'Karlstadt']),
    ('Capito, Wolfgang', [r'Wolfgang Capito', r'Capito']),
    ('Oecolampadius, Johannes', [r'Oecolampadius']),
    ('Bader, Johannes', [r'Johannes Bader']),
    ('Sulzer, Simon', [r'Simon Sulzer']),
    ('Greiter, Matthäus', [r'Matthäus Greiter', r'Greiter']),
    ('Löner, Kaspar', [r'Kaspar Löner', r'Caspar Löner', r'Caspar Löhner', r'Löner']),
    ('Kolb, Franz', [r'Franz Kolb', r'Kolb']),
    ('Coelius, Michael', [r'Michael Coelius', r'Coelius']),
    ('Huberinus, Caspar', [r'Caspar Huberinus', r'Huberinus']),
    ('Hegenwalt, Erhart', [r'Erhart Hegenwalt', r'Hegenwalt']),
    ('Honterus, Johannes', [r'Honterus']),
    ('Heyden, Sebald', [r'Sebald Heyden', r'Heyden']),
    ('Speratus, Paul', [r'D\. Sperati', r'Sperati', r'Paul Speratus', r'Doctor Speratus', r'Speratus']),
    ('Eber, Paul', [r'Paul Eber', r'Eber']),
    ('Decius, Nikolaus', [r'Nikolaus Decius', r'Decius']),
    ('Triller, Valentin', [r'Triller']),
    ('Sarcerius, Erasmus', [r'Sarcerius']),
    ('Mathesius, Johannes', [r'Johannes Mathesius', r'Master Mathesius', r'Mathesius']),
    ('Assum, Johann', [r'Johann Assum', r'Assum']),
    ('Leyser, Polycarp', [r'Polycarp Leyser', r'Leyser']),
    ('Stieber, Thomas', [r'Thomas Stieber', r'Stieber']),
    ('Pangratius, Andreas', [r'Andreas Pangratius', r'Andreas Pangratio', r'Pangratius']),
    ('Banc, Arnaud', [r'Arnaud Banc']),
    ('Marboeuf, Pierre', [r'Pierre Marboeuf']),
    ('François, Nicolas', [r'Nicolas François']),
    ('Ludecus, Matthäus', [r'Ludecus']),
    ('Bora, Katharina von', [r'Katharina von Bora']),
    ('Eitzen, Paul von', [r'Paul von Eitzen', r'Eitzen']),
    ('Gallus, Nikolaus', [r'Nikolaus Gallus', r'(?<=Vergleichsartikel mit )Gallus',
        r'(?<=Kirchenordnung des )Gallus']),
    ('Heshusen, Tilemann', [r'Heshusius', r'Tilemann Heshusen', r'Tilemann von Hussen', r'Heshusen',
        r'Henrici Heshusii']),
    ('Fabricius, Jakob', [r'Jakob Fabricius']),
    ('Erastus, Thomas', [r'Erastus']),
    ('Ursinus, Zacharias', [r'Ursinus']),
    ('Beza, Theodore', [r'Beza']),
    ('Zanchi, Girolamo', [r'Zanchi']),
    ('Poullain, Valérand', [r'Valérand Poullain', r'Poullain', r'Valerand Poullain']),
    ('Hofmann, Johann', [r'Johann Hofmann']),
    ('Joris, David', [r'David Joris']),
    ('Faber, Gellius', [r'Gellius Faber']),
    ('Faber (preacher at Amberg)', [r'(?<=Predigers )Dr\. Faber']),
    ('Noppus, Hieronymus', [r'Hieronymus Noppus', r'Noppus']),
    ('Lauterbach, Anton', [r'Anton Lauterbach']),
    ('Hefentreger, Johann', [r'Johann Hefentreger']),
    ('Schenk, Jacob', [r'Jacob Schenk']),
    ('Sam, Konrad', [r'Konrad Sam']),
    ('Rabus, Ludwig', [r'Ludwig Rabus']),
    ('Veesenbeck, Johannes', [r'Johannes Veesenbeck']),
    ('Mening, Markus', [r'Markus Mening']),
    ('Naso, Joseph', [r'Joseph Naso', r'Naso(?= conflict)']),
    ('Varrelmann, Johannes', [r'Johannes Varrelmann']),
    ('Widensee, Eberhard', [r'Widensee', r'Eberhard Widensee']),
    ('Zindel, Christian', [r'Christian Zindel']),
    ('Abel, Konrad', [r'Konrad Abel']),
    ('Pflacher, Moses', [r'Pfarrers Pflacher']),
    ('Püttner, David', [r'David Püttner']),
    ('Kestner, Veit', [r'Veit Kestner']),
    ('Nervius, Johannes', [r'Johannes Nervius']),
    ('Schnabel, Albert', [r'Albert Schnabel']),
    ('Hagemann, Simon', [r'Simon Hagemann']),
    ('Pistorius, Johannes', [r'Johannes Pistorius']),
    ('Kroschen, Severus', [r'Severus Kroschen']),
    ('Buchholtzer, Georg', [r'Georg Buchholtzer']),
    ('Goltz, Joachim', [r'Joachimum Goltzium']),
    ('Rodtbart, Petrus', [r'Petrum Rodtbart']),
    ('Fabricius (superintendent in Anhalt)', [r'Superintendenten Fabricius', r'Superintendent Fabricius']),
    ('Pauli, Simon', [r'Superintendenten Pauli', r'Simon Pauli']),
    ('Aepinus, Johannes', [r'Aepinus']),
    ('Amsdorf, Nikolaus von', [r'Amsdorf']),
    ('Beust, Joachim von', [r'Beust']),
    ('Bidembach, Felix', [r'Bidembach']),
    ('Blarer, Ambrosius', [r'Blarer']),
    ('Bucanus, Wilhelm', [r'Bucanus']),
    ('Cox, Richard', [r'Richard Cox']),
    ('Fagius, Paul', [r'Fagius']),
    ('Hamelmann, Hermann', [r'Hamelmann']),
    ('Hemmingsen, Niels', [r'Hemmingsen']),
    ('Kreuziger, Elisabeth', [r'Kreuziger']),
    ('Lambert, Francis', [r'Francis Lambert']),
    ('Mögner, Veit', [r'Mögner']),
    ('Porta, Conrad', [r"Porta(?='s Pastorale)"]),
    ('Serinus', [r'Serinus']),
    ('Spengler, Lazarus', [r'Spengler']),
    ('Stancarus, Francesco', [r'Stancarus']),
    ('Whittingham, William', [r'Whittingham']),
    ('Winkel, Heinrich', [r'Winkel(?= and Corvinus)']),
    ('Zwick, Johannes', [r'Zwick']),
    ('Nieden, Arnd van', [r'Arnd van Nieden']),
    ('Leyden, Peter van', [r'Peter van Leyden']),
    ('Verbeke, Renatus', [r'Renatus Verbeke']),
    ('Hiemeyer, David', [r'David Hiemeyer']),
    ('Streitberger, Johann', [r'(?:Dr )?Johann Streitberger']),
    ('Hertweg, Georg', [r'Georg(?:en)? Hertweg']),
    ('Schlüter, Gottfried', [r'(?:Superintendent )?Gottfried Schlüter']),
    ('Geyer, Hans', [r'Hans Geyer']),
    ('Schlemmer, Jakob', [r'(?:Master |Herr )?Jacob Schlemmer']),
    ('Sella, Joachim', [r'(?:[Hh]err )?Joachim Sella']),
    ('Sahr, Johann', [r'(?:Master |Herr )?Johann Sahr']),
    ('Runge, Jacob', [r'Jacob Runge']),
    ('Judex, Johannes', [r'Johannes Judex']),
    ('Hollande, Johannes de', [r'Johannes de Hollande']),
    ('Codomann, Laurentius', [r'(?:Master |herr )?Laurentius Codoman+us']),
    ('Kosch, Laurentius', [r'(?:Master )?Laurentius Kosch']),
    ('Eberhard, Leonhard', [r'(?:Master )?Leonhard Eberhard']),
    ('Görlitz, Martin', [r'Martin Görlitz']),
    ('Bode, Michael', [r'Michael Bode']),
    ('Lorenz (schoolmaster at Frankfurt)', [r'(?<=Michael Bode und )Lorenz',
        r'(?<=Michael Bode and )Lorenz']),
    ('Hanssen, Paul', [r'Paul Hanssen', r'Pauwel Hanssen']),
    ('Janken (brother of Paul Hanssen)', [r"(?<=Paul's brother )Janken"]),
    ('Reysing, Philipp', [r'Philipp Reysing']),
    ('Nimwegen, Rudolf von', [r'Rudolf von Nimwegen']),
    ('Döberlein, Wolfgang', [r'Wolfgang Döberlein']),
    # Princes, lords and prelates
    ('Johann, Elector of Saxony', [r'Herzog Hansen(?= churfursten)',
        r'Duke John(?= and Duke John Frederick)']),
    ('Johann Friedrich I, Elector of Saxony', [r'Duke John Frederick(?= of Saxony)']),
    ('Johann Friedrich II, Duke of Saxony', [r'Johann Friedrich(?: des Mittleren| the Middle)',
        r'Johans Friderichen des mittlern', r'Duke Johann Friedrich(?= made himself)']),
    ('Johann Friedrich III, Duke of Saxony', [r'Johann Friedrich the Younger',
        r'Johans Friderichen d\. j\.']),
    ('Johann Wilhelm, Duke of Saxony', [r'Johann Wilhelms?', r'Johans Wilhelm']),
    ('Heinrich, Duke of Saxony', [r'Duke Heinrich', r'Duke Henry', r'[Hh]erzog Heinrichs']),
    ('Moritz, Elector of Saxony', [r'Herzogs Moritz']),
    ('August, Elector of Saxony', [r'Kurfürst August', r'Kurfürsten August', r'Duke August',
        r'Elector August', r'Herzogs Augustus', r'Herzog Augusts']),
    ('Christian I, Elector of Saxony', [r'Christian I(?![\w])']),
    ('Joachim II, Elector of Brandenburg', [r'(?:Elector |Kurfürst )?Joachim II\.?', r'Elector Joachim']),
    ('Johann, Margrave of Brandenburg-Küstrin', [r'Markgrafen Johann', r'Margrave Johann']),
    ('Georg, Margrave of Brandenburg-Ansbach', [r'Lord George(?=, margrave)', r'Margrave George',
        r'herrn Geörgen']),
    ('Casimir, Margrave of Brandenburg-Kulmbach', [r'Fürsten Casimir', r'Herr Casimir']),
    ('Albrecht Alcibiades, Margrave of Brandenburg-Kulmbach', [r'Margrave Albrecht']),
    ('Albrecht, Duke in Prussia', [r'Duke Albrecht', r'Herzogs Albrecht(?= in Preussen)']),
    ('Philipp, Landgrave of Hesse', [r"Philip(?='s death)", r'Philip of Hesse',
        r"Philip(?='s (?:Hesse|church|testament|sons))", r'(?<=under )Philip(?= \(to 156)',
        r'Landgrave Philipsen', r'(?<=[Uu]nser )Philipsen', r'(?<=herrn )Philipsen(?=, Landtgraven)']),
    ('Wilhelm IV, Landgrave of Hesse-Kassel', [r'Wilhelms(?=, Ludwigs, Philipsen)']),
    ('Ludwig IV, Landgrave of Hesse-Marburg', [r'(?<=Wilhelms, )Ludwigs']),
    ('Philipp II, Landgrave of Hesse-Rheinfels', [r'(?<=Ludwigs, )Philipsen']),
    ('Georg I, Landgrave of Hesse-Darmstadt', [r'Georgens(?=, Gebrüder)']),
    ('Moritz, Landgrave of Hesse-Kassel', [r'Landgraf Moritz', r'(?<=Kassel under )Moritz']),
    ('Ulrich, Duke of Württemberg', [r'Duke Ulrich']),
    ('Christoph, Duke of Württemberg', [r'Duke Christoph']),
    ('Ludwig, Duke of Württemberg', [r'Duke Ludwig']),
    ('Friedrich II, Elector Palatine', [r'Friedrich II(?![I\w])',
        r'Pfaltzgrave Friedrichs(?=, churfürsten etc\., aufgerichtete)']),
    ('Ottheinrich, Elector Palatine', [r'Ottheinrich']),
    ('Friedrich III, Elector Palatine', [r'Duke Frederick(?=, Count Palatine)', r'Frederick III',
        r'Friedrich III\.?', r'Friedrichs III\.?', r'Elector Frederick III',
        r'Kurfürst Friedrich III\.?', r'Pfal?n?tz[gq]ra(?:ve|f) Friderichs',
        r'(?<=pfaltzgrave )Friderichs', r'hertzog Friderichen(?=, pfaltzgraven)']),
    ('Ludwig VI, Elector Palatine', [r'Count Palatine Lewis', r'Ludwig VI',
        r'Pfal?n?tzgra(?:ve|f) Ludwigs']),
    ('Johann Casimir, Count Palatine', [r'Johann Casimir(?:en)?', r'John Casimir',
        r'(?<![\w ]{2}g )Casimir(?= 1587)']),
    ('Friedrich IV, Elector Palatine', [r'Frederick IV', r'Elector Palatine(?= in 1599)',
        r'Friedrich IV', r'Elector Frederick IV', r'Elector Frederick(?= IV)']),
    ('Reichard, Duke of Pfalz-Simmern', [r'Duke Reichard', r'hertzog Reichards']),
    ('Georg, Duke of Pfalz-Simmern', [r'Duke George(?=, as prince)',
        r'Hertzog Georg(?= als Landtßfürsten)']),
    ('Wolfgang, Count Palatine of Zweibrücken', [r'Pfalzgraf Wolfgang', r'Duke Wolfgang']),
    ('Georg Johann, Count Palatine of Veldenz', [r'Pfalzgraf Georg Johann', r'Georg Johann']),
    ('Wolfgang, Prince of Anhalt', [r'Lord Wolfgang(?=, prince of Anhalt)', r'Fürsten Wolfgang',
        r'Prince Wolfgang']),
    ('Johann IV, Prince of Anhalt', [r'(?<=Wolfgang, )Johann(?=, Georg und Joachim)',
        r'(?<=Fürsten )Johann(?=,? (?:und )?Georg)', r'Johann(?= Georg’s und Joachim’s von Anhalt)',
        r'(?<=Princes )Johann(?= and Georg)']),
    ('Georg III, Prince of Anhalt', [r'(?<=Johann, )Georg(?= und Joachim von Anhalt)',
        r'(?<=Johann und )Georg(?= von Anhalt)', r'(?<=Johann )Georg(?=’s und Joachim’s von Anhalt)',
        r'(?<=Johann and )Georg', r'(?:Prince )?Georg(?= of Anhalt)',
        r'Georg(?= as bishop| "had himself)', r'Prince George(?= on 23 July)']),
    ('Joachim, Prince of Anhalt', [r'(?<=Georg und )Joachim(?= von Anhalt)', r'Fürsten Joachim',
        r'Joachim(?=’s von Anhalt)']),
    ('Bernhard, Prince of Anhalt', [r'Prince Bernhard', r'Fürsten Bernhard']),
    ('Joachim Ernst, Prince of Anhalt', [r'(?:Prince )?Joachim Ernst']),
    ('Johann Georg, Prince of Anhalt', [r'(?:Prince )?Johann Georg(?!’s und Joachim)',
        r'Hans Georg(?= von Anhalt)']),
    ('Plauen, Anna von, Abbess of Gernrode', [r'Abbess Anna']),
    ('Julius, Duke of Brunswick-Wolfenbüttel', [r'Duke Julius', r'Herzog Julius']),
    ('Heinrich Julius, Duke of Brunswick-Wolfenbüttel', [r'Heinrich Julius']),
    ('Elisabeth, Duchess of Brunswick-Calenberg', [r'Duchess Elisabeth', r'Herzogin Elisabeth']),
    ('Ernst, Duke of Brunswick-Lüneburg', [r'Herzog Ernstes',
        r'(?<=wir, )Ernst(?=, von Gots gnaden herzog)']),
    ('Wilhelm the Younger, Duke of Brunswick-Lüneburg', [r'Herzogs Wilhelm d\. J\.',
        r'Duke (?:Wilhelm|William) the Younger']),
    ('Philipp I, Duke of Brunswick-Grubenhagen', [r'Herzogs Philipps I\.']),
    ('Philipp II, Duke of Brunswick-Grubenhagen', [r'(?<=herrn )Philipsen(?=, herzogen zu Brunschweig)']),
    ('Wolfgang, Duke of Brunswick-Grubenhagen', [r'Herzog Wolfgang(?=, Herzog zu Braunschweig)']),
    ('Johann Albrecht I, Duke of Mecklenburg', [r'(?<=lord )Johann Albrecht', r'Duke Johann Albrecht']),
    ('Barnim IX, Duke of Pomerania', [r'Barnim(?:’s)? IX\.?', r'Herzogs Barnim']),
    ('Frederick I, King of Denmark', [r'König Friedrich I\.']),
    ('Johann the Elder, Duke of Schleswig-Holstein', [r'Duke Johann(?= ordered the old pews)']),
    ('Adolf I, Duke of Holstein-Gottorp', [r'Herzog Adolf I\.']),
    ('Johann Adolf, Duke of Holstein-Gottorp', [r'(?:Duke )?Johann Adolf']),
    ('Enno II, Count of East Frisia', [r'(?<=wy, )Enno(?=, grave)']),
    ('Anna, Countess of East Frisia', [r'Countess Anna', r'Gräfin Anna']),
    ('Edzard II, Count of East Frisia', [r'Count Edzard(?: II)?', r'Edzard II']),
    ('Maria, Lady of Jever', [r'Fräulein Maria(?: von Jever)?', r'Maria von Jever']),
    ('Anton I, Count of Oldenburg', [r'Graf Anton(?: I\.)?']),
    ('Georg Ernst, Count of Henneberg', [r'Georg Ernst(?:en|’s)?']),
    ('Wilhelm IV, Count of Henneberg', [r'Wilhelm(?:’s)? von Henneberg']),
    ('Heinrich IV, Lord of Reuss', [r'Heinrich(?:’s)? IV\.? von Reuss',
        r'(?<=Kirchen-Ordnung of )Heinrich IV']),
    ('Heinrich IV, Count of Sayn', [r'Graf Heinrich IV\.?']),
    ('Philipp I, Count of Leiningen-Westerburg', [r'Graf Philipp(?=\))']),
    ('Philipp IV, Count of Hanau-Lichtenberg', [r'Graf Philipp IV\.?']),
    ('Georg, Count of Erbach', [r'Graf Georg(?=\))']),
    ('Adolf, Count of Neuenahr and Moers', [r'Graf Adolf von Neuenahr', r'Count Adolf(?= \(1578)']),
    ('Wolfgang Ernst, Count of Ysenburg-Birstein', [r'(?:Graf )?Wolfgang Ernst']),
    ('Wolfgang, Count of Hohenlohe', [r'Count Wolfgang', r'grave Wolffgangs']),
    ('Ludwig Casimir, Count of Hohenlohe', [r'Graf L[nu]dwig Casimirs?']),
    ('Georg Friedrich, Count of Hohenlohe', [r'Count Georg Friedrich']),
    ('Johann VI, Count of Nassau-Dillenburg', [r'Count John VI', r'John VI(?= of Nassau)', r'Johann VI\.?']),
    ('Johann Albrecht, Count of Solms-Braunfels', [r'Count Johann Albrecht']),
    ('Simon VI, Count of Lippe', [r'Simon VI']),
    ('Johann III, Duke of Jülich-Cleves-Berg', [r'Duke Johann III', r'Johann III(?= of Jülich)']),
    ('Friedrich II, Duke of Liegnitz', [r'Friedrichs(?= \. \. \. zur Liegnitz)',
        r'Herzogs Friedrich(?= für die Stadt Liegnitz)']),
    ('Georg II, Duke of Brieg', [r'Georgs II\.?(?= für Liegnitz-Brieg)']),
    ('Joachim Friedrich, Duke of Liegnitz and Brieg', [r'Herzog Joachim Friedrichs']),
    ('Gotthard Kettler, Duke of Courland', [r'Herzog Gottfrieds']),
    ('Philipp I, Margrave of Baden', [r'Margrave Philipp(?= of Baden|, 1531)']),
    ('Philipp II, Margrave of Baden', [r'[Mm]arggrav?e Philipsen zu Baden']),
    ('Wied, Hermann von, Archbishop of Cologne', [r'Hermann v(?:on|\.) Wied', r"Wied(?='s)"]),
    ('Truchsess von Waldburg, Gebhard, Archbishop of Cologne', [r'Gebhard Truchsess']),
    ('Waldeck, Franz von, Bishop of Münster', [r'(?:Bishop )?Franz von Waldeck', r'Bishop Franz']),
    ('Christoph, Archbishop of Bremen', [r'Erzbischof Christoph']),
    ('Heinrich, Archbishop of Bremen', [r'Heinrich(?=, postulirter erzbischoff)']),
    ('Johann Friedrich, Archbishop of Bremen', [r'Johan Friedrichs(?=, erwelten)']),
    ('Sigismund, Archbishop of Magdeburg', [r'Administrator Sigismund(?: of Brandenburg)?',
        r'Erzbischofs Sigismund']),
    ('Marquard, Bishop of Speyer', [r'bischof Marquards']),
    ('Queiss, Erhard von, Bishop of Pomesania', [r'Erhard von Queiss']),
    ('Kolowrat, Jaroslaw von', [r'Jaroslaw von Kolowradt']),
    ('Bieberstein, Joachim von', [r'Joachim von Bieberstein']),
    ('Bieberstein, Johann von', [r'(?<=Herren )Johann(?= und Abraham von Bieberstein)']),
    ('Bieberstein, Abraham von', [r'Abraham von Bieberstein']),
    ('Schulenburg, Joachim von der', [r'Joachim v\. d\. Schulenburg']),
    ('Minkwitz, Hans von', [r'Hans von Minkwitz']),
    ('Promnitz, Abraham von', [r'Abraham von Promnitz']),
    ('Rantzau, Heinrich', [r'Heinrich Rantzau']),
    ('Charles V, Emperor', [r'Charles the Fifth',
        r'Carol(?:o|e|en|n)?(?= ?(?:dem |V\b|V\.|quinto|Quinto))', r'(?<=keiser )Carol\w*',
        r'(?<=kayser )Carol\w*', r'(?<=Keyser )Carol\w*', r'(?<=keyser )Carol\w*',
        r'(?<=Imperatori )Carolo', r'Charles V(?![\w])']),
    ('Ferdinand I, Emperor', [r'Kaiser Ferdinands I\.']),
    ('Maximilian II, Emperor', [r'Kaiser Maximilians? II\.?', r'Maximilian II']),
    ('Sigismund II Augustus, King of Poland', [r'Sigismund Augustus', r'King Sigismund Augustus',
        r'Sigismundus Augustus']),
    ('Johann I, Count Palatine of Zweibrücken', [r'Duke Johann(?= announced)']),
    ('Karl I, Count Palatine of Birkenfeld', [r'Herrn Carol(?=, Pfalzgravens)',
        r'Lord Charles(?=, Count Palatine)']),
    ('Ernst, Count of Holstein-Schaumburg', [r'Graf/Fürst Ernst']),
    ('Edward VI, King of England', [r'Edward VI']),
    ('Schaumberg, Hans Paul von', [r'Hans Paul von Schaumberg', r'Hanns Paulus von Schaumberg',
        r'Paulus von Schaumberg']),
    # Fathers, popes and others of earlier times
    ('Leo I, Pope', [r"Leo(?='s Tome| to Flavian)"]),
    ('Flavian, Patriarch of Constantinople', [r'(?<=to )Flavian']),
    ('Gregory I, Pope', [r'Gregory(?: the Great)?', r'Gregorii']),
    ('Augustine', [r'Augustine', r'Augustin(?=[ ,.;:])', r'Augustini', r'Augustino', r'Augustinus']),
    ('Ambrose', [r'Ambrose', r'Ambrosii', r'Ambrosio']),
    ('Chrysostom, John', [r'Chrysostom(?:us)?']),
    ('Justin Martyr', [r'Justin(?: Martyr)?']),
    ('Tertullian', [r'Tertullian']),
    ('Prudentius', [r'Prudentius']),
    ('Muhammad (Mahomet)', [r'Mahomet(?!an)', r'Machomet']),
    ('Homer', [r'Homer']),
    ('Virgil', [r'Virgil']),
    ('Platina, Bartolomeo', [r'Platina']),
    ('Cyprian', [r'Cyprianus', r'Cyprian']),
    # Musicians and printers
    ('Rhau, Georg', [r'Georg Rhau', r'Rhau']),
    ('Walter, Johann', [r'Johann Walter', r'Walter(?=, Isaac)']),
    ('Senfl, Ludwig', [r'Senfl']),
    ('Lassus, Orlande de', [r'Orlando', r'Lassus', r'Orlandus', r'Orlandi', r'Lasso(?=,)']),
    ('Clemens non Papa, Jacobus', [r'Clemens(?: non Papa| Non Papa)?']),
    ('Victoria, Tomás Luis de', [r'(?:L\. de )?Victoria']),
    ('Isaac, Heinrich', [r'Isaac(?= and Josquin|, Josquin)']),
    ('Josquin des Prez', [r'Josquin']),
    ('Vaet, Jacobus', [r'Vaet']),
    ('Galliculus, Johannes', [r'Galliculus']),
    ('Daser, Ludwig', [r'Ludwig Daser']),
    ('Schröter, Leonhard', [r'Leonhard Schröter', r'Leonhardi Schroteri']),
    ('Forster, Georg', [r'Georg Forster']),
    ('Burck, Joachim a', [r'Joachim a Burck']),
    ('Babst, Valentin', [r'Valentin Babst']),
    ('Dressler, Gallus', [r'Gallus Dressler', r'Dressler']),
    ('Gesius, Bartholomäus', [r'Gesius']),
    ('Keuchenthal, Johannes', [r'Keuchenthal']),
    ('Meiland, Jakob', [r'Meiland']),
    ('Stiphelius, Laurentius', [r'Stiphelius']),
    ('Vögelin, Ernst', [r'Vögelin']),
    ('Wert, Giaches de', [r'Wert(?=, for)']),
]


def literal(form):
    """The longest run of plain characters that every match of a form contains, or ''. Only
    characters outside groups and classes count, and none that a quantifier governs."""
    atoms, depth, i = [], 0, 0          # the form's top-level atoms: a character, or None
    while i < len(form):
        c, i = form[i], i + 1
        if c == '\\':
            c, i = form[i], i + 1
            atom = None if c.isalnum() else c
        elif c == '[':
            i += form[i] == '^'
            i += form[i] == ']'
            while form[i] != ']':
                i += 2 if form[i] == '\\' else 1
            i += 1
            atom = None
        elif c == '(':
            depth += 1
            continue
        elif c == ')':
            depth -= 1
            atom = None
        elif c in '?*+{':
            if c == '{':
                i = form.index('}', i) + 1
            if depth == 0 and atoms:
                atoms[-1] = None
            continue
        elif c == '|':
            if depth == 0:
                return ''
            continue
        else:
            atom = None if c in '.^$' else c
        if depth == 0:
            atoms.append(atom)
    return max(''.join(a or '\0' for a in atoms).split('\0'), key=len)


# Each form is tried only on the blocks that contain its literal, which spares most of the work.
FORMS = [(re.compile(r'(?<![\w])(?:' + f + r')s?(?![\w])'), i, literal(f))
         for i, (_, forms) in enumerate(PERSONS) for f in forms]


def names(text):
    """[(start, end, person)] for the names in one block of the guide. The leftmost match is
    taken, and of the matches that begin at the same place, the longest; a match that
    overlaps one already taken is dropped."""
    found = sorted((m.start(), -m.end(), i) for rx, i, lit in FORMS if lit in text
                   for m in rx.finditer(text))
    out, last = [], 0
    for s, e, i in found:
        if s >= last:
            out.append((s, -e, i))
            last = -e
    return out


def collect(text):
    """Return the names in the guide as [(line, anchor, person, matched text)] and the
    anchors in order."""
    lines = text.split('\n')
    start = next(i for i, l in enumerate(lines) if l.startswith('## <a id="introduction"'))
    end = next(i for i, l in enumerate(lines) if l.startswith('## <a id="scripture-index"'))
    order = re.findall(r'^#{2,6}\s+<a id="([^"]+)"></a>', text, re.M)
    out = []
    for n, anchor, _, block in blocks(lines, start, end):
        block = normalize(block)
        out += [(n, anchor, i, block[s:e]) for s, e, i in names(block)]
    return out, order


# ---------------------------------------------------------------- writing the index

def fold(s):
    """A word as it sorts: without accents, case or punctuation."""
    s = unicodedata.normalize('NFKD', s)
    return re.sub(r'[\W_]', '', ''.join(c for c in s if not unicodedata.combining(c))).casefold()


def sort_key(heading):
    """Headings sort word by word up to the first comma or parenthesis, then by the rest. A
    ruler's numeral sorts as a number, before any name: Johann, Johann I, Johann IV,
    Johann Adolf."""
    head, rest = re.match(r'([^,(]*)[,(]?(.*)', heading).groups()

    def words(s):
        return tuple((0, roman(w), '') if roman(w) else (1, 0, fold(w)) for w in s.split())
    return words(head), words(rest)


def build(found, order):
    rank = {a: i for i, a in enumerate(order)}
    sections = {}
    for _, anchor, i, _ in found:
        sections.setdefault(i, set()).add(anchor)
    by_letter = {}
    for i in sorted(sections, key=lambda i: sort_key(PERSONS[i][0])):
        by_letter.setdefault(fold(PERSONS[i][0])[0].upper(), []).append(i)
    out = [' · '.join(f'[{x}](#per-{x.lower()})' for x in by_letter), '']
    for x, people in by_letter.items():
        out += [f'<a id="per-{x.lower()}"></a>**{x}**', '']
        for i in people:
            out.append(f'- {PERSONS[i][0]} — {links(sections[i], rank)}')
        out.append('')
    return '\n'.join(out).rstrip('\n'), len(sections)


def rebuild(text):
    i, j = text.find(START), text.find(END)
    if i < 0 or j < i:
        raise SystemExit('Index of persons markers not found')
    found, order = collect(text)
    body, n = build(found, order)
    named = {f[2] for f in found}
    unnamed = [p[0] for k, p in enumerate(PERSONS) if k not in named]
    return text[:i + len(START)] + '\n' + body + '\n' + text[j:], found, n, unnamed


def main():
    args = sys.argv[1:]
    paths = [a for a in args if not a.startswith('--')]
    path = paths[0] if paths else MASTER
    text = open(path, encoding='utf-8').read()
    new, found, n, unnamed = rebuild(text)
    if '--list' in args:
        for line, anchor, i, matched in found:
            print(f'{line}\t{label(anchor)}\t{PERSONS[i][0]}\t{matched}')
    for name in unnamed:
        print(f'not found in the guide: {name}')
    if '--check' in args:
        print(f'{len(found)} names, {n} persons; the index is {"current" if new == text else "out of date"}')
        sys.exit(1 if unnamed or new != text else 0)
    if '--list' not in args and new != text:
        open(path, 'w', encoding='utf-8').write(new)
    print(f'{len(found)} names, {n} persons')
    sys.exit(1 if unnamed else 0)


if __name__ == '__main__':
    main()
