#!/usr/bin/env python3
"""Build the Scripture index of the master guide.

The index lists every passage of Scripture that the guide cites by book and
chapter: in its own text, in the orders it quotes and in their translations.
Each reference is filed under the section it stands in, and each section is a
link. The list is written between the index markers; the note above them is
ordinary text.

References are found in three ways:
- the usual forms, in English, Latin and German: "Acts 2:42", "1 Cor 11:28",
  "Ps 124:8", "Act. 6, 3", "1. Sam. III. 1.", "Joan. 5 [39]",
  "Johannis am 2. capitel";
- psalms named by number in prose: "den 111. psalm", "the hundred and
  eleventh psalm";
- chapters named in prose: "the 53rd chapter of Isaiah", "das 6. capitel
  Johannis".
Forms the rules cannot read, and the places where the text's own numbering
must be corrected (a psalm numbered as in the Vulgate, a misprint the editor
corrects), are listed in PROSE below. An entry there that no longer matches
the guide is reported.

Psalms are numbered as in the English Bible, and books are named as in the
Authorized Version, with the Apocrypha between the Testaments.

Usage:
    python3 tools/master_scripture.py           rebuild the index in place
    python3 tools/master_scripture.py --check   only report whether it is current
    python3 tools/master_scripture.py --list    print every reference found
"""
import re
import sys

from master_links import expected_label

MASTER = 'LITURGICAL_AND_ECCLESIASTICAL_LIFE.md'
START = '<!-- Scripture index start: generated by tools/master_scripture.py; do not edit by hand -->'
END = '<!-- Scripture index end -->'

# key, name, chapters, part, full names, abbreviations.
# A key starting with a digit is one of a numbered series (1 Samuel, 2 Samuel);
# its forms then need the number before them ("1 Cor", "2. Par.").
BOOKS = [
    ('gen', 'Genesis', 50, 'OT', 'Genesis Genesi', 'Gen Genes'),
    ('exod', 'Exodus', 40, 'OT', 'Exodus Exodi', 'Exod'),
    ('lev', 'Leviticus', 27, 'OT', 'Leviticus Levitici', 'Lev Levit'),
    ('num', 'Numbers', 36, 'OT', 'Numbers Numeri Numerorum', 'Num Nume Numer'),
    ('deut', 'Deuteronomy', 34, 'OT', 'Deuteronomy Deuteronomii Deuteronomium', 'Deut Deuter'),
    ('josh', 'Joshua', 24, 'OT', 'Joshua Josua Iosue Josue', 'Josh'),
    ('judg', 'Judges', 21, 'OT', 'Judges Judicum', 'Judg Judic'),
    ('ruth', 'Ruth', 4, 'OT', 'Ruth', ''),
    ('1sam', 'Samuel', 31, 'OT', 'Samuel Samuelis', 'Sam'),
    ('2sam', 'Samuel', 24, 'OT', '', ''),
    ('1kgs', 'Kings', 22, 'OT', 'Kings Könige', 'Kgs Kön'),
    ('2kgs', 'Kings', 25, 'OT', '', ''),
    ('1chr', 'Chronicles', 29, 'OT', 'Chronicles Paralipomenon', 'Chron Chr Par Paral Paralip'),
    ('2chr', 'Chronicles', 36, 'OT', '', ''),
    ('ezra', 'Ezra', 10, 'OT', 'Ezra Esra', ''),
    ('neh', 'Nehemiah', 13, 'OT', 'Nehemiah Nehemia Nehemias', 'Neh Nehem'),
    ('esth', 'Esther', 10, 'OT', 'Esther', 'Esth'),
    ('job', 'Job', 42, 'OT', 'Job Hiob Iob', ''),
    ('ps', 'Psalms', 150, 'OT', 'Psalm Psalms Psalmus psalmus Psalmen Psalmo Psalmi', 'Ps Psal Pss'),
    ('prov', 'Proverbs', 31, 'OT', 'Proverbs Proverbiorum', 'Prov Proverb'),
    ('eccl', 'Ecclesiastes', 12, 'OT', 'Ecclesiastes Ecclesiastae', 'Eccl Eccles'),
    ('song', 'Song of Solomon', 8, 'OT', 'Hohelied Hoheslied', 'Cant'),
    ('isa', 'Isaiah', 66, 'OT', 'Isaiah Isaias Esaias Esaiae Esaia Jesaja Jesaia Jesajae Jesaiae',
     'Isa Esa Jes Esai'),
    ('jer', 'Jeremiah', 52, 'OT', 'Jeremiah Jeremias Jeremiae Jeremia', 'Jer Jerem'),
    ('lam', 'Lamentations', 5, 'OT', 'Lamentations Threni Klagelieder', 'Lam Thren'),
    ('ezek', 'Ezekiel', 48, 'OT', 'Ezekiel Ezechiel Hesekiel Ezechielis', 'Ezek Ezech Hes'),
    ('dan', 'Daniel', 12, 'OT', 'Daniel Danielis', 'Dan'),
    ('hos', 'Hosea', 14, 'OT', 'Hosea Osee Oseae Hoseas', 'Hos'),
    ('joel', 'Joel', 3, 'OT', 'Joel', ''),
    ('amos', 'Amos', 9, 'OT', 'Amos', ''),
    ('obad', 'Obadiah', 1, 'OT', 'Obadiah Abdias Obadja', 'Obad Abd'),
    ('jonah', 'Jonah', 4, 'OT', 'Jonah Jona Jonae', ''),
    ('mic', 'Micah', 7, 'OT', 'Micah Michaeas Micha Michae', 'Mic Mich'),
    ('nah', 'Nahum', 3, 'OT', 'Nahum', 'Nah'),
    ('hab', 'Habakkuk', 3, 'OT', 'Habakkuk Habacuc Habakuk', 'Hab Habac'),
    ('zeph', 'Zephaniah', 3, 'OT', 'Zephaniah Sophonias Zephanja', 'Zeph Soph'),
    ('hag', 'Haggai', 2, 'OT', 'Haggai Aggaeus', 'Hag Agg'),
    ('zech', 'Zechariah', 14, 'OT', 'Zechariah Zacharias Sacharja', 'Zech Zach'),
    ('mal', 'Malachi', 4, 'OT', 'Malachi Malachias Maleachi', 'Mal'),
    ('tob', 'Tobit', 14, 'AP', 'Tobit Tobiae', 'Tob'),
    ('jdt', 'Judith', 16, 'AP', 'Judith', 'Jdt'),
    ('wis', 'Wisdom of Solomon', 19, 'AP', 'Wisdom Sapientia Sapientiae', 'Wis Sap'),
    ('sir', 'Ecclesiasticus (Sirach)', 51, 'AP', 'Sirach Ecclesiasticus Syrach', 'Sir Ecclus Syr'),
    ('bar', 'Baruch', 6, 'AP', 'Baruch', 'Bar'),
    ('1macc', 'Maccabees', 16, 'AP', 'Maccabees Machabaeorum', 'Macc Mach Makk'),
    ('2macc', 'Maccabees', 15, 'AP', '', ''),
    ('matt', 'Matthew', 28, 'NT', 'Matthew Matthaei Matthei Matthäus Matthaeus Mattheus Mattheo',
     'Matt Mt Matth Mat Math'),
    ('mark', 'Mark', 16, 'NT', 'Mark Marci Markus', 'Mk Marc Mar'),
    ('luke', 'Luke', 24, 'NT', 'Luke Lucae Luce Lukas', 'Lk Luc Luk'),
    ('john', 'John', 21, 'NT', 'John Johannis Joannis Johannes Joannes', 'Jn Joh Johan Joan Ioh'),
    ('acts', 'Acts', 28, 'NT', 'Acts Acta Actorum Apostelgeschichte', 'Act Actor Apg Ap.-G'),
    ('rom', 'Romans', 16, 'NT', 'Romans Römer Römern Romern Romanos', 'Rom Röm'),
    ('1cor', 'Corinthians', 16, 'NT', 'Corinthians Corinther Corinthern Korinther Korinthern Corinthios',
     'Cor Kor Corinth Corint'),
    ('2cor', 'Corinthians', 13, 'NT', '', ''),
    ('gal', 'Galatians', 6, 'NT', 'Galatians Galater Galatern Galatas', 'Gal Galat'),
    ('eph', 'Ephesians', 6, 'NT', 'Ephesians Epheser Ephesern Ephesios', 'Eph Ephes'),
    ('phil', 'Philippians', 4, 'NT', 'Philippians Philipper Philippern Philippenses', 'Phil Philipp'),
    ('col', 'Colossians', 4, 'NT', 'Colossians Colosser Colossern Kolosser Colossenses', 'Col Coloss Kol'),
    ('1thess', 'Thessalonians', 5, 'NT', 'Thessalonians Thessalonicher Thessalonichern Thessalonicenses',
     'Thess Thes'),
    ('2thess', 'Thessalonians', 3, 'NT', '', ''),
    ('1tim', 'Timothy', 6, 'NT', 'Timothy Timotheum Timothei', 'Tim Timo Timot Timoth'),
    ('2tim', 'Timothy', 4, 'NT', '', ''),
    ('titus', 'Titus', 3, 'NT', 'Titus Tito Titum', 'Tit'),
    ('phlm', 'Philemon', 1, 'NT', 'Philemon', 'Philem Phlm'),
    ('heb', 'Hebrews', 13, 'NT', 'Hebrews Hebräer Ebräer Hebraeos Ebreer', 'Heb Hebr Ebr'),
    ('jas', 'James', 5, 'NT', 'James Jacobi Iacobi', 'Jas Jac Jaco Jak'),
    ('1pet', 'Peter', 5, 'NT', 'Peter Petri', 'Pet'),
    ('2pet', 'Peter', 3, 'NT', '', ''),
    ('1john', 'John', 5, 'NT', '', ''),
    ('2john', 'John', 1, 'NT', '', ''),
    ('3john', 'John', 1, 'NT', '', ''),
    ('jude', 'Jude', 1, 'NT', 'Jude Judae', ''),
    ('rev', 'Revelation', 22, 'NT', 'Revelation Apocalypse Apocalypsis Offenbarung', 'Rev Apoc Offb Offenb'),
]

# Forms the rules cannot read, and corrections. Each entry is a stretch of the
# guide's text (with line breaks and emphasis removed) and the references it
# stands for, separated by semicolons. The stretch is taken out of the text
# before the rules run, so that nothing in it is read twice.
PROSE = [
    # Psalms numbered as in the Vulgate.
    ('Der 42. psalm', 'Ps 43'),
    ('The 42nd psalm', 'Ps 43'),
    ('Psalm 123: Unser hilf', 'Ps 124:8'),
    ('Psalm 123: Our help', 'Ps 124:8'),
    # Luther's "psal. 96", corrected by the editor.
    ('Vel illa psal. 96.', 'Ps 67'),
    ('Psalm 96 [67]', 'Ps 67'),
    # Psalms named in prose, beyond the rules.
    ('den 33. Psalm biß auf den 7. versicul', 'Ps 33:1-7'),
    ('the thirty-third psalm, as far as the seventh verse', 'Ps 33:1-7'),
    ('den 93. Psalm: Gott als ein könig etc., den 100.: Ihr völker auf der erden all etc. oder den '
     '117.: Den Herrn lobt ihr etc. oder den 121.', 'Ps 93; Ps 100; Ps 117; Ps 121'),
    ('the ninety-third psalm, "God as a king," etc., the hundredth, "Ye peoples on the earth all," '
     'etc., or the hundred and seventeenth, "Praise ye the Lord," etc., or the hundred and '
     'twenty-first', 'Ps 93; Ps 100; Ps 117; Ps 121'),
    ('den 127. psalm, oder den 128.', 'Ps 127; Ps 128'),
    ('the hundred and twenty-seventh psalm be sung, or the hundred and twenty-eighth',
     'Ps 127; Ps 128'),
    ('ein psalm als der 8. 16. 22. 69. 110.', 'Ps 8; Ps 16; Ps 22; Ps 69; Ps 110'),
    ('as the 8th, 16th, 22nd, 69th, 110th', 'Ps 8; Ps 16; Ps 22; Ps 69; Ps 110'),
    ('the psalms of preparation (84, 85, 86, 116, 130)', 'Ps 84; Ps 85; Ps 86; Ps 116; Ps 130'),
    ('the second psalm, "Help, God, how goeth it ever so,"', 'Ps 2'),
    # Chapters named in prose, beyond the rules.
    ('the first chapter of the epistle to the Romans', 'Rom 1'),
    ('Johannis am sechsten capitel', 'John 6'),
    ('in der ersten epistel an die Corint. am XI. capitel [23-29]', '1 Cor 11:23-29'),
    ('in the first epistle to the Corinthians, in the eleventh chapter', '1 Cor 11'),
    ('auß der ersten Epistel Pauli am 11. capitel zu den Corinthern', '1 Cor 11'),
    ('out of the first Epistle of Paul to the Corinthians, the eleventh chapter', '1 Cor 11'),
    ('die epistel zun Colossern am andern', 'Col 2'),
    ('in der 1. zun Corinthern am 14.', '1 Cor 14'),
    ('aus dem Mattheo das ander Capitel', 'Matt 2'),
    ('das 6 te capitel Johannis', 'John 6'),
    # Abbreviations the rules do not take.
    ('Thimo. 3. 1', '1 Tim 3:1'),
    ('Jo. 6 [56 u. 54]', 'John 6:56; John 6:54'),
    ('John 6[:56 and 54]', 'John 6:56; John 6:54'),
    ('1. Tim. 3 (8f. 12)', '1 Tim 3:8f.; 1 Tim 3:12'),
    ('apostel Timot. 2', '1 Tim 2'),
    ('the Apostle in Timothy 2', '1 Tim 2'),
    ('[l.Kor. 10, 17]', '1 Cor 10:17'),
    ('2. Reg. IV. 38.', '2 Kgs 4:38'),
    ('2. Reg. IV. 20.', '2 Kgs 4:20'),
]

ORDINALS = {
    'first': 1, 'second': 2, 'third': 3, 'fourth': 4, 'fifth': 5, 'sixth': 6, 'seventh': 7,
    'eighth': 8, 'ninth': 9, 'tenth': 10, 'eleventh': 11, 'twelfth': 12, 'thirteenth': 13,
    'fourteenth': 14, 'fifteenth': 15, 'sixteenth': 16, 'seventeenth': 17, 'eighteenth': 18,
    'nineteenth': 19, 'twentieth': 20, 'thirtieth': 30, 'fortieth': 40, 'fiftieth': 50,
    'sixtieth': 60, 'seventieth': 70, 'eightieth': 80, 'ninetieth': 90, 'hundredth': 100,
}
TENS = {'twenty': 20, 'thirty': 30, 'forty': 40, 'fifty': 50, 'sixty': 60, 'seventy': 70,
        'eighty': 80, 'ninety': 90}
ORD_WORD = '|'.join(sorted(ORDINALS, key=len, reverse=True))
ORD = (r'(?:\d+(?:st|nd|rd|th)|(?:(?:one\s+)?hundred(?:\s+and\s+|\s+))?'
       r'(?:(?:' + '|'.join(TENS) + r')-)?(?:' + ORD_WORD + r'))')


def ordinal(s):
    """The number an English ordinal stands for: 'hundred and twenty-seventh' -> 127."""
    s = s.lower().strip()
    m = re.fullmatch(r'(\d+)(?:st|nd|rd|th)', s)
    if m:
        return int(m.group(1))
    n = 0
    m = re.match(r'(?:one\s+)?hundred(?:\s+and\s+|\s+)(.+)', s)
    if m:
        n, s = 100, m.group(1)
    m = re.fullmatch(r'(\w+)-(\w+)', s)
    if m:
        return n + TENS[m.group(1)] + ORDINALS[m.group(2)]
    return n + ORDINALS[s]


def roman(s):
    vals = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100}
    if not re.fullmatch(r'C{0,1}(?:XC|XL|L?X{0,3})(?:IX|IV|V?I{0,3})', s) or not s:
        return None
    total = 0
    for a, b in zip(s, s[1:] + ' '):
        total += -vals[a] if b != ' ' and vals[b] > vals[a] else vals[a]
    return total


# ---------------------------------------------------------------- the book table

# The forms the guide's own English uses; any other form is Latin or German.
ENGLISH = set('''Genesis Exodus Leviticus Numbers Deuteronomy Joshua Judges Ruth Samuel Kings
    Chronicles Ezra Nehemiah Esther Job Psalm Psalms Proverbs Ecclesiastes Isaiah Jeremiah
    Lamentations Ezekiel Daniel Hosea Joel Amos Obadiah Jonah Micah Nahum Habakkuk Zephaniah
    Haggai Zechariah Malachi Tobit Judith Wisdom Sirach Ecclesiasticus Baruch Maccabees Matthew
    Mark Luke John Acts Romans Corinthians Galatians Ephesians Philippians Colossians
    Thessalonians Timothy Titus Philemon Hebrews James Peter Jude Revelation Gen Exod Lev Num
    Deut Josh Judg Sam Kgs Chron Neh Esth Ps Pss Prov Eccl Isa Jer Lam Ezek Dan Hos Obad Mic
    Nah Hab Zeph Hag Zech Mal Tob Jdt Wis Sir Bar Macc Matt Mt Mk Lk Jn Rom Cor Gal Eph Phil
    Col Thess Tim Tit Phlm Heb Jas Pet Rev'''.split())

KEY = {b[0]: i for i, b in enumerate(BOOKS)}
FORMS = {}      # form -> (base key, full word?)
for key, name, chapters, part, full, abbr in BOOKS:
    for f in full.split():
        FORMS[f] = (key, True)
    for f in abbr.split():
        FORMS.setdefault(f, (key, False))
NUMBERED_BASES = {k for k in KEY if k[0] == '1'}            # '1sam', '1cor', ...
FORM_RE = '|'.join(re.escape(f) for f in sorted(FORMS, key=len, reverse=True))
BOOK_TOKEN = re.compile(
    r'(?<![\w.])(?:(?P<pre>IV|III|II|I|[1-4])(?:\.\s*|\s+))?'
    r'(?P<form>' + FORM_RE + r')(?![^\W\d_])(?P<dot>\.)?')
NUMBERED_AHEAD = re.compile(r'\s*\.?\s*(?:' + FORM_RE + r')(?![^\W\d_])')


def resolve(form, pre):
    """The book key for a form and its number, or None."""
    base, full = FORMS[form]
    if base == 'john' and pre:
        base = '1john'
    if base in NUMBERED_BASES:
        if not pre:
            return None
        n = int(pre) if pre.isdigit() else roman(pre)
        key = f'{n}{base[1:]}'
        return key if key in KEY else None
    return None if pre and not base.startswith(pre) else base


def chapters(key):
    return BOOKS[KEY[key]][2]


def ref(key, c1, v1=None, c2=None, v2=None, sfx=''):
    return (KEY[key], c1, v1, c2, v2, sfx)


def parse_ref(s):
    """Parse a reference written as in PROSE ('1 Cor 11:23-29') into a reference tuple."""
    m = re.fullmatch(r'(?:([1-3]) )?(\w+) (\d+)(?::(\d+)(ff?\.)?(?:-(\d+))?)?', s.strip())
    pre, form, c, v, sfx, v2 = m.groups()
    return ref(resolve(form, pre), int(c), int(v) if v else None, None, int(v2) if v2 else None,
               sfx or '')


# ---------------------------------------------------------------- reading the text

def tail_spec(s, i, key, source, roman_ok):
    """Read the chapter and verses after a book name at s[i:].

    source: the reference is written in the Latin or German way, where "Act. 6, 3"
    is chapter 6, verse 3; in the English way a comma separates chapters ("Ps 67, 51").
    roman_ok: the chapter may be a Roman numeral ("1. Sam. III. 1.").
    Returns (list of references, end position); the list is empty if no chapter follows.
    """
    n = chapters(key)
    m = re.compile(r'\s*(?:am\s+|cap\.\s*|capite\s+|capitel\s+)?').match(s, i)
    j = m.end()
    m = re.compile(r'(\d{1,3})(?![\d\w])').match(s, j)
    if m:
        c = int(m.group(1))
    else:
        m = re.compile(r'([IVXLC]+)(?=[.:,\[]|\s+capite)').match(s, j)
        if not (m and roman_ok):
            return [], i
        c = roman(m.group(1))
        if c is None:
            return [], i
    if not 1 <= c <= n:
        return [], i
    j = m.end()
    # the word "chapter" after the number: "am 2. capitel", "49 cap.", "VI. capite"
    m = re.compile(r'\.?\s*(?:capitel|Capitel|cap\.|capite)(?!\w)').match(s, j)
    if m:
        j = m.end()
    out = []
    v = v2 = c2 = None
    sfx = ''
    verse = re.compile(r'(?::|\[:)(\d{1,3})(?:\])?'                         # 3:16, 4[:9]
                       r'|[.,]?\s*(?:V|v|vers|Vers|verse|Verse)\.?\s*(\d{1,3})(?!\d)'  # 2. vers. 9
                       r'|[.,]?\s*\[(\d{1,3})(?=\s*(?:[-–]\s*\d{1,3}\s*)?(?:ff?\.)?\])')  # 5 [39], 2, [1f.]
    verse_q = re.compile(r',\s*(\d{1,3})(?!\d)(?!\s*\.\s*\d)'                # Act. 6, 3
                         r'|\.\s*(\d{1,3})(?=\s*[.\[]|\s+[a-zäöü]|\s*$)')      # III. 1.
    m = verse.match(s, j) or (verse_q.match(s, j) if source else None)
    if m:
        v = int(next(g for g in m.groups() if g))
        j = m.end()
        m = re.compile(r'(ff?\.)').match(s, j)
        if m:
            sfx, j = m.group(1), m.end()
        m = re.compile(r'\s*[-–—]\s*(\d{1,3})(?::(\d{1,3}))?(?![\d])').match(s, j)
        if m:
            if m.group(2):
                c2, v2 = int(m.group(1)), int(m.group(2))
            else:
                v2 = int(m.group(1))
            j = m.end()
        m = re.compile(r'(ff?\.)?\]').match(s, j)        # close "[1f.]", "[1-7]"
        if m and s[:j].rfind('[') > s[:j].rfind(']'):
            sfx, j = m.group(1) or sfx, m.end()
        out.append(ref(key, c, v, c2, v2, sfx))
        # more verses of the same chapter, "2:18, 21–24", or of another, "9:28; 10:14"
        while True:
            m = re.compile(r',\s*(\d{1,3})(?:\s*[-–]\s*(\d{1,3}))?(?![\d:])').match(s, j)
            if m and not NUMBERED_AHEAD.match(s, m.end()):
                out.append(ref(key, c, int(m.group(1)), None, int(m.group(2)) if m.group(2) else None))
                j = m.end()
                continue
            m = re.compile(r'[,;]\s*(\d{1,3}):(\d{1,3})(?:\s*[-–]\s*(\d{1,3}))?(?!\d)').match(s, j)
            if m and 1 <= int(m.group(1)) <= n:
                c = int(m.group(1))
                out.append(ref(key, c, int(m.group(2)), None, int(m.group(3)) if m.group(3) else None))
                j = m.end()
                continue
            break
    else:
        m = re.compile(r'\s*[-–]\s*(\d{1,3})(?![\d:])').match(s, j)
        if m and c < int(m.group(1)) <= n:
            c2, j = int(m.group(1)), m.end()
        out.append(ref(key, c, None, c2))
        if not source:
            # more chapters of the same book: "Ps 67, 51, 130", "Psalms 127 and 128"
            while True:
                m = re.compile(r'(?:,\s*|\s+and\s+|\s+or\s+|\s*/\s*)(\d{1,3})(?![\d\w])'
                               r'(?::(\d{1,3})(?:[-–](\d{1,3}))?)?').match(s, j)
                if not m or NUMBERED_AHEAD.match(s, m.end()) or not 1 <= int(m.group(1)) <= n:
                    break
                c = int(m.group(1))
                out.append(ref(key, c, int(m.group(2)) if m.group(2) else None, None,
                               int(m.group(3)) if m.group(3) else None))
                j = m.end()
    return out, j


ENGLISH_BOOK = {b[1]: b[0] for b in BOOKS if not b[0][0].isdigit()}
EN_RE = '|'.join(sorted(ENGLISH_BOOK, key=len, reverse=True))
PROSE_RULES = [
    # the 53rd chapter of Isaiah; the sixth chapter of John
    (re.compile(r'\b[Tt]he\s+(?P<ord>' + ORD + r')\s+chapter\s+of\s+(?P<book>' + EN_RE + r')\b'), 'en'),
    # Numbers the sixth chapter; John in the second chapter
    (re.compile(r'\b(?P<book>' + EN_RE + r'),?\s+(?:in\s+)?the\s+(?P<ord>' + ORD + r')\s+chapter\b'), 'en'),
    # James, chapter 5
    (re.compile(r'\b(?P<book>' + EN_RE + r'),?\s+chapter\s+(?P<num>\d{1,3})\b'), 'en'),
    # das 6. capitel Johannis
    (re.compile(r'\bdas\s+(?P<num>\d{1,3})\.\s*[Cc]apitel\s+(?P<form>' + FORM_RE + r')\b'), 'de'),
    # the hundred and eleventh psalm; the twenty-third, hundred and third, hundred and eleventh psalm
    (re.compile(r'\b[Tt]he\s+(?P<ords>' + ORD + r'(?:\s*,\s*' + ORD + r')*(?:\s*,?\s+(?:and|or)\s+'
                + ORD + r')?)\s+psalms?\b'), 'ps-en'),
    # den 111. psalm; der 23., 103., 111. psalm; den CXI. psalm
    (re.compile(r'\b(?:[Dd]en|[Dd]er|[Dd]em|[Dd]es)\s+(?P<nums>(?:(?:\d{1,3}|[IVXLC]{1,8})\.\s*,?\s*)+)'
                r'(?:\[[^\]]*\]\s*)?[Pp]salm(?:en|e|us)?\b'), 'ps-de'),
]


def prose_refs(m, kind):
    """The references a match of one of the PROSE_RULES stands for."""
    if kind == 'en':
        key = ENGLISH_BOOK[m.group('book')]
        c = ordinal(m.group('ord')) if m.groupdict().get('ord') else int(m.group('num'))
        return [ref(key, c)] if c <= chapters(key) else []
    if kind == 'de':
        key = resolve(m.group('form'), None)
        c = int(m.group('num'))
        return [ref(key, c)] if key and c <= chapters(key) else []
    if kind == 'ps-en':
        nums = [ordinal(o) for o in re.findall(ORD, m.group('ords'))]
        if nums in ([1], [2]):          # "the first psalm or hymn": a count, not a number
            return []
        return [ref('ps', n) for n in nums if n <= 150]
    nums = [int(x) if x.isdigit() else roman(x) for x in re.findall(r'\d+|[IVXLC]+', m.group('nums'))]
    return [ref('ps', n) for n in nums if n and n <= 150]


def normalize(text):
    text = re.sub(r'`[^`]*`', ' ', text)
    text = re.sub(r'(?<!!)\[((?:[^\[\]\\]|\\.|\[[^\]]*\])*)\]\(#[^)\s]+\)', r'\1', text)
    text = text.replace('*', '')
    text = re.sub(r'(?<=[A-Za-z])\[([a-z]+)\](?=[\s.,;:])', r'\1', text)   # Jes[ajae], Gene[sis]
    return re.sub(r'\s+', ' ', text).strip()


def references(text, quote, used):
    """Return [(matched text, reference)] for one block of the guide; quote is true for a
    block quotation, that is, the text of an order."""
    found = []
    for snippet, refs in PROSE:
        while snippet in text:
            used.add(snippet)
            found += [(snippet, parse_ref(r)) for r in refs.split(';')]
            text = text.replace(snippet, ' ' * len(snippet), 1)
    for rule, kind in PROSE_RULES:
        for m in rule.finditer(text):
            refs = prose_refs(m, kind)
            if refs:
                found += [(m.group(0), r) for r in refs]
                text = text[:m.start()] + ' ' * (m.end() - m.start()) + text[m.end():]
    i = 0
    while True:
        m = BOOK_TOKEN.search(text, i)
        if not m:
            break
        i = m.end()
        form, full = m.group('form'), FORMS[m.group('form')][1]
        if full and m.group('dot'):
            continue                    # "The day of Philip and James. 7." is a list, not a verse
        key = resolve(form, m.group('pre'))
        if key is None and m.group('pre') and FORMS[form][0] not in NUMBERED_BASES:
            key = resolve(form, None)   # "3. Psalms 127 and 128": the number is the list's
        if key is None:
            continue
        source = quote or bool(m.group('dot')) or form not in ENGLISH
        refs, j = tail_spec(text, m.end(), key, source, quote or bool(m.group('dot')))
        if refs:
            found += [(text[m.start():j].strip(), r) for r in refs]
            i = j
    return found


def blocks(lines, start, end):
    """Yield (line number, anchor, quotation?, text) for each paragraph, item, row and heading."""
    anchor, cur, cur_n, cur_q = None, [], None, False
    for i in range(start, end):
        line = lines[i]
        h = re.match(r'^#{2,6}\s+<a id="([^"]+)"></a>', line)
        if h:
            if cur:
                yield cur_n, anchor, cur_q, ' '.join(cur)
                cur = []
            anchor = h.group(1)
            yield i + 1, anchor, False, line[h.end():]
            continue
        s = line.strip()
        if not s or s.startswith('<!--') or s.startswith('<div'):
            if cur:
                yield cur_n, anchor, cur_q, ' '.join(cur)
                cur = []
            continue
        q = s.startswith('>')
        t = re.sub(r'^>\s?', '', s) if q else s
        # a numbered line in a quotation is usually a wrapped line of Sehling's text
        new_item = bool(re.match(r'^(?:[-*+]|\d+\.)\s', t) and not q) or t.startswith('|')
        if cur and (q != cur_q or new_item or cur[-1].startswith('|')):
            yield cur_n, anchor, cur_q, ' '.join(cur)
            cur = []
        if not cur:
            cur_n, cur_q = i + 1, q
        cur.append(t)
    if cur:
        yield cur_n, anchor, cur_q, ' '.join(cur)


def collect(text):
    """Return the references of the guide as [(line, anchor, matched text, reference)],
    the anchors in order, and the PROSE entries that matched nothing."""
    lines = text.split('\n')
    start = next(i for i, l in enumerate(lines) if l.startswith('## <a id="introduction"'))
    end = next(i for i, l in enumerate(lines) if l.startswith('## <a id="scripture-index"'))
    order = [a for a in re.findall(r'^#{2,6}\s+<a id="([^"]+)"></a>', text, re.M)]
    used, out = set(), []
    for n, anchor, quote, block in blocks(lines, start, end):
        for matched, r in references(normalize(block), quote, used):
            out.append((n, anchor, matched, r))
    stale = [s for s, _ in PROSE if s not in used]
    return out, order, stale


# ---------------------------------------------------------------- writing the index

def book_name(key):
    name = BOOKS[KEY[key]][1]
    return f'{key[0]} {name}' if key[0].isdigit() else name


def show(r):
    _, c1, v1, c2, v2, sfx = r
    if v1 is None:
        return f'{c1}–{c2}' if c2 else f'{c1}'
    s = f'{c1}:{v1}{sfx}'
    if c2:
        return f'{s}–{c2}:{v2}'
    return f'{s}–{v2}' if v2 else s


def label(anchor):
    """The label of a link to a section: '13.7.2', 'Chapter 3' or 'Introduction'."""
    if re.fullmatch(r'ch\d+', anchor):
        return f'Chapter {anchor[2:]}'
    if anchor.startswith(('introduction', 'intro-', 'repo-')):
        return 'Introduction'
    if anchor.startswith(('conventions', 'conv-')):
        return 'Conventions'
    return expected_label(anchor)


def links(anchors, rank):
    """The links to a set of sections, in the order of the guide. The sections of the front
    matter share a label, as "Introduction", and each label is linked once, to its first
    section."""
    first = {}
    for a in sorted(anchors, key=rank.get):
        first.setdefault(label(a), a)
    return ', '.join(f'[{lab}](#{a})' for lab, a in first.items())


def build(found, order):
    rank = {a: i for i, a in enumerate(order)}
    entries = {}
    for _, anchor, _, r in found:
        entries.setdefault(r, set()).add(anchor)
    by_book = {}
    for r in sorted(entries, key=lambda r: (r[0], r[1], r[2] or 0, r[3] or r[1], r[4] or r[2] or 0, r[5])):
        by_book.setdefault(r[0], []).append(r)
    parts = {'OT': 'Old Testament', 'AP': 'Apocrypha', 'NT': 'New Testament'}
    out = []
    for part, title in parts.items():
        keys = [BOOKS[b][0] for b in by_book if BOOKS[b][3] == part]
        if keys:
            out.append(f'**{title}:** ' + ' · '.join(f'[{book_name(k)}](#scr-{k})' for k in keys))
            out.append('')
    for b, refs in by_book.items():
        key = BOOKS[b][0]
        out.append(f'<a id="scr-{key}"></a>**{book_name(key)}**')
        out.append('')
        for r in refs:
            out.append(f'- {show(r)} — {links(entries[r], rank)}')
        out.append('')
    return '\n'.join(out).rstrip('\n'), len(entries)


def rebuild(text):
    i, j = text.find(START), text.find(END)
    if i < 0 or j < i:
        raise SystemExit('Scripture index markers not found')
    found, order, stale = collect(text)
    body, n = build(found, order)
    return text[:i + len(START)] + '\n' + body + '\n' + text[j:], found, n, stale


def main():
    args = sys.argv[1:]
    paths = [a for a in args if not a.startswith('--')]
    path = paths[0] if paths else MASTER
    text = open(path, encoding='utf-8').read()
    new, found, n, stale = rebuild(text)
    if '--list' in args:
        for line, anchor, matched, r in found:
            print(f'{line}\t{label(anchor)}\t{book_name(BOOKS[r[0]][0])} {show(r)}\t{matched}')
    for s in stale:
        print(f'not found in the guide: {s!r}')
    if '--check' in args:
        print(f'{len(found)} references, {n} entries; the index is {"current" if new == text else "out of date"}')
        sys.exit(1 if stale or new != text else 0)
    if '--list' not in args and new != text:
        open(path, 'w', encoding='utf-8').write(new)
    print(f'{len(found)} references, {n} entries')
    sys.exit(1 if stale else 0)


if __name__ == '__main__':
    main()
