#!/usr/bin/env python3
"""Rebuild the table of contents of the master guide from its headings.

Every heading below the title carries an explicit anchor, for example

    ### <a id="s2-3"></a>2.3 The families of evangelical ordo

The contents list between the TOC markers is regenerated from those anchors,
one nested list item per heading. The script also reports headings without an
anchor and anchors used more than once, and exits with status 1 if it finds
any.

Usage:
    python3 tools/master_toc.py            rebuild the contents in place
    python3 tools/master_toc.py --check    only report whether they are current
"""
import re
import sys

MASTER = 'LITURGICAL_AND_ECCLESIASTICAL_LIFE.md'
START = '<!-- TOC start: generated by tools/master_toc.py; do not edit by hand -->'
END = '<!-- TOC end -->'
HEADING = re.compile(r'^(#{2,6})\s+(.*)$')
ANCHORED = re.compile(r'^<a id="([^"]+)"></a>(.*)$')


def headings(lines):
    """Yield (line number, level, anchor or None, title) for each heading below the title."""
    fence = False
    for n, line in enumerate(lines, 1):
        if line.startswith('```'):
            fence = not fence
        if fence:
            continue
        m = HEADING.match(line)
        if not m:
            continue
        a = ANCHORED.match(m.group(2).strip())
        if a:
            yield n, len(m.group(1)), a.group(1), a.group(2).strip()
        else:
            yield n, len(m.group(1)), None, m.group(2).strip()


def toc_items(text):
    """Return the contents list and a list of problems found."""
    items, seen, problems = [], {}, []
    for n, level, aid, title in headings(text.split('\n')):
        if aid is None:
            problems.append(f'line {n}: heading without an anchor: {title[:70]}')
            continue
        if aid in seen:
            problems.append(f'line {n}: anchor "{aid}" is also used at line {seen[aid]}')
        seen[aid] = n
        if aid == 'contents':
            continue
        label = title.replace('[', '\\[').replace(']', '\\]')
        items.append('  ' * (level - 2) + f'- [{label}](#{aid})')
    return items, problems


def rebuild(text):
    """Return the text with its contents list regenerated, and the problems found."""
    i, j = text.find(START), text.find(END)
    if i < 0 or j < i:
        raise SystemExit('TOC markers not found')
    items, problems = toc_items(text)
    return text[:i + len(START)] + '\n' + '\n'.join(items) + '\n' + text[j:], items, problems


def main():
    check = '--check' in sys.argv[1:]
    paths = [a for a in sys.argv[1:] if not a.startswith('--')]
    path = paths[0] if paths else MASTER
    text = open(path, encoding='utf-8').read()
    new, items, problems = rebuild(text)
    for p in problems:
        print(p)
    if check:
        print(f'{len(items)} entries; contents are {"current" if new == text else "out of date"}')
        sys.exit(1 if problems or new != text else 0)
    if new != text:
        open(path, 'w', encoding='utf-8').write(new)
    print(f'{len(items)} entries written to {path}')
    sys.exit(1 if problems else 0)


if __name__ == '__main__':
    main()
